// AI Engineer path — Module 3 (Classical ML with scikit-learn) quiz bank.
// [lessonSlug, prompt, [correct, ...distractors], correctIndex=0, explanation, difficulty, styleTag]
// NOTE (content-first remodel): the LIVE quiz set in the DB is thinned to ONE sharpest question
// per lesson. This file keeps the fuller authored bank for reference; the DB is the source of truth.
module.exports = [
// --- fit/predict ---
["aiml-model-fit-predict","What does `.fit(X, y)` do?",["Shows the model training features and known answers so it can learn its internal weights","Makes a prediction on new data","Deletes the model's learned weights","Splits data into train and test sets"],0,"fit() is the learning step: the model sees features (X) and correct answers (y) and learns its coef_/intercept_.",1,"conceptual"],
["aiml-model-fit-predict","Why is testing a model only on data it was trained (fit) on misleading?",["It measures memorisation, not generalisation to new, unseen data","It always produces 0% accuracy","fit() and predict() cannot be used on the same dataset at all","It makes the model faster"],0,"Training data was already seen during fit() — good performance there could just mean memorisation, not real learning.",1,"conceptual"],
["aiml-model-fit-predict","After `.fit()`, where does a linear model store what it learned?",["In `.coef_` (weights) and `.intercept_` (bias)","In a hidden file on disk","In the y array, overwriting it","Nowhere — it must be refit before every predict() call"],0,"scikit-learn's linear models expose their learned weights and bias as .coef_ and .intercept_ after fitting.",1,"conceptual"],
// --- train/test split ---
["aiml-train-test-split","With 200 rows and `test_size=0.25`, how many rows go to the test set?",["50","25","75","150"],0,"25% of 200 = 50 rows for test, 150 for train.",1,"code-output"],
["aiml-train-test-split","What does `random_state=42` achieve in train_test_split?",["Makes the split reproducible — the same rows land in train/test every run","Ensures exactly 42% of data goes to test","Guarantees the model will be 42% accurate","Randomizes the split differently every single run"],0,"A fixed random_state makes the split deterministic across reruns, essential for fair experiment comparison.",1,"conceptual"],
["aiml-train-test-split","When should you use `stratify=y` in train_test_split?",["For classification with imbalanced classes, to keep class proportions consistent across train and test","Only for regression problems","Never — it's deprecated","Only when test_size is exactly 0.5"],0,"stratify=y preserves each class's proportion in both splits — most important when classes are imbalanced.",2,"conceptual"],
// --- linear regression ---
["aiml-linear-regression","What kind of target does linear regression predict?",["A continuous number (like a price)","A category (like spam/not spam)","Always a probability between 0 and 1","A yes/no boolean only"],0,"Linear regression predicts continuous numeric values; classification models handle categories.",1,"conceptual"],
["aiml-linear-regression","Why should you compare a model's MSE against a simple baseline instead of judging the raw number alone?",["MSE's scale depends entirely on what's being predicted — there's no universal 'good' number","MSE is always between 0 and 1, so it's self-explanatory","A baseline is required by scikit-learn's API","MSE cannot be computed without a baseline"],0,"An MSE of 100 might be great for house prices in dollars but terrible for probabilities — context and a baseline comparison matter.",2,"conceptual"],
["aiml-linear-regression","Why is a large `.coef_` value not automatically 'more important feature' when features are on very different scales?",["Features on different scales (e.g. sqft vs bedroom count) aren't directly comparable without standardizing first","Coefficients are always meaningless","Larger coefficients always mean less important features","scikit-learn sorts coefficients by importance automatically"],0,"A coefficient's magnitude reflects both its true effect AND its feature's scale — comparing raw coefficients across differently-scaled features is misleading.",2,"conceptual"],
// --- classification ---
["aiml-classification","What does `.predict_proba()` return that `.predict()` doesn't?",["The probability for each possible class, not just the single most likely label","A completely different set of features","The model's training accuracy","Nothing — they return identical output"],0,"predict_proba() gives per-class confidence (summing to 1); predict() collapses that to one label using a threshold.",1,"conceptual"],
["aiml-classification","Why can raw accuracy be misleading on an imbalanced dataset (e.g. 95% one class)?",["A model that always predicts the majority class can score high accuracy while being useless on the minority class","Accuracy cannot be computed on imbalanced data","Imbalanced datasets always give 50% accuracy","scikit-learn refuses to run on imbalanced data"],0,"Always predicting the majority class scores ~95% accuracy there while never correctly catching the minority class — a real failure hidden by the metric.",2,"conceptual"],
["aiml-classification","Despite its name, what task is LogisticRegression actually used for?",["Classification, not regression — it outputs class probabilities","Only linear regression tasks","Image processing exclusively","Clustering unlabeled data"],0,"LogisticRegression is scikit-learn's core classification workhorse; it predicts probabilities via a logistic curve, then a threshold picks the class.",1,"conceptual"],
// --- trees & forests ---
["aiml-trees-forests","Why does an unrestricted decision tree risk becoming 'unstable' per scikit-learn's docs?",["It can grow to fit training data very closely, so small data changes can produce a completely different tree","Trees are always identical no matter the data","Instability only affects regression trees, never classifiers","Unrestricted trees train faster and are therefore less stable"],0,"An unrestricted tree can isolate individual samples, making it highly sensitive to small variations in the training data.",2,"conceptual"],
["aiml-trees-forests","How does a random forest typically reduce a single tree's overfitting?",["By training many trees on random subsets of data/features and averaging their predictions","By using only one very deep tree instead of many","By removing all randomness from training","By training on the test set directly"],0,"Averaging predictions across many trees, each trained on a random subset, smooths out individual trees' overfitting to quirks in their sample.",1,"conceptual"],
["aiml-trees-forests","Is a random forest guaranteed to outperform a single decision tree on every dataset?",["No — on small, easy datasets a well-tuned single tree can sometimes match or beat it; always check on your own data","Yes, always, with no exceptions","No, forests are always worse than single trees","Yes, but only for regression problems"],0,"Forests usually reduce overfitting on complex datasets, but on small/easy datasets a single tree can be competitive — empirical comparison beats assuming.",2,"conceptual"],
// --- choosing a model ---
["aiml-choosing-model","Why is it important to compare candidate models on the exact same train/test split?",["So performance differences reflect the models themselves, not random variation from different data splits","It's required by scikit-learn's license","Different splits always produce identical results anyway","It makes training faster"],0,"Using the same split isolates the model as the variable being compared — a fair, apples-to-apples comparison.",2,"conceptual"],
["aiml-choosing-model","Give one valid reason to choose a simpler, slightly less accurate model over a more complex, slightly more accurate one.",["Explainability, lower overfitting risk on small data, or faster predictions — accuracy isn't the only criterion","There is never a valid reason — always pick the most accurate model","Simpler models are always literally more accurate","Complex models are illegal in production systems"],0,"Real-world model choice weighs explainability, overfitting risk, latency, and maintainability alongside raw accuracy.",1,"conceptual"]
];
