// FORAGE — AI Engineer path, Module 6: LLMs & GenAI Fundamentals
// Facts verified against Hugging Face's tokenizer_summary docs, embeddings blog post, and
// the LLM course. Code-runnable pieces (tokenizer counts, embedding similarity) executed
// with a real tokenizer/sentence-embedding model before shipping.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "aiml-llm", title: "LLMs & GenAI Fundamentals",
  why: "Large Language Models power the chatbots, coding assistants, and generative tools reshaping the industry. You don't need to train one from scratch to work with them professionally — but you do need the real mental model: tokens, embeddings, the transformer's attention idea, and what prompting and RAG actually do. This module builds that model from zero.",
  topics: [
  {
    id: "aiml-tokens", title: "Tokens — how LLMs actually read text",
    concept: "An LLM never sees raw text — it sees a sequence of TOKENS, numeric IDs from a fixed vocabulary. Per Hugging Face's own tokenizer documentation, most modern LLMs use SUBWORD tokenization (commonly Byte-Pair Encoding, or BPE): common words stay as one token, but rarer or longer words get split into meaningful pieces (e.g. 'annoyingly' → 'annoying' + 'ly'). This is a deliberate middle ground — whole-word tokenization needs an enormous vocabulary and can't handle unseen words; character-level tokenization keeps sequences painfully long. Subwords balance a manageable vocabulary size with the ability to represent any word, including ones never seen during training.",
    analogy: "Think of subword tokens like a practical toolkit of word-parts rather than a full dictionary of whole words or a bin of individual letters. A whole-word dictionary needs a separate entry for 'run', 'running', 'runner', 'runs' — huge and still incomplete. Individual letters can spell anything but say almost nothing on their own ('r' carries no meaning). A toolkit of common pieces — 'run', 'ing', 'er', 's' — reuses parts efficiently and can still assemble words it's never seen whole.",
    examples: [
      {code: "from transformers import AutoTokenizer\n\ntok = AutoTokenizer.from_pretrained(\"gpt2\")\ntext = \"Tokenization is fundamental to how LLMs process text.\"\nids = tok.encode(text)\nprint(len(text.split()), \"words ->\", len(ids), \"tokens\")\nprint(tok.convert_ids_to_tokens(ids))", note: "Notice the token count usually differs from the word count — common words often become one token each, but some words split into pieces (look for a 'Ġ' prefix in GPT-2's tokenizer, which marks 'start of a new word' at the byte level). This is the exact BPE mechanism from Hugging Face's tokenizer docs, applied to real text."},
      {code: "# Rare/unusual words split into more pieces than common ones\nfor word in [\"the\", \"cat\", \"tokenization\", \"antidisestablishmentarianism\"]:\n    n = len(tok.encode(word, add_special_tokens=False))\n    print(f\"{word!r}: {n} token(s)\")", note: "Common short words ('the', 'cat') typically cost 1 token. Rarer or longer words cost more, because the tokenizer had to fall back to smaller subword pieces during training — exactly the tradeoff Hugging Face's docs describe: a compact vocabulary that can still represent any word by breaking it down."}
    ],
    mistakes: ["Assuming 1 token ≈ 1 word — it's approximate at best; punctuation, whitespace, and rare words all change the count.","Forgetting that LLM usage/pricing and context-window limits are measured in TOKENS, not words or characters — a token-count estimate matters for real API usage.","Thinking tokenization is unique to one company's models — it's a general LLM technique; the specific algorithm (BPE/Unigram/WordPiece) varies by model family."],
    handsOn: "Install `transformers`, load a tokenizer (e.g. AutoTokenizer.from_pretrained('gpt2')), and encode a few sentences of your own. Compare the word count to the token count. Then try a made-up word or a word in a language other than English and observe how many pieces it splits into.",
    doneWhen: "You can explain why LLMs use subword tokens instead of whole words or characters, and you've confirmed with real code that token count differs from word count.",
    checks: [
      {q: "Why do LLMs use subword tokenization instead of splitting text into whole words?", a: "Whole-word vocabularies get enormous and still can't handle words never seen during training; subword tokenization keeps the vocabulary compact while still being able to represent any word by breaking it into smaller known pieces."}
    ],
    keyTakeaways: ["LLMs process TOKENS (numeric IDs), not raw text.", "Subword tokenization (e.g. BPE) balances vocabulary size against handling unseen words.", "Token count ≠ word count — this matters for context limits and API costs."],
    resources: [
      {label: "Hugging Face — Tokenizer summary (BPE, Unigram, WordPiece)", url: "https://huggingface.co/docs/transformers/tokenizer_summary", kind: "docs"},
      {label: "Hugging Face — LLM Course, Chapter 6 (tokenizers)", url: "https://huggingface.co/learn/llm-course/chapter6/1", kind: "course"}
    ]
  },
  {
    id: "aiml-embeddings", title: "Embeddings — meaning as vectors",
    concept: "An embedding is a list of numbers (a vector) that represents the MEANING of a piece of text, not just its literal characters. Per Hugging Face's own explanation, texts with similar meaning end up positioned close together in this numeric space, even if they share almost no words in common — 'How do I sign up for Medicare?' and 'How can I register for Medicare?' land near each other because they mean the same thing. You measure 'how similar' two pieces of text are by measuring the distance (or cosine similarity) between their embeddings. This is the foundation of semantic search, recommendation systems, and — critically for this module — RAG.",
    analogy: "Imagine plotting every book in a library not by title, but by PLOT — a point in space where similar plots (heist stories, coming-of-age stories) cluster near each other regardless of their actual titles or authors. Finding 'books like this one' becomes a matter of looking at nearby points, not matching exact words in the title. That's what an embedding space does for meaning.",
    examples: [
      {code: "from sentence_transformers import SentenceTransformer\nfrom sklearn.metrics.pairwise import cosine_similarity\n\nmodel = SentenceTransformer(\"all-MiniLM-L6-v2\")\nsentences = [\n    \"How do I sign up for Medicare?\",\n    \"How can I register for Medicare?\",\n    \"What's the weather like today?\",\n]\nembs = model.encode(sentences)\nprint(embs.shape)   # (3, 384) -- 3 sentences, each a 384-number vector\n\nsim = cosine_similarity(embs)\nprint(sim.round(2))", note: "The similarity matrix shows sentence 1 and 2 (both about registering for Medicare) score much higher similarity with each other than either scores with sentence 3 (unrelated weather question) — even though sentences 1 and 2 share barely any exact words. This is meaning-based similarity, not keyword matching."},
      {code: "# Each sentence becomes a fixed-length vector regardless of its length\nfor s, e in zip(sentences, embs):\n    print(f\"{len(s)} chars -> vector of {len(e)} numbers\")", note: "Every sentence -- short or long -- gets compressed into the SAME size vector (384 numbers here). That fixed size is what makes embeddings easy to store, compare, and search across millions of documents efficiently."}
    ],
    mistakes: ["Confusing embeddings with tokens — tokens are how text is CHOPPED UP for the model to read; embeddings are numeric MEANING representations (often of a whole sentence or document).","Assuming embedding similarity is exact/symbolic — it's a learned, approximate measure of semantic closeness, not a guarantee of logical equivalence.","Comparing embeddings from two DIFFERENT models — their vector spaces aren't compatible; always embed with the same model you'll compare against."],
    handsOn: "Install `sentence-transformers`, load a small model like 'all-MiniLM-L6-v2', and embed 4-5 sentences of your own — include two that mean the same thing in different words, and one or two unrelated ones. Compute cosine similarity between all pairs and confirm the semantically related pair scores highest.",
    doneWhen: "You can explain what an embedding represents, why semantically similar text ends up with high cosine similarity even with different wording, and you've confirmed this with real code.",
    checks: [
      {q: "Two sentences share almost no exact words but mean the same thing. What would you expect from their embedding similarity, and why?", a: "High similarity — embeddings represent MEANING, not literal word overlap, so semantically equivalent sentences land close together in vector space even with completely different wording."}
    ],
    keyTakeaways: ["An embedding is a fixed-length numeric vector representing a text's meaning.", "Semantically similar texts have high cosine similarity, even with different wording.", "Embeddings power semantic search, recommendations, and RAG retrieval."],
    resources: [
      {label: "Hugging Face — Getting Started With Embeddings", url: "https://huggingface.co/blog/getting-started-with-embeddings", kind: "docs"},
      {label: "sentence-transformers — official docs", url: "https://www.sbert.net/", kind: "docs"}
    ]
  },
  {
    id: "aiml-transformer-intuition", title: "The transformer — attention, at a glance",
    concept: "The transformer architecture (introduced in the 2017 paper 'Attention Is All You Need') is the backbone of virtually every modern LLM. Its core idea is SELF-ATTENTION: when processing each token, the model looks at every OTHER token in the input and learns how much each one should matter to understanding this one. This lets the model resolve context that pure word-order processing would miss — e.g. in 'the trophy didn't fit in the suitcase because it was too big,' attention lets the model learn that 'it' more likely refers to 'the trophy,' by weighing relationships between all the words at once rather than reading strictly left-to-right.",
    analogy: "Imagine reading a mystery novel where, to understand who 'she' refers to on page 200, you don't just look at the immediately preceding sentence — your brain instantly weighs several earlier candidate characters and settles on the most likely one based on context. Self-attention is that same 'weigh everything relevant, not just what's nearby' process, done mathematically for every word against every other word, all at once.",
    examples: [
      {code: "# Attention scores are LEARNED weights showing how much each token matters to another\n# Simplified illustration (not real model internals, but the right shape):\nimport numpy as np\n\ntokens = [\"The\", \"trophy\", \"didn't\", \"fit\", \"because\", \"it\", \"was\", \"big\"]\n# Pretend attention weights FROM \"it\" TO every other token (rows sum to 1)\nattention_from_it = np.array([0.02, 0.55, 0.03, 0.05, 0.02, 0.02, 0.06, 0.25])\nfor tok, w in zip(tokens, attention_from_it):\n    print(f\"{tok:10s} {w:.2f}\")\nprint(\"sum:\", attention_from_it.sum())", note: "This is a simplified illustration, not real extracted weights -- but it shows the SHAPE of what attention computes: for the token 'it', the model assigns most weight to 'trophy' (0.55), correctly resolving the ambiguous pronoun by attending strongly to the right earlier token, with the weights summing to 1 (a probability distribution)."}
    ],
    warn: "This lesson gives INTUITION, not the full mathematical mechanism (queries/keys/values, multi-head attention) — that level of depth belongs in a dedicated deep-learning-architecture course. The goal here is understanding WHAT attention does conceptually, since that's what matters for using and reasoning about LLMs day to day.",
    mistakes: ["Thinking transformers read text strictly left-to-right like older RNN models — self-attention lets them weigh relationships across the WHOLE input at once.","Assuming 'attention' is a vague marketing term — it's a specific, learned mathematical mechanism with real, inspectable weights.","Expecting to need to implement attention from scratch as an AI Engineer — most real work uses pretrained transformers via libraries; understanding the concept matters far more than re-deriving the math."],
    handsOn: "Write out a sentence with an ambiguous pronoun or reference (like the trophy/suitcase example) and manually reason through which earlier word it most likely refers to, and why. Then read the first two sections of Hugging Face's LLM course chapter on transformers architecture (linked below) to see the real terminology (queries, keys, values) mapped onto this intuition.",
    doneWhen: "You can explain in plain language what self-attention does and why it helps resolve context that simple left-to-right reading would miss.",
    checks: [
      {q: "What does self-attention let a transformer do that a strictly left-to-right reading process can't do as well?", a: "It lets the model weigh relationships between EVERY pair of tokens in the input at once (not just nearby ones), so it can resolve context — like which earlier noun a pronoun refers to — using the whole sentence, not just recent words."}
    ],
    keyTakeaways: ["The transformer's core idea is self-attention: weighing every token against every other token.", "This resolves context (like pronoun references) better than strict left-to-right reading.", "Attention weights are learned, real, and inspectable — not a vague concept."],
    resources: [
      {label: "Hugging Face — LLM Course, Chapter 1: Transformer models", url: "https://huggingface.co/learn/llm-course/chapter1/1", kind: "course"},
      {label: "3Blue1Brown — Attention in transformers, visually explained (video)", url: "https://www.youtube.com/watch?v=eMlx5fFNoYc", kind: "video"}
    ]
  },
  {
    id: "aiml-prompting", title: "Prompting — the real interface to an LLM",
    concept: "For most AI Engineering work, the model itself is fixed (you call an existing pretrained model via an API) — the lever you actually control is the PROMPT: the instructions and context you send in. Effective prompting means being specific about the task, providing relevant context/examples, and structuring the request clearly (e.g. separating instructions from the content to act on). Two widely-used patterns: FEW-SHOT prompting (showing the model 1-3 examples of the input→output pattern you want before your real request) and clear ROLE/SYSTEM instructions (telling the model how to behave for the whole conversation, not per-message).",
    analogy: "Prompting a general-purpose LLM is like briefing a very capable but context-blind new hire on their first task: vague instructions ('write something good') get vague, unpredictable results; a clear brief with the goal, format, and a worked example gets a result close to what you actually wanted, the first time.",
    examples: [
      {code: "# Vague prompt (unpredictable, inconsistent format)\nvague = \"Summarize this article.\"\n\n# Specific prompt (clear task, format, and constraint)\nspecific = \"\"\"Summarize the following article in exactly 3 bullet points,\neach under 15 words, focused only on concrete facts (no opinions).\n\nArticle:\n<article text here>\"\"\"", note: "The specific version fixes the FORMAT (3 bullets), the LENGTH (under 15 words each), and the CONTENT FILTER (facts only) — three concrete constraints that make the output far more predictable and directly usable than the vague version, which leaves the model guessing your actual intent."},
      {code: "# Few-shot prompting: show the pattern before asking for a new one\nfew_shot = \"\"\"Classify the sentiment as Positive, Negative, or Neutral.\n\nText: \"This laptop is amazing, best purchase ever!\"\nSentiment: Positive\n\nText: \"The delivery was three weeks late.\"\nSentiment: Negative\n\nText: \"The package arrived on the expected date.\"\nSentiment: Neutral\n\nText: \"Customer support fixed my issue but took forever to respond.\"\nSentiment:\"\"\"", note: "Three worked examples establish the exact format the model should follow (one word: Positive/Negative/Neutral) before the real question — few-shot prompting is often far more reliable than describing the desired format in words alone, especially for consistent formatting."}
    ],
    mistakes: ["Writing a vague prompt and blaming the model for an unpredictable answer — specificity is the engineer's job, not the model's.","Never testing a prompt on edge cases (ambiguous or unusual inputs) before relying on it in a real feature.","Putting untrusted user input directly into an instruction-following prompt without separating it clearly from your actual instructions — a real security concern called prompt injection, worth being aware of even at this stage."],
    handsOn: "Take a real task you want an LLM to do (summarizing, classifying, extracting data). Write a vague version of the prompt and a specific, constrained version with a worked example (few-shot). If you have access to any LLM (a chat UI counts), run both and compare how much more consistent and usable the specific version's output is.",
    doneWhen: "You can write a specific, well-structured prompt with explicit format/length/content constraints, and explain what few-shot prompting is and why it improves consistency.",
    checks: [
      {q: "Why does a vague prompt like 'summarize this' often produce inconsistent results across runs?", a: "It leaves the format, length, and focus entirely up to the model's guess — without explicit constraints, the model has many equally 'valid' ways to satisfy the request, so output varies. Specific constraints narrow that down."}
    ],
    keyTakeaways: ["The prompt is the primary lever you control when using a pretrained LLM via API.", "Specific instructions (format, length, focus) produce far more consistent output than vague ones.", "Few-shot prompting shows the model worked examples of the exact pattern you want."],
    resources: [
      {label: "Anthropic — Prompt engineering overview", url: "https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview", kind: "docs"},
      {label: "OpenAI — Prompt engineering guide", url: "https://platform.openai.com/docs/guides/prompt-engineering", kind: "docs"}
    ]
  },
  {
    id: "aiml-rag-basics", title: "RAG — grounding an LLM in your own data",
    concept: "An LLM only knows what it learned during training — it has no built-in knowledge of your company's documents, yesterday's news, or your specific codebase. RAG (Retrieval-Augmented Generation) fixes this WITHOUT retraining the model: you embed your documents (Module 6.2's embeddings) into a searchable vector store, then at query time you EMBED the user's question, RETRIEVE the most similar document chunks, and INJECT them into the prompt as context before asking the LLM to answer. The model then answers grounded in the retrieved text instead of only its training-time knowledge — the same trick this app's own 'Forage Tutor' uses to stay grounded in a specific lesson.",
    analogy: "Think of RAG as giving an extremely knowledgeable but memory-limited expert a stack of the exact right reference pages right before you ask your question, instead of expecting them to recall everything from a textbook they read once, long ago. Retrieval finds the right pages; the LLM still does the reasoning and writing, but grounded in what's actually in front of it.",
    examples: [
      {code: "from sentence_transformers import SentenceTransformer\nfrom sklearn.metrics.pairwise import cosine_similarity\nimport numpy as np\n\nmodel = SentenceTransformer(\"all-MiniLM-L6-v2\")\n\n# Step 1: embed a small \"knowledge base\" of document chunks\ndocs = [\n    \"Forage's free tier is called Common Core and covers six foundational modules.\",\n    \"Forage Interview gives Pro users unlimited mock interview sessions.\",\n    \"The capital of France is Paris.\",\n]\ndoc_embs = model.encode(docs)\n\n# Step 2: embed the user's question\nquestion = \"What does the free plan include?\"\nq_emb = model.encode([question])\n\n# Step 3: retrieve the most similar chunk\nsims = cosine_similarity(q_emb, doc_embs)[0]\nbest_idx = np.argmax(sims)\nprint(\"best match:\", docs[best_idx], f\"(similarity {sims[best_idx]:.2f})\")", note: "The question about 'the free plan' correctly retrieves the Common Core document, not the unrelated Paris fact or the Pro-tier fact, purely from embedding similarity -- no keyword overlap needed ('free plan' vs 'free tier'). This retrieved text is what gets injected into the LLM's prompt as grounding context."},
      {code: "# Step 4 (conceptual): build the grounded prompt to send to the LLM\nretrieved_context = docs[best_idx]\ngrounded_prompt = f\"\"\"Answer the question using ONLY the context below.\nIf the context doesn't contain the answer, say so.\n\nContext: {retrieved_context}\n\nQuestion: {question}\"\"\"\nprint(grounded_prompt)", note: "This is the actual prompt sent to the LLM -- notice the instruction to answer ONLY from the given context, and to admit when it can't. That explicit constraint is what keeps a RAG system honest instead of letting the model fall back on possibly-wrong training-time knowledge."}
    ],
    warn: "RAG reduces but does NOT eliminate incorrect answers (hallucination) — the retrieval step can pull irrelevant chunks, and the LLM can still misread even correct context. Always instruct the model to admit when the retrieved context doesn't answer the question, and treat RAG outputs as needing verification for anything high-stakes.",
    mistakes: ["Confusing RAG with fine-tuning — RAG injects fresh context at query time without touching the model's weights at all; fine-tuning actually retrains the model, a much heavier process.","Retrieving too many or too irrelevant chunks — stuffing the prompt with noise can hurt answer quality more than help it.","Forgetting to instruct the model to say 'I don't know' when the retrieved context doesn't actually answer the question — otherwise it may guess from training data instead of admitting the gap."],
    handsOn: "Build the mini example above with your own 3-5 'document' sentences on a topic you know well, plus one unrelated one as a distractor. Ask 2-3 different questions and confirm retrieval correctly picks the relevant document each time, including for questions that don't share exact keywords with the document.",
    doneWhen: "You can explain what RAG does and why, distinguish it clearly from fine-tuning, and have built a working toy retrieval step with real embeddings.",
    checks: [
      {q: "How does RAG let an LLM answer questions about documents it was never trained on?", a: "It doesn't retrain the model at all — it embeds your documents, retrieves the most relevant chunks for a given question at query time using embedding similarity, and injects that retrieved text into the prompt as context for the LLM to answer from."},
      {q: "What's the key difference between RAG and fine-tuning?", a: "RAG injects fresh context into the prompt at query time without touching the model's weights; fine-tuning actually retrains/adjusts the model's weights on new data — a much heavier, more permanent process."}
    ],
    keyTakeaways: ["RAG grounds an LLM in your own data by retrieving relevant chunks and injecting them into the prompt.", "It works via embeddings + similarity search, with no retraining required.", "RAG reduces but doesn't eliminate hallucination — always instruct the model to admit gaps."],
    resources: [
      {label: "Hugging Face — RAG overview (Transformers docs)", url: "https://huggingface.co/docs/transformers/model_doc/rag", kind: "docs"},
      {label: "Pinecone — Retrieval-Augmented Generation guide", url: "https://www.pinecone.io/learn/retrieval-augmented-generation/", kind: "reference"}
    ]
  }
  ]
};
