// FORAGE — AI Engineer path, Module 3: Classical ML with scikit-learn
// Schema matches commoncore.js. Facts verified against scikit-learn.org docs
// (fit/predict API, train_test_split behavior, LinearRegression/LogisticRegression,
// decision tree overfitting — see resources for the exact pages). All code snippets
// run against scikit-learn 1.9.0 and checked before shipping.

module.exports = {
  id: "aiml-sklearn", title: "Classical ML with scikit-learn",
  why: "This is where everything from the last two modules pays off. scikit-learn packages 'features · weights, minimize the loss, follow the gradient' into a tiny, consistent API — fit() then predict() — so you can build real models in a handful of lines. This module builds the muscle memory you'll reuse in every project after this.",
  topics: [
  {
    id: "aiml-model-fit-predict", title: "What a model is — fit() and predict()",
    concept: "Every scikit-learn model follows the exact same two-step pattern, called the Estimator API: `.fit(X, y)` shows the model your training data (features X, known answers y) so it can learn its internal numbers (like the weights from Module 2); `.predict(X_new)` then uses those learned numbers to guess answers for data it hasn't seen. Once you know fit/predict, you already know the shape of using ANY scikit-learn model — linear regression, decision trees, random forests all share this identical interface.",
    analogy: "Think of `.fit()` as studying for an exam using past papers with answer keys (X = questions, y = answers), and `.predict()` as sitting the real exam — new questions, no answer key, using only what you learned while studying. A model that's only ever seen `.fit()` data and never been tested with `.predict()` on NEW data is like a student who's never taken a practice test: you don't actually know if the studying worked.",
    examples: [
      {code: "from sklearn import linear_model\n\n# X: 3 examples, 2 features each. y: the known correct answer for each.\nX = [[0, 0], [1, 1], [2, 2]]\ny = [0, 1, 2]\n\nreg = linear_model.LinearRegression()\nreg.fit(X, y)\n\nprint(reg.coef_)        # [0.5 0.5]\nprint(reg.intercept_)   # ~0.0 (e.g. 1.11e-16 -- tiny floating-point noise, not a real number)", note: "This matches scikit-learn's own documented example. After `.fit()`, the model stores what it learned in `.coef_` (the weights from Module 2) and `.intercept_` (the baseline/bias). The intercept prints as a tiny number like 1.11e-16 instead of a clean 0.0 — that's ordinary floating-point rounding noise from the underlying maths, not a sign anything is wrong; treat any number smaller than about 1e-10 as effectively zero."},
      {code: "predictions = reg.predict([[3, 3], [4, 4]])\nprint(predictions)   # [3. 4.]", note: "`.predict()` takes NEW feature rows (never seen during `.fit()`) and applies the learned coef_/intercept_ — literally `features · weights + bias` from Module 2's math, computed automatically."}
    ],
    mistakes: ["Calling `.predict()` before `.fit()` — the model has no learned coef_/intercept_ yet and will raise a 'not fitted' error.","Passing DIFFERENT features to `.predict()` than the model was `.fit()` on (e.g. 2 features during fit, 3 during predict) — shapes must match.","Evaluating a model only on the SAME data it was `.fit()` on — that tells you how well it memorised, not how well it generalises to new data (the next lesson fixes this)."],
    handsOn: "Using the example above, add a third feature column to X and y (make up 2 more rows) and re-fit. Print the new `.coef_` and `.intercept_`, then predict on 2 brand-new rows you didn't train on. Confirm the prediction shape matches the number of rows you passed in.",
    doneWhen: "You can explain fit/predict in your own words using the exam analogy, and you've fit a model on your own small dataset and predicted on new rows.",
    checks: [
      {q: "What does `.fit(X, y)` do, in one sentence?", a: "It shows the model training features (X) and their known correct answers (y) so it can learn its internal weights/coefficients."},
      {q: "Why is testing a model only on the data it was trained on misleading?", a: "It only tells you how well the model memorised the training data, not how well it will perform on new, unseen data — which is what actually matters in practice."}
    ],
    keyTakeaways: ["Every scikit-learn model shares the same fit()/predict() interface — the Estimator API.","`.fit(X, y)` learns; `.predict(X_new)` applies what was learned to new data.","After fitting, linear models expose `.coef_` and `.intercept_` — the weights and bias from Module 2's maths."],
    resources: [
      {label: "scikit-learn — Linear Models (fit/predict, coef_, intercept_)", url: "https://scikit-learn.org/stable/modules/linear_model.html", kind: "docs"},
      {label: "scikit-learn — Getting Started guide", url: "https://scikit-learn.org/stable/getting_started.html", kind: "docs"}
    ]
  },
  {
    id: "aiml-train-test-split", title: "Train/test split — the honesty check",
    concept: "If you evaluate a model on the same data it trained on, you're grading your own homework with the answer key already memorised — the score will look better than reality. `train_test_split` fixes this by holding back a chunk of your data (commonly 20-30%) that the model NEVER sees during `.fit()`, so you can honestly check performance on data it genuinely hasn't encountered. This one function is what separates 'looks good in the notebook' from 'actually works.'",
    analogy: "Imagine a driving instructor who only ever tests students on the exact same street they practised on. Everyone passes — but that tells you nothing about whether they can drive on a street they've never seen. The test set is the unfamiliar street: the only fair way to know if the skill (or model) actually generalises.",
    examples: [
      {code: "from sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.arange(20).reshape((10, 2))   # 10 examples, 2 features\ny = np.arange(10)                     # 10 labels\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.3, random_state=42\n)\nprint(X_train.shape, X_test.shape)   # (7, 2) (3, 2)", note: "test_size=0.3 means 30% held back for testing — with 10 rows that's 3 for test, 7 for train, matching scikit-learn's own documented behaviour. `random_state=42` makes the split reproducible: the SAME 3 rows go to test every time you rerun this exact code, which matters when you're comparing experiments."},
      {code: "from sklearn.model_selection import train_test_split\nfrom sklearn import datasets\n\niris = datasets.load_iris(as_frame=True)\nX, y = iris[\"data\"], iris[\"target\"]\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.33, random_state=42, stratify=y\n)\nprint(y_train.value_counts(normalize=True).round(2))\nprint(y_test.value_counts(normalize=True).round(2))", note: "`stratify=y` keeps the CLASS PROPORTIONS the same in both train and test sets — per scikit-learn's docs, this matters most for imbalanced classification (e.g. 95% not-fraud, 5% fraud), where a plain random split could accidentally put almost all the rare class into one side."}
    ],
    mistakes: ["Forgetting `random_state`, so every rerun gives a DIFFERENT split — making it impossible to fairly compare 'did my change actually help?' between experiments.","Evaluating repeatedly on the test set while tweaking the model — each peek leaks a little information, and eventually you're indirectly fitting to the 'unseen' data too (a 3rd 'validation' split is the fix, covered in the next module).","Not using `stratify=y` on an imbalanced classification problem, ending up with a test set that barely contains any examples of the rare class."],
    handsOn: "Split any small dataset you've built in this module (or `iris`) into train/test with `test_size=0.25` and `random_state=42`. Print the shapes of all four outputs and confirm they add up to the original dataset size. Then re-run with a DIFFERENT `random_state` and confirm you get a different split.",
    doneWhen: "You can explain why testing on training data is misleading, and you've produced a reproducible train/test split and verified the shapes add up correctly.",
    checks: [
      {q: "With 200 rows and `test_size=0.25`, how many rows end up in the test set?", a: "50 rows (25% of 200) — the remaining 150 go to training."},
      {q: "What does setting `random_state=42` (or any fixed number) achieve?", a: "It makes the train/test split reproducible — the exact same rows land in train vs test every time the code runs, which is essential for fairly comparing experiments."}
    ],
    keyTakeaways: ["Never evaluate a model only on the data it trained on — that measures memorisation, not generalisation.","train_test_split holds back unseen data to honestly check performance.","random_state makes splits reproducible; stratify keeps class balance for classification."],
    resources: [
      {label: "scikit-learn — train_test_split documentation", url: "https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html", kind: "docs"},
      {label: "scikit-learn — Cross-validation guide", url: "https://scikit-learn.org/stable/modules/cross_validation.html", kind: "docs"}
    ]
  },
  {
    id: "aiml-linear-regression", title: "Linear regression — predicting a number",
    concept: "Linear regression predicts a CONTINUOUS number (a price, a temperature, a score) as a weighted sum of features plus a baseline: exactly the `features · weights + bias` from Module 2, now fit automatically by minimizing squared error (Module 2's MSE) across all training rows. It's usually the first model to try for a numeric-prediction problem — simple, fast, and its learned `.coef_` values are directly interpretable (\"each extra bedroom adds $30k to the predicted price\").",
    analogy: "Linear regression is like finding the single straight line through a scatter of points that stays as close as possible to all of them on average — not passing through every point exactly, but minimizing the overall squared distance. Add more features and it becomes a flat plane (or higher-dimensional equivalent) through the data instead of a line, but the idea is identical.",
    examples: [
      {code: "from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\n\n# Toy dataset: [size_sqft, bedrooms] -> price_in_thousands\nX = np.array([[850,2],[900,2],[1200,3],[1500,3],[1800,4],[2000,4],[2200,5]])\ny = np.array([150, 160, 210, 250, 300, 320, 360])\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint(model.coef_)        # weight per feature\nprint(model.intercept_)   # baseline price", note: "coef_[0] is roughly 'price change per extra sqft', coef_[1] is roughly 'price change per extra bedroom' — this direct interpretability is exactly why linear regression stays useful even in a world of deep learning: you can explain WHY it predicted what it predicted."},
      {code: "from sklearn.metrics import mean_squared_error\n\npredictions = model.predict(X_test)\nprint(predictions)\nprint(mean_squared_error(y_test, predictions))", note: "This is Module 2's MSE lesson, applied for real: scikit-learn's `mean_squared_error` computes exactly `mean((predictions - true_values) ** 2)` — the same formula, now measuring performance on the held-out TEST set from the last lesson, not training data."}
    ],
    warn: "A small MSE number alone doesn't tell you if a model is 'good' — it depends entirely on the scale of what you're predicting (an MSE of 100 is great for house prices in dollars, terrible for probabilities between 0 and 1). Always compare MSE against a simple baseline (like 'always predict the average') before calling a result good.",
    mistakes: ["Judging a model as 'good' purely from training performance instead of the held-out test set from the last lesson.","Assuming a large `.coef_` value automatically means 'more important feature' — features on very different scales (e.g. square feet vs number of bedrooms) aren't directly comparable without first standardizing them.","Using linear regression for a fundamentally non-linear relationship (e.g. one that curves sharply) and being confused why predictions are poor — the model can only draw a straight line/plane through the data."],
    handsOn: "Using the housing example (or your own made-up numeric-prediction dataset), fit a LinearRegression model on a train split, predict on the test split, and compute the MSE. Then compare it to a trivial baseline: predict the TRAINING MEAN for every test row and compute that MSE too. Confirm your model beats the baseline.",
    doneWhen: "You've fit and evaluated a linear regression model on a proper train/test split, and confirmed it outperforms a naive 'always predict the average' baseline.",
    checks: [
      {q: "What kind of target does linear regression predict — a category or a continuous number?", a: "A continuous number (like a price or temperature) — for predicting categories, you'd reach for classification models instead (next lesson)."},
      {q: "Why should you compare your model's MSE against a simple baseline instead of judging the raw number alone?", a: "Because MSE's scale depends entirely on what you're predicting — there's no universal 'good' number; a baseline (like predicting the average) gives you something meaningful to compare against."}
    ],
    keyTakeaways: ["Linear regression predicts continuous numbers as a weighted sum of features plus a baseline.","Its coef_ values are directly interpretable — a real advantage over black-box models.","Always evaluate on the test split, and compare against a simple baseline, not in isolation."],
    resources: [
      {label: "scikit-learn — Linear Regression (Ordinary Least Squares)", url: "https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares", kind: "docs"},
      {label: "scikit-learn — Regression metrics (MSE and friends)", url: "https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics", kind: "docs"}
    ]
  },
  {
    id: "aiml-classification", title: "Classification — predicting a category",
    concept: "Classification predicts which CATEGORY something belongs to (spam/not-spam, cat/dog/bird), rather than a number. Despite the name, LogisticRegression is scikit-learn's classification workhorse: it outputs a PROBABILITY between 0 and 1 (via `.predict_proba()`) using the same features·weights idea as linear regression, then squeezes that number through a logistic curve so it always lands between 0 and 1. A threshold (0.5 by default, exactly as covered in Module 2's probability lesson) turns that probability into a final class label.",
    analogy: "Linear regression draws a straight line through numeric data; logistic regression draws a boundary CURVE that separates categories, and reports how confidently a point sits on one side or the other as a probability — the closer to the boundary, the closer that probability sits to 0.5 (genuine uncertainty), exactly matching the spam-filter intuition from Module 2.",
    examples: [
      {code: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn import datasets\n\niris = datasets.load_iris()\nX, y = iris.data, iris.target   # 3 flower species to classify\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\n\nclf = LogisticRegression(max_iter=200)\nclf.fit(X_train, y_train)\n\nprint(clf.predict(X_test[:5]))          # predicted class labels\nprint(clf.predict_proba(X_test[:5]).round(2))  # probability per class", note: "`max_iter=200` is a real, common necessity — LogisticRegression trains iteratively (Module 2's gradient descent!) and the default iteration limit sometimes isn't enough to converge, which scikit-learn warns about rather than failing silently. `.predict_proba()` returns one probability PER CLASS per row (they sum to 1, exactly like Module 2's probability lesson)."},
      {code: "from sklearn.metrics import accuracy_score\n\npredictions = clf.predict(X_test)\nprint(accuracy_score(y_test, predictions))", note: "Accuracy = fraction of predictions that exactly matched the true label. Simple and intuitive, but remember Module 2's warning: accuracy alone can be misleading on imbalanced data (a model that always predicts the majority class can still score high accuracy) — the next module covers better tools for that."}
    ],
    mistakes: ["Confusing `.predict()` (a class label) with `.predict_proba()` (probabilities per class) — reaching for the wrong one depending on whether you need a decision or a confidence level.","Trusting raw accuracy on an imbalanced dataset (e.g. 95% one class) — a model that predicts the majority class every time scores 95% accuracy while being useless.","Not increasing `max_iter` when scikit-learn warns about convergence — the model may have stopped training before it actually found good weights."],
    handsOn: "Using the iris example (or your own categorical-target dataset), fit a LogisticRegression classifier, get both `.predict()` and `.predict_proba()` output for the same 5 test rows, and write one sentence connecting a LOW max-probability row to Module 2's 'the model is genuinely unsure' idea.",
    doneWhen: "You can explain the difference between predict() and predict_proba(), and you've identified at least one test row where the model's top probability is notably less confident than the others.",
    checks: [
      {q: "What does `.predict_proba()` return that `.predict()` doesn't?", a: "The probability for each possible class (summing to 1 per row), rather than just the single most likely class label."},
      {q: "Why can raw accuracy be misleading on an imbalanced dataset?", a: "A model that always predicts the majority class can score high accuracy while never correctly identifying the minority class — accuracy alone hides this failure."}
    ],
    keyTakeaways: ["Classification predicts categories; LogisticRegression outputs probabilities via a logistic curve, then a threshold picks the class.","predict() gives a label; predict_proba() gives per-class confidence.","Accuracy alone can mislead on imbalanced data — a recurring theme the next module addresses properly."],
    resources: [
      {label: "scikit-learn — Logistic regression", url: "https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression", kind: "docs"},
      {label: "scikit-learn — accuracy_score and classification metrics", url: "https://scikit-learn.org/stable/modules/model_evaluation.html#accuracy-score", kind: "docs"}
    ]
  },
  {
    id: "aiml-trees-forests", title: "Decision trees & random forests",
    concept: "A decision tree predicts by asking a sequence of yes/no questions about your features (\"is size > 1000 sqft?\", then \"is bedrooms > 3?\") until it reaches a final answer — genuinely readable, like a flowchart a human could follow. Left alone, trees grow until they perfectly memorise the training data (one leaf per example), which per scikit-learn's own documentation makes them unstable: a small change in the data can produce a completely different tree. A random forest fixes this by training MANY trees, each on a randomly-sampled slice of the data and features, then averaging their predictions — trading away a single tree's readability for far more stable, usually more accurate results.",
    analogy: "A single decision tree is one very opinionated expert who's memorised every past case in detail — confident, but easily thrown off by one unusual example. A random forest is a committee of many such experts, each having studied a different random subset of past cases; asking all of them and going with the majority vote smooths out any individual expert's blind spots.",
    examples: [
      {code: "from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn import datasets\nfrom sklearn.metrics import accuracy_score\n\n# 8x8 pixel images of handwritten digits 0-9 -- more features and\n# more room for a tree to overfit than a small dataset like iris.\ndigits = datasets.load_digits()\nX, y = digits.data, digits.target\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\n\n# An unrestricted tree -- watch it overfit\ndeep_tree = DecisionTreeClassifier(random_state=42)\ndeep_tree.fit(X_train, y_train)\nprint(\"train:\", accuracy_score(y_train, deep_tree.predict(X_train)))\nprint(\"test:\", accuracy_score(y_test, deep_tree.predict(X_test)))   # train=1.00, test~0.85", note: "Watch the gap between train and test accuracy. Per scikit-learn's documentation, an unrestricted tree grows until samples are isolated — near-perfect TRAINING accuracy is a red flag for overfitting, not a sign of success, exactly like Module 2's loss-minimization warning about memorisation. Here the tree memorises training data perfectly (100%) but only reaches ~85% on unseen test digits — a real, sizeable gap."},
      {code: "from sklearn.ensemble import RandomForestClassifier\n\nforest = RandomForestClassifier(n_estimators=100, random_state=42)\nforest.fit(X_train, y_train)\nprint(\"train:\", accuracy_score(y_train, forest.predict(X_train)))\nprint(\"test:\", accuracy_score(y_test, forest.predict(X_test)))   # train=1.00, test~0.97", note: "`n_estimators=100` trains 100 trees, each on a randomly-sampled subset of rows and features (per scikit-learn's docs: 'features and samples are randomly sampled with replacement'), then averages their votes. On this dataset the forest closes most of the gap — test accuracy jumps from ~85% to ~97% while training accuracy stays at 100%, exactly the 'more stable, less overfit' effect the concept describes. (This isn't universal: on very small, easy datasets like iris, a single tree can sometimes match or beat a forest — always check on YOUR actual data rather than assuming.)"}
    ],
    mistakes: ["Leaving a DecisionTreeClassifier completely unrestricted (no `max_depth`, `min_samples_leaf`) and being surprised it overfits — scikit-learn's own docs explicitly recommend setting these to control tree size.","Assuming a random forest is ALWAYS strictly better on every dataset — it usually reduces overfitting on datasets with enough features/complexity to overfit on, but on small, easy datasets (like iris) a single reasonably-sized tree can sometimes match it; the real fix is comparing both on your own data, not assuming.","Comparing a tree's train accuracy to a forest's TEST accuracy (or vice versa) and drawing conclusions — always compare like-for-like (test vs test)."],
    handsOn: "Using the digits (or your own) dataset, fit both a DecisionTreeClassifier and a RandomForestClassifier on the same train split. Print train AND test accuracy for both. Identify which one shows a bigger gap between train and test accuracy, and write one sentence explaining what that gap tells you.",
    doneWhen: "You've compared a single tree against a random forest on train vs test accuracy, and can explain in your own words why the forest's train/test gap is usually smaller.",
    checks: [
      {q: "Why does per scikit-learn's docs an unrestricted decision tree risk becoming 'unstable'?", a: "Because it's grown to fit the training data very closely (potentially isolating single samples), so small changes in the data can produce a completely different tree structure."},
      {q: "How does a random forest reduce a single tree's instability?", a: "By training many trees, each on a randomly-sampled subset of data and features, then averaging their predictions — smoothing out any individual tree's overfitting to quirks in its particular sample."}
    ],
    keyTakeaways: ["Decision trees split on yes/no feature questions — readable, but prone to overfitting if unrestricted.","A big train/test accuracy gap is the signature of overfitting.","Random forests train many trees on random data/feature subsets and average — more stable, less readable."],
    resources: [
      {label: "scikit-learn — Decision Trees", url: "https://scikit-learn.org/stable/modules/tree.html", kind: "docs"},
      {label: "scikit-learn — Random Forests (ensemble methods)", url: "https://scikit-learn.org/stable/modules/ensemble.html#random-forests", kind: "docs"}
    ]
  },
  {
    id: "aiml-choosing-model", title: "Choosing the right model",
    concept: "There's no single 'best' model — the right choice depends on your target (continuous number → regression family; category → classification family), how much you need to EXPLAIN predictions (linear models and single trees are readable; forests and neural networks are not), how much data you have (simple models often win on small data; complex ones need more to avoid overfitting), and how fast predictions need to be. A practical rule most ML engineers actually follow: start with the simplest reasonable model as a baseline, then add complexity only if it earns its keep on the TEST set.",
    analogy: "Choosing a model is like choosing a vehicle: a bicycle (linear regression) is simple, cheap, and easy to maintain — perfect for a short, simple trip. A truck (random forest) can handle far more complex cargo but costs more to run and is harder to explain to a mechanic who's never seen one. You don't default to the truck for every trip — you match the vehicle to the actual job.",
    examples: [
      {code: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score\nfrom sklearn import datasets\n\niris = datasets.load_iris()\nX, y = iris.data, iris.target\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\n\nmodels = {\n    \"Logistic Regression\": LogisticRegression(max_iter=200),\n    \"Decision Tree\": DecisionTreeClassifier(max_depth=3, random_state=42),\n    \"Random Forest\": RandomForestClassifier(n_estimators=100, random_state=42),\n}\n\nfor name, model in models.items():\n    model.fit(X_train, y_train)\n    acc = accuracy_score(y_test, model.predict(X_test))\n    print(f\"{name}: {acc:.3f}\")", note: "This loop is the practical heart of model selection: fit several reasonable candidates on the SAME train/test split, compare TEST scores fairly, and let the data — not a gut feeling — pick the winner. Notice all three models share the identical fit/predict interface from the first lesson, which is exactly why this comparison is so easy to write."}
    ],
    mistakes: ["Reaching for the most complex model (deep learning, huge forests) by default 'because it sounds more advanced' — on small or simple datasets, this often UNDERPERFORMS a simple baseline while being far harder to debug.","Comparing models using DIFFERENT train/test splits — always compare on the exact same split so differences reflect the model, not the data split.","Picking a model based on training accuracy instead of test accuracy — repeating Module 2 and this module's recurring warning, because it's the single most common beginner mistake in applied ML."],
    handsOn: "Using the model-comparison loop above (or your own dataset), add a fourth model of your choice from scikit-learn's documentation, run the same comparison, and write 2-3 sentences: which model won on TEST accuracy, and would you trust it in a context where you need to explain individual predictions to a human?",
    doneWhen: "You've fairly compared at least 3 models on the identical train/test split and can justify your choice using both test performance AND explainability, not test performance alone.",
    checks: [
      {q: "Why is it important to compare models on the SAME train/test split?", a: "So any performance difference reflects the models themselves, not random variation from getting different train/test data — otherwise the comparison isn't fair."},
      {q: "Give one practical reason you might choose a simpler, slightly less accurate model over a more complex, slightly more accurate one.", a: "Explainability (needing to justify individual predictions to a human), less overfitting risk on small data, faster predictions, or easier debugging — accuracy isn't the only criterion that matters."}
    ],
    keyTakeaways: ["No single 'best' model — match model choice to target type, data size, and explainability needs.","Start simple as a baseline; add complexity only if it earns its keep on the TEST set.","Always compare candidate models on the identical train/test split for a fair comparison."],
    resources: [
      {label: "scikit-learn — Choosing the right estimator (flowchart)", url: "https://scikit-learn.org/stable/machine_learning_map.html", kind: "docs"},
      {label: "Google Machine Learning Crash Course — model families overview", url: "https://developers.google.com/machine-learning/crash-course", kind: "course"}
    ]
  }
  ]
};
