// FORAGE — AI Engineer path, Module 4: Model Evaluation
// Schema matches commoncore.js. Facts + formulas verified against scikit-learn's
// model_evaluation docs (precision/recall/F1/confusion-matrix/ROC-AUC) and
// cross_validation docs. Every code snippet run against scikit-learn 1.9.0 and
// its output checked before shipping. Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "aiml-eval", title: "Model Evaluation",
  why: "Module 3 kept warning that accuracy can lie. This module gives you the real toolkit — precision, recall, F1, ROC-AUC, cross-validation — so you can tell an actually-good model from one that just looks good, which is exactly what separates a usable model from a dangerous one in production.",
  topics: [
  {
    id: "aiml-confusion-matrix", title: "The confusion matrix — the source of every metric",
    concept: "A confusion matrix is a small table that breaks a classifier's predictions into four buckets: True Positives (predicted positive, actually positive), True Negatives (predicted negative, actually negative), False Positives (predicted positive, actually negative — a false alarm), and False Negatives (predicted negative, actually positive — a miss). Almost every classification metric — accuracy, precision, recall, F1 — is just a different ratio of these four numbers, so understanding the matrix means understanding all of them at once.",
    analogy: "Think of a smoke detector. A True Positive is it correctly beeping during a real fire; a True Negative is silence when there's no fire. A False Positive is it beeping at your toast (annoying but safe); a False Negative is it staying silent during a real fire (dangerous). The whole point of evaluation is deciding which of those two mistakes you can least afford — and the confusion matrix lays them out side by side.",
    examples: [
      {code: "from sklearn.metrics import confusion_matrix\n\ny_true = [0, 0, 0, 1, 1, 1, 1, 1]   # 0 = not spam, 1 = spam\ny_pred = [0, 1, 0, 1, 0, 1, 0, 1]\n\ntn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()\nprint(f\"TN={tn}  FP={fp}  FN={fn}  TP={tp}\")   # TN=2 FP=1 FN=2 TP=3", note: "scikit-learn's binary confusion matrix, when flattened with `.ravel()`, always comes out in the exact order TN, FP, FN, TP — memorise that order, it's how you pull the four numbers out. Here 1 false alarm (FP) and 2 misses (FN)."},
      {code: "from sklearn.metrics import confusion_matrix\nprint(confusion_matrix(y_true, y_pred))\n# [[2 1]\n#  [2 3]]\n# rows = ACTUAL class (0 then 1); columns = PREDICTED class (0 then 1)", note: "The full matrix: rows are the true class, columns are what the model predicted. The diagonal (top-left, bottom-right) is where it got things right; everything off the diagonal is a mistake. Reading it as rows=actual, cols=predicted is scikit-learn's documented convention."}
    ],
    mistakes: ["Mixing up False Positive and False Negative — FP is a false ALARM (cried wolf), FN is a MISS (missed the real thing); which one is worse depends entirely on the problem.","Forgetting scikit-learn's `.ravel()` order is TN, FP, FN, TP — getting it wrong silently swaps your metrics.","Reading the matrix as columns=actual — scikit-learn's convention is rows=actual, columns=predicted."],
    handsOn: "Take any classifier you built in Module 3 (or the iris/breast-cancer datasets), get its predictions on a test set, and print the confusion matrix. Point to which cell is False Positives and which is False Negatives, and write one sentence about which mistake would matter more for that specific problem.",
    doneWhen: "You can label all four cells of a confusion matrix (TP/TN/FP/FN) from memory and explain, for a given problem, which type of error is more costly.",
    checks: [
      {q: "In spam detection, which is worse: a False Positive or a False Negative — and why?", a: "It depends on the cost you assign. A False Positive sends a real email to spam (you might miss something important); a False Negative lets spam into the inbox (annoying but usually harmless). Most people weight the FP as worse for email — the point is the matrix forces you to decide."},
      {q: "scikit-learn's `confusion_matrix(...).ravel()` returns four numbers — in what order?", a: "TN, FP, FN, TP — true negatives, false positives, false negatives, true positives."}
    ],
    keyTakeaways: ["A confusion matrix splits predictions into TP, TN, FP, FN.","Almost every classification metric is a ratio of these four numbers.","FP = false alarm, FN = miss — deciding which is worse is the core of evaluation."],
    resources: [
      {label: "scikit-learn — Confusion matrix", url: "https://scikit-learn.org/stable/modules/model_evaluation.html#confusion-matrix", kind: "docs"},
      {label: "Google ML Crash Course — Classification: True/False Positives & Negatives", url: "https://developers.google.com/machine-learning/crash-course/classification/true-false-positive-negative", kind: "course"},
      {label: "StatQuest — Confusion Matrix clearly explained (video)", url: "https://www.youtube.com/watch?v=Kdsp6soqA7o", kind: "video"}
    ]
  },
  {
    id: "aiml-precision-recall", title: "Precision & recall — the tradeoff accuracy hides",
    concept: "Precision answers \"of everything the model flagged as positive, how much really was?\" — it's TP / (TP + FP), and it punishes false alarms. Recall answers \"of all the real positives out there, how many did the model catch?\" — it's TP / (TP + FN), and it punishes misses. They pull in opposite directions: you can trivially get 100% recall by flagging everything (but precision collapses), or high precision by only flagging the surest cases (but recall collapses). Accuracy hides this tradeoff; precision and recall expose it.",
    analogy: "Imagine fishing with a net. Precision is \"of the things in my net, what fraction are actually fish (not boots and seaweed)?\" Recall is \"of all the fish in the lake, what fraction did I catch?\" A tiny fine net catches only obvious fish (high precision, low recall); a giant net scoops everything including junk (high recall, low precision). No single net wins both — you tune for the job.",
    examples: [
      {code: "from sklearn.metrics import precision_score, recall_score\n\ny_true = [0, 0, 0, 1, 1, 1, 1, 1]\ny_pred = [0, 1, 0, 1, 0, 1, 0, 1]\n\nprint(\"precision:\", precision_score(y_true, y_pred))   # 0.75\nprint(\"recall:   \", recall_score(y_true, y_pred))      # 0.6", note: "From the confusion matrix (TP=3, FP=1, FN=2): precision = 3/(3+1) = 0.75 (75% of flagged items were right), recall = 3/(3+2) = 0.6 (caught 60% of the real positives). Two different numbers describing two different failures — exactly what a single accuracy score would blur together."},
      {code: "# The extreme: predict EVERYTHING positive -> perfect recall, terrible precision\ny_true = [0, 0, 0, 1, 1]\ny_all_pos = [1, 1, 1, 1, 1]\nprint(\"recall:   \", recall_score(y_true, y_all_pos))     # 1.0  -- caught every positive\nprint(\"precision:\", precision_score(y_true, y_all_pos))  # 0.4  -- but 60% were false alarms", note: "This is why recall alone (or precision alone) is gameable. Flagging everything guarantees you miss nothing (recall 1.0) but floods you with false alarms (precision 0.4). The two must be read TOGETHER — which is what F1 (next lesson) does."}
    ],
    mistakes: ["Optimising recall alone (\"catch everything!\") without noticing precision has cratered into uselessness — or vice versa.","Swapping the definitions: precision is about the model's POSITIVE predictions being trustworthy; recall is about not MISSING real positives.","Assuming there's one universally-right balance — a cancer screen wants high recall (don't miss cases); a spam filter often wants high precision (don't trash real mail)."],
    handsOn: "Using a classifier and test set, compute both precision and recall. Then lower the decision threshold (predict positive at a lower probability, e.g. via `predict_proba() > 0.3`) and recompute — watch recall rise while precision falls. Write one sentence naming a real problem where you'd deliberately accept low precision to get high recall.",
    doneWhen: "You can define precision and recall in your own words, compute both from a confusion matrix by hand, and explain the tradeoff between them with a concrete example.",
    checks: [
      {q: "A model flags 100 emails as spam; 90 really are. What's its precision, and what does that number ignore?", a: "Precision = 90/100 = 0.9 (90% of its flags were correct). It says nothing about recall — how many of ALL the actual spam emails it missed by not flagging them."},
      {q: "For a cancer-screening model, would you usually prioritise precision or recall, and why?", a: "Recall — you'd rather have some false alarms (lower precision) than MISS a real cancer case (a false negative), because a missed diagnosis is far more costly than a follow-up test on a healthy person."}
    ],
    keyTakeaways: ["Precision = TP/(TP+FP): of what you flagged, how much was right (punishes false alarms).","Recall = TP/(TP+FN): of the real positives, how many you caught (punishes misses).","They trade off against each other; the right balance depends entirely on the problem's costs."],
    resources: [
      {label: "scikit-learn — Precision, recall and F-measures", url: "https://scikit-learn.org/stable/modules/model_evaluation.html#precision-recall-f-measure-metrics", kind: "docs"},
      {label: "Google ML Crash Course — Precision and Recall", url: "https://developers.google.com/machine-learning/crash-course/classification/precision-and-recall", kind: "course"}
    ]
  },
  {
    id: "aiml-f1", title: "F1 score — one number for both",
    concept: "The F1 score combines precision and recall into a single number using their HARMONIC mean: F1 = 2 × (precision × recall) / (precision + recall). The harmonic mean (rather than a plain average) is deliberate — it stays low unless BOTH precision and recall are high, so you can't fake a good F1 by acing one and tanking the other. It's the go-to single metric when you care about the positive class and have class imbalance, precisely because it refuses to be fooled the way accuracy is.",
    analogy: "A plain average is forgiving: 100% precision and 0% recall averages to a respectable-looking 50%. The harmonic mean is harsh and honest: those same numbers give an F1 of 0. It's like a chain — as strong as its weakest link, not the average of its links. That harshness is the whole point: F1 only rewards you when neither precision nor recall is being neglected.",
    examples: [
      {code: "from sklearn.metrics import f1_score, precision_score, recall_score\n\ny_true = [0, 0, 0, 1, 1, 1, 1, 1]\ny_pred = [0, 1, 0, 1, 0, 1, 0, 1]\n\np = precision_score(y_true, y_pred)   # 0.75\nr = recall_score(y_true, y_pred)      # 0.6\nprint(\"F1:\", f1_score(y_true, y_pred))            # 0.666...\nprint(\"harmonic check:\", 2 * p * r / (p + r))     # 0.666... -- same thing", note: "F1 = 2 × (0.75 × 0.6) / (0.75 + 0.6) = 0.9/1.35 ≈ 0.667. Notice it sits below both precision (0.75) and recall (0.6) individually — the harmonic mean always leans toward the smaller of the two, which is exactly why it can't be gamed."},
      {code: "# Why the harmonic mean, not a plain average: it punishes imbalance\np, r = 1.0, 0.0   # perfect precision, zero recall\nplain_avg = (p + r) / 2         # 0.5  -- looks OK\nf1 = 2 * p * r / (p + r) if (p + r) else 0.0   # 0.0 -- honest\nprint(plain_avg, f1)", note: "A plain average would give this useless model a 0.5. F1 gives it 0.0 — the honest answer, because a model with zero recall is worthless no matter how precise it is. This is the property that makes F1 trustworthy on imbalanced data where accuracy lies."}
    ],
    mistakes: ["Reaching for F1 when you actually care about precision and recall UNEQUALLY — if one matters far more, report them separately or use F-beta (which weights them), not plain F1.","Comparing F1 across datasets with very different class balances as if the numbers mean the same thing — they don't.","Forgetting F1 focuses on the POSITIVE class; on a problem where the negative class matters too, you'd look at more than F1 alone."],
    handsOn: "Take a classifier's precision and recall on a test set and compute F1 both with `f1_score()` and by hand with the harmonic-mean formula — confirm they match. Then construct a case where precision is high but recall is low, and observe how F1 lands closer to the low number than a plain average would.",
    doneWhen: "You can state the F1 formula, explain why the harmonic mean (not a plain average) is used, and compute F1 by hand from a precision/recall pair.",
    checks: [
      {q: "Why does F1 use the harmonic mean instead of a normal average of precision and recall?", a: "The harmonic mean stays low unless BOTH values are high — it can't be inflated by acing one metric while neglecting the other, so it honestly reflects a model that's only good at one thing (a plain average would hide that)."},
      {q: "Precision is 1.0 and recall is 0.0. What is the F1 score?", a: "0.0 — the harmonic mean collapses to zero when either input is zero, correctly flagging that a model catching none of the real positives is useless regardless of its precision."}
    ],
    keyTakeaways: ["F1 = harmonic mean of precision and recall = 2PR/(P+R).","The harmonic mean stays low unless BOTH are high — it can't be gamed like accuracy.","Use F1 for the positive class under imbalance; use separate metrics or F-beta when precision and recall matter unequally."],
    resources: [
      {label: "scikit-learn — f1_score", url: "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html", kind: "docs"},
      {label: "Wikipedia — F-score (harmonic mean rationale)", url: "https://en.wikipedia.org/wiki/F-score", kind: "reference"}
    ]
  },
  {
    id: "aiml-roc-auc", title: "ROC curve & AUC — evaluating across all thresholds",
    concept: "Every probability classifier needs a threshold (0.5 by default) to turn a probability into a yes/no — but that one threshold is a choice, and different choices trade precision for recall. The ROC curve plots the True Positive Rate (recall) against the False Positive Rate as you sweep the threshold from 0 to 1, showing the model's behaviour at EVERY possible cutoff at once. AUC (Area Under the Curve) collapses that whole curve into one number: 1.0 is perfect, 0.5 is coin-flip-random, and it measures how well the model RANKS positives above negatives regardless of where you set the threshold.",
    analogy: "Judging a model by accuracy at one threshold is like judging a car by its speed at exactly 30 mph. The ROC curve is the full performance graph across every speed; AUC is the single 'overall capability' score. A high AUC means that if you picked one random positive and one random negative example, the model would almost always give the positive a higher score — good ranking, independent of any specific threshold.",
    examples: [
      {code: "from sklearn.datasets import load_breast_cancer\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import roc_auc_score\n\nX, y = load_breast_cancer(return_X_y=True)\nXtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\nclf = LogisticRegression(max_iter=5000).fit(Xtr, ytr)\n\ny_scores = clf.predict_proba(Xte)[:, 1]   # probability of the positive class\nprint(round(roc_auc_score(yte, y_scores), 3))   # ~0.989", note: "Crucially, `roc_auc_score` takes PROBABILITIES (`predict_proba`), not hard 0/1 labels — because it evaluates ranking across all thresholds, it needs the underlying scores. An AUC near 1.0 here means the model ranks almost every malignant case above every benign one."},
      {code: "# A random-guessing baseline scores ~0.5\nimport numpy as np\nrng = np.random.default_rng(0)\nrandom_scores = rng.random(len(yte))\nprint(round(roc_auc_score(yte, random_scores), 3))   # ~0.5", note: "Feeding pure random scores gives AUC ≈ 0.5 — the coin-flip floor. That's the reference point: any real model needs to beat 0.5 meaningfully. AUC's 0.5-is-random property makes it easy to sanity-check whether a model learned anything at all."}
    ],
    warn: "AUC can look impressively high on heavily imbalanced data even when the model is poor at the rare class you actually care about — because it rewards ranking across the (huge) majority class too. On strong imbalance, precision-recall-based metrics (and the PR-AUC) often tell a more honest story than ROC-AUC.",
    mistakes: ["Passing hard labels (`predict()`) to `roc_auc_score` instead of probabilities (`predict_proba()[:, 1]`) — it needs the scores to sweep thresholds.","Trusting a high ROC-AUC on severely imbalanced data without also checking precision/recall on the minority class.","Thinking AUC tells you the accuracy at a specific threshold — it doesn't; it's a threshold-INDEPENDENT ranking measure."],
    handsOn: "Train a probability classifier on a dataset, get `predict_proba()[:, 1]`, and compute `roc_auc_score`. Then compute AUC on shuffled/random scores and confirm it drops toward 0.5. Write one sentence explaining what an AUC of 0.5 versus 0.99 tells you about the model.",
    doneWhen: "You can explain what the ROC curve plots, that AUC summarises it across all thresholds, that 0.5 = random and 1.0 = perfect, and that roc_auc_score needs probabilities not labels.",
    checks: [
      {q: "Does `roc_auc_score` take hard predicted labels or predicted probabilities, and why?", a: "Predicted probabilities (`predict_proba`) — because AUC evaluates the model across ALL thresholds by ranking, so it needs the continuous scores, not the already-thresholded 0/1 labels."},
      {q: "What does an ROC-AUC of 0.5 tell you?", a: "The model ranks positives no better than random chance — it has learned essentially nothing useful for distinguishing the classes."}
    ],
    keyTakeaways: ["ROC plots true-positive-rate vs false-positive-rate across every threshold; AUC is the area under it.","AUC = 1.0 perfect, 0.5 random — it measures ranking quality independent of any single threshold.","roc_auc_score needs probabilities; and AUC can flatter a model on imbalanced data — cross-check with precision/recall."],
    resources: [
      {label: "scikit-learn — ROC metrics (roc_auc_score, roc_curve)", url: "https://scikit-learn.org/stable/modules/model_evaluation.html#roc-metrics", kind: "docs"},
      {label: "Google ML Crash Course — ROC and AUC", url: "https://developers.google.com/machine-learning/crash-course/classification/roc-and-auc", kind: "course"}
    ]
  },
  {
    id: "aiml-cross-validation", title: "Cross-validation — a more honest score",
    concept: "A single train/test split gives ONE score that depends on which rows happened to land in the test set — you might have gotten lucky or unlucky. K-fold cross-validation fixes this: it splits the data into K equal parts (folds), trains K times, each time holding out a different fold as the test set, and averages the K scores. The result is a more stable, trustworthy estimate of how the model really performs — plus the spread across folds tells you how sensitive the model is to which data it sees.",
    analogy: "Judging a student on a single exam is noisy — they might have had a good or bad day, or the questions happened to suit them. Cross-validation is like averaging five different exams on different question sets: one lucky paper can't dominate, and if their scores swing wildly across exams, that variance itself is useful information about how consistent they really are.",
    examples: [
      {code: "from sklearn.model_selection import cross_val_score\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nclf = LogisticRegression(max_iter=200)\n\nscores = cross_val_score(clf, X, y, cv=5)   # 5-fold cross-validation\nprint(scores.round(3))\nprint(f\"mean={scores.mean():.3f}  std={scores.std():.3f}\")", note: "`cross_val_score` handles the whole split-train-score loop for you: 5 folds means 5 train/score rounds, returning 5 numbers. Report the MEAN as your estimate and the STD as its uncertainty — a low std means the model performs consistently regardless of which slice it's tested on."},
      {code: "# The mean is more trustworthy than any single fold\nprint(\"individual folds:\", scores.round(3))\nprint(\"a single split could have reported any one of those\")\nprint(\"the 5-fold mean smooths out that luck-of-the-draw:\", round(scores.mean(), 3))", note: "This is the core value: any single train/test split you ran in Module 3 could have landed on the high fold or the low fold by chance. Cross-validation's averaged score is far less at the mercy of one random split — the honest number to report and to compare models with."}
    ],
    mistakes: ["Reporting a single train/test split's score as if it were definitive, when it can swing several points just from the random split — cross-validation reveals that swing.","Using too many folds on a tiny dataset (each fold's test set becomes so small the per-fold scores get noisy), or too few to smooth out luck.","Cross-validating AFTER already peeking at the test set to tune the model — that leaks information and inflates the score (proper practice keeps a final untouched test set)."],
    handsOn: "Run `cross_val_score` with cv=5 on a model and dataset, and print both the individual fold scores and the mean/std. Then compare the mean to the single train/test-split score you got for the same model in Module 3 — note whether the single split was optimistic or pessimistic relative to the cross-validated average.",
    doneWhen: "You can explain why a single train/test split is noisy, how K-fold cross-validation produces a steadier estimate, and what a large standard deviation across folds tells you.",
    checks: [
      {q: "Why is the mean of 5-fold cross-validation usually more trustworthy than a single train/test split's score?", a: "A single split's score depends on which rows randomly landed in the test set — it can be lucky or unlucky. Averaging over 5 folds (each testing on a different slice) smooths out that luck-of-the-draw for a steadier estimate."},
      {q: "Cross-validation gives fold scores of [0.98, 0.62, 0.99, 0.97, 0.60]. What does the wide spread suggest?", a: "The model is unstable — its performance depends heavily on which data it's tested on. That high variance is a warning sign (possible overfitting or too little data) that a single split's score would have hidden."}
    ],
    keyTakeaways: ["K-fold cross-validation trains K times, each holding out a different fold, then averages.","The averaged score is a steadier estimate than one noisy train/test split.","The spread (std) across folds reveals how sensitive the model is to its training data."],
    resources: [
      {label: "scikit-learn — Cross-validation", url: "https://scikit-learn.org/stable/modules/cross_validation.html", kind: "docs"},
      {label: "scikit-learn — cross_val_score", url: "https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html", kind: "docs"}
    ]
  },
  {
    id: "aiml-over-underfit", title: "Overfitting & underfitting — the central tension",
    concept: "Underfitting is when a model is too simple to capture the real pattern — it does poorly on BOTH training and test data (like fitting a straight line to a curve). Overfitting is the opposite — the model is so complex it memorises the training data's noise, scoring near-perfectly on training but poorly on test data (the tell you saw with the deep decision tree in Module 3). The goal is the sweet spot between them: complex enough to learn the real signal, simple enough not to memorise noise. The gap between training and test performance is your primary diagnostic.",
    analogy: "Underfitting is a student who barely studied — they fail both the practice papers and the real exam. Overfitting is a student who memorised the exact answers to last year's practice papers — they ace the practice but fail the real exam because the questions changed. The good student learned the underlying concepts: they do well on both, because they can generalise to questions they haven't seen.",
    examples: [
      {code: "from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.datasets import load_digits\nfrom sklearn.metrics import accuracy_score\n\nX, y = load_digits(return_X_y=True)\nXtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\n\n# Underfit: a stump (too simple)\nstump = DecisionTreeClassifier(max_depth=1, random_state=42).fit(Xtr, ytr)\nprint(\"underfit  train/test:\", round(accuracy_score(ytr, stump.predict(Xtr)),2), round(accuracy_score(yte, stump.predict(Xte)),2))\n# ~0.20 / ~0.20 -- bad at BOTH", note: "A depth-1 tree can only ask ONE yes/no question — far too simple for 10-way digit classification, so it scores badly on training AND test (~0.20 each). Both-low is the signature of underfitting: the model literally can't represent the pattern."},
      {code: "# Overfit: an unrestricted tree (too complex)\ndeep = DecisionTreeClassifier(random_state=42).fit(Xtr, ytr)\nprint(\"overfit   train/test:\", round(accuracy_score(ytr, deep.predict(Xtr)),2), round(accuracy_score(yte, deep.predict(Xte)),2))\n# 1.00 / ~0.85 -- perfect on train, worse on test\n\n# Balanced: a moderate depth\nmid = DecisionTreeClassifier(max_depth=10, random_state=42).fit(Xtr, ytr)\nprint(\"balanced  train/test:\", round(accuracy_score(ytr, mid.predict(Xtr)),2), round(accuracy_score(yte, mid.predict(Xte)),2))", note: "The overfit tree memorises training data (100%) but drops to ~85% on unseen test digits — a big train/test GAP is the signature of overfitting. The balanced tree sits between the two extremes. Reading the train-vs-test gap is how you diagnose which problem you have."}
    ],
    mistakes: ["Seeing high TRAINING accuracy and celebrating — near-perfect training scores usually signal overfitting, not success; the test score is what counts.","Fixing underfitting and overfitting the same way — underfitting needs MORE model complexity (or better features), overfitting needs LESS (or more data / regularisation).","Only ever looking at the test score without comparing it to the training score — the GAP between them is what tells you which way you're erring."],
    handsOn: "Train the same model type at three complexity levels (e.g. a decision tree at max_depth 1, 10, and unlimited) on one dataset, and print train AND test accuracy for each. Identify which is underfitting (both low), which is overfitting (big train/test gap), and which is balanced. Write one sentence on how you'd fix the underfitting one versus the overfitting one.",
    doneWhen: "You can define overfitting and underfitting, diagnose which one a model has from its train-vs-test gap, and state the opposite fixes each one needs.",
    checks: [
      {q: "A model scores 100% on training data but 70% on test data. Is it overfitting or underfitting, and what's the fix direction?", a: "Overfitting — the large train/test gap means it memorised the training data. The fix is LESS complexity (shallower model, more regularisation) or more training data."},
      {q: "A model scores 55% on training AND 54% on test. Which problem is this, and how do you fix it?", a: "Underfitting — it's bad at both because it's too simple to capture the pattern. The fix is MORE complexity (a richer model) or better/more features."}
    ],
    keyTakeaways: ["Underfitting: too simple, bad on both train and test. Overfitting: too complex, great on train but poor on test.","The train-vs-test gap is the primary diagnostic for which one you have.","They need opposite fixes — more complexity for underfitting, less (or more data) for overfitting."],
    resources: [
      {label: "scikit-learn — Underfitting vs. Overfitting (worked example)", url: "https://scikit-learn.org/stable/auto_examples/model_selection/plot_underfitting_overfitting.html", kind: "docs"},
      {label: "Google ML Crash Course — Generalization (overfitting)", url: "https://developers.google.com/machine-learning/crash-course/overfitting/overfitting", kind: "course"}
    ]
  }
  ]
};
