// AI Engineer path — Module 1 (Python for ML) quiz bank.
// [lessonSlug, prompt, [correct, ...distractors], correctIndex=0, explanation, difficulty, styleTag]
// Correct answer authored at index 0; the app shuffles options per attempt so position is irrelevant.
// NOTE (content-first remodel): the LIVE quiz set in the DB is thinned to ONE sharpest question
// per lesson. This file keeps the fuller authored bank for reference; the DB is the source of truth.
module.exports = [
// --- NumPy arrays ---
["aiml-numpy","Why is `arr * 2` on a NumPy array faster than a Python for-loop doing the same thing?",["It's vectorised — runs across the whole array in optimized compiled code, not interpreted step by step","NumPy arrays are stored on the GPU by default","Python loops are disabled inside NumPy","It isn't actually faster"],0,"Vectorised operations process the entire array in one optimized pass instead of looping element-by-element in the Python interpreter.",1,"conceptual"],
["aiml-numpy","A NumPy array has shape (100, 5). How many total elements does it have?",["500","100","5","105"],0,"Shape (100, 5) means 100 rows × 5 columns = 500 total elements.",1,"code-output"],
["aiml-numpy","Given `m = np.array([[1,2,3],[4,5,6]])`, what does `m.sum(axis=0)` return?",["[5, 7, 9] — summed down each column","[6, 15] — summed across each row","21 — the total sum","[1, 2, 3]"],0,"axis=0 sums down columns (first dim); 1+4=5, 2+5=7, 3+6=9.",2,"code-output"],
// --- Pandas basics ---
["aiml-pandas","What's the difference between a pandas Series and a DataFrame?",["A Series is one labeled column; a DataFrame is a full table of multiple Series sharing an index","They are identical objects","A DataFrame can only hold numbers; a Series can hold any type","A Series is a NumPy-only concept, unrelated to pandas"],0,"DataFrame = table; Series = single column (or row) within it.",1,"conceptual"],
["aiml-pandas","What does `df[df[\"age\"] > 18]` return?",["A new DataFrame with only the rows where age > 18","A single boolean value","The column named 'age > 18'","An error — you can't compare a column to a number"],0,"This is boolean filtering: the inner expression makes a True/False mask, and wrapping the DataFrame in it selects only the True rows.",1,"code-output"],
["aiml-pandas","What does `df.groupby(\"passed\")[\"score\"].mean()` compute?",["The average score, separately for each value of 'passed' (e.g. True vs False)","The average of the 'passed' column only","A single overall average score","It deletes rows where passed is False"],0,"groupby splits the table into groups by the given column, then mean() aggregates within each group — like a pivot table.",2,"conceptual"],
// --- Cleaning ---
["aiml-cleaning","Why normalise text casing (e.g. `.str.lower()`) before deduplicating rows?",["'Chennai' and 'chennai' are the same real value but won't be caught as duplicates unless casing is normalised first","Lowercase text runs faster in pandas","Deduplication requires all-lowercase column names","It's not necessary — pandas ignores case automatically"],0,"drop_duplicates() checks for exact matches; inconsistent casing hides real duplicates unless normalised first.",1,"conceptual"],
["aiml-cleaning","When might filling missing values with the column mean be a bad idea?",["When the column is skewed by outliers, or the missingness itself is meaningful","Never — the mean is always the safest choice","Only when the column has zero missing values","Mean-filling always improves model accuracy"],0,"A skewed column's mean isn't 'typical', and sometimes WHY a value is missing carries information a naive fill would erase.",2,"conceptual"],
["aiml-cleaning","What does `df.duplicated().sum()` tell you?",["The count of fully duplicate rows in the DataFrame","The number of missing values","The number of unique rows","The sum of all numeric columns"],0,"duplicated() flags rows identical to an earlier row; summing the True/False flags counts them.",1,"code-output"],
// --- Jupyter & venvs ---
["aiml-jupyter","Why create a separate virtual environment for each Python project?",["So each project's package versions are isolated and can't silently break each other","Virtual environments make code run faster","It's required by Python itself to run any script","It automatically deploys your project to the cloud"],0,"venvs isolate installed packages per project — upgrading a library for one project can't break a different one.",1,"conceptual"],
["aiml-jupyter","In a Jupyter notebook, what actually determines a variable's current value — cell position on the page, or something else?",["The ORDER cells were executed in, not their visual position on the page","Only the cell's position on the page matters","Variables reset automatically every time you look at the notebook","Notebooks don't have variables, only outputs"],0,"Notebook state follows execution order; running cells out of order can leave stale values that 'Restart & Run All' would expose.",2,"conceptual"],
["aiml-jupyter","What's the purpose of `python -m venv .venv` followed by activating it?",["Creates and switches into an isolated environment so pip installs only affect this project","Downloads Python itself","Starts the Jupyter server","Deletes all previously installed packages system-wide"],0,"venv creates an isolated folder of packages; activating it points pip/python at that isolated environment.",1,"conceptual"],
// --- Plotting ---
["aiml-plotting","You want to see the relationship between two numeric columns (e.g. hours studied vs test score). Which plot fits best?",["Scatter plot","Histogram","Pie chart","None — you must read the raw numbers"],0,"A scatter plot shows how two numeric variables relate to each other, point by point.",1,"conceptual"],
["aiml-plotting","You want to see the distribution/shape of a single numeric column, including spotting outliers. Which plot fits best?",["Histogram","Scatter plot","A single number like the mean","A bar chart of row indexes"],0,"A histogram groups values into bins and shows counts — revealing shape, spread, and outliers in one variable.",1,"conceptual"],
["aiml-plotting","Why plot data BEFORE training a model, not just after?",["To catch outliers, wrong relationships, or skew early, before they cause confusing performance issues later","Plotting before training is required by scikit-learn","It has no real benefit — plotting matters only after training","It replaces the need for data cleaning entirely"],0,"Pre-training plots surface data problems early, when they're much easier to diagnose and fix.",2,"conceptual"]
];
