// AI Engineer path — Module 2 (Math Intuition for ML) quiz bank.
// [lessonSlug, prompt, [correct, ...distractors], correctIndex=0, explanation, difficulty, styleTag]
// NOTE (content-first remodel): the LIVE quiz set in the DB is thinned to ONE sharpest question
// per lesson. This file keeps the fuller authored bank for reference; the DB is the source of truth.
module.exports = [
// --- Vectors & dot products ---
["aiml-vectors","What does the dot product of two same-length vectors return?",["A single number — the sum of the element-wise products","A new vector of the same length","A matrix","Always zero"],0,"Per NumPy's own docs, the dot product of two 1D arrays is an inner product: multiply matching elements and sum — one scalar out.",1,"conceptual"],
["aiml-vectors","Given features=[2,1,3] and prices=[3,5,1], what is their dot product?",["14","6","9","20"],0,"(2×3)+(1×5)+(3×1) = 6+5+3 = 14.",1,"code-output"],
["aiml-vectors","Why can't you take the dot product of a 3-element vector and a 4-element vector?",["There's no valid way to pair up mismatched positions to multiply and sum","NumPy doesn't support vectors longer than 3 elements","You can — NumPy pads the shorter one with zeros automatically","Dot products only work on integers"],0,"The dot product pairs matching positions; with different lengths there's no consistent pairing, so NumPy raises a shape error.",1,"conceptual"],
// --- Matrices as data tables ---
["aiml-matrices-ml","In `X @ weights` where X has shape (100, 5) and weights has shape (5,), what does the operation compute?",["One prediction per row — 100 predictions total","A single overall prediction","5 predictions, one per feature","It always errors"],0,"Matrix @ vector applies the same dot-product prediction to every row of X at once — one prediction per example.",1,"conceptual"],
["aiml-matrices-ml","For `X @ weights` to work, what must match?",["The number of columns in X and the number of elements in weights","The number of rows in X and the number of elements in weights","X must be a square matrix","Nothing needs to match — NumPy resizes automatically"],0,"The shared 'inner' dimension (X's columns, weights' length) must match — that's the dimension being summed over.",1,"conceptual"],
["aiml-matrices-ml","Why does NumPy raise an error rather than a wrong answer when matrix shapes don't match for multiplication?",["There's no valid mathematical way to pair up mismatched dimensions, so raising an error surfaces the mistake immediately","NumPy is just being overly strict for no real reason","It's a bug that will be fixed in a future version","Shape errors only happen with matrices, never vectors"],0,"An error is a deliberate safety feature — silently producing meaningless numbers would be far worse for debugging.",2,"conceptual"],
// --- Gradients ---
["aiml-gradients","Does the gradient point toward the minimum error or away from it?",["Away from it — toward increasing error","Toward the minimum, directly","It points in a random direction","Gradients only exist at the minimum"],0,"The gradient points toward steepest INCREASING error — training subtracts it (moves opposite) to reduce error, per scikit-learn's own SGD documentation.",2,"conceptual"],
["aiml-gradients","What happens if the learning rate (step size) in gradient descent is too large?",["Updates can overshoot the minimum and bounce around or diverge","Training becomes perfectly accurate instantly","Nothing — learning rate only affects speed, never correctness","The gradient direction reverses"],0,"scikit-learn's documentation explicitly warns that too-large steps can overshoot the optimal solution or cause divergence.",2,"conceptual"],
["aiml-gradients","In the error(w) = (w-3)^2 example, why is the gradient NEGATIVE at w=0 and w=2, but POSITIVE at w=5?",["Below the minimum (w<3), error increases as w decreases, so the gradient is negative; above it (w>5), error increases as w increases, so it's positive","The gradient is random noise with no pattern","It's a bug in the example","Gradients are always negative below zero"],0,"The gradient's sign always points toward the direction of increasing error — negative below the minimum (since decreasing w increases error), positive above it.",2,"code-output"],
// --- Probability ---
["aiml-probability","If a spam filter outputs '70% spam' for an email, what does that mean?",["A calibrated estimate of likelihood, not a guarantee — about 30% of similarly-scored emails would not be spam","The email is definitely spam","The filter is 70% broken","The email will be spam 70% of the time it's opened"],0,"Model probabilities are calibrated estimates of likelihood based on patterns in similar past examples, not certainties.",1,"conceptual"],
["aiml-probability","What does raising the decision threshold from 0.5 to 0.7 generally do?",["Reduces the number of positive predictions — only higher-confidence cases cross the bar","Increases the number of positive predictions","Has no effect on predictions","Makes the model retrain from scratch"],0,"A higher threshold requires more confidence before predicting positive, so fewer examples qualify.",1,"conceptual"],
["aiml-probability","For one event with mutually exclusive outcomes (e.g. spam vs not spam), what must the probabilities of all outcomes sum to?",["1","0","100","It varies — no fixed rule"],0,"All possible outcomes of one event must sum to exactly 1 — a useful sanity check on model output.",1,"conceptual"],
// --- Loss ---
["aiml-loss","Why does Mean Squared Error square the errors before averaging, instead of just averaging raw errors?",["Squaring makes all errors positive (so they don't cancel out) and penalises large errors more than small ones","Squaring makes the calculation faster","Squaring is only done for historical reasons and doesn't affect anything","Squaring converts the loss into a probability"],0,"Both effects — no cancellation, and disproportionate penalty for big errors — are deliberate properties of MSE.",1,"conceptual"],
["aiml-loss","Why can't models usually be trained directly on plain accuracy?",["Accuracy jumps in sharp steps and has no smooth gradient for gradient descent to follow","Accuracy is illegal to use in ML","Accuracy is always 100% during training","Models can be trained on accuracy just as easily as any other metric"],0,"Accuracy is either right or wrong with no smooth in-between, so it provides no usable gradient signal — a smoother loss like log loss is needed instead.",2,"conceptual"],
["aiml-loss","true_values=[3.0,5.0,2.5,7.0], predictions=[2.8,5.4,2.0,6.5]. Is the MSE closer to 0.2 or 20?",["0.2 — the errors here are all small (under 0.5 each)","20 — squaring always produces large numbers","Exactly 0 — the predictions are perfect","It can't be computed without more data"],0,"Each individual error is well under 1, so squaring keeps them small; the MSE here is about 0.175 — close to 0.2, nowhere near 20.",2,"code-output"]
];
