// FORAGE — AI Engineer path, Module 9: Monitoring & Drift
// A conceptually tight module — production monitoring and drift are awareness-level topics for
// a fresher AI Engineer, not something requiring a large curriculum. The drift-detection code
// example was executed for real with SciPy's Kolmogorov-Smirnov test.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "aiml-monitoring", title: "Monitoring & Drift",
  why: "A model that scored 95% accuracy at launch can quietly get worse over time as the real world changes around it — with no error, no crash, just steadily wrong predictions. This module covers what a responsible AI Engineer watches for once a model is live, connecting directly to Module 4's evaluation metrics and Module 7's serving API.",
  topics: [
  {
    id: "aiml-why-monitor", title: "Why a deployed model needs ongoing monitoring",
    concept: "Module 4 taught you how to evaluate a model BEFORE deployment, on a held-out test set. But a live model keeps making predictions on NEW real-world data indefinitely — and unlike a crashed server, a model that's quietly gotten worse doesn't throw an error. It just keeps confidently returning predictions, some increasingly wrong, unless someone is actively tracking its real-world performance over time. Monitoring means continuing to measure the same kinds of metrics from Module 4 (accuracy, precision/recall where you have ground truth, or proxy signals where you don't) on live traffic, not just at training time.",
    analogy: "A model evaluated once before launch and never checked again is like a car that passed its safety inspection the day it was bought and never got serviced again — it might run fine for a long time, or it might be quietly wearing down in ways you won't notice until something actually breaks, possibly at the worst moment. Monitoring is the recurring service check that catches quiet degradation before it becomes a visible failure.",
    examples: [
      {code: "# A model can 'fail silently' -- it keeps returning predictions, just increasingly wrong ones\nimport numpy as np\n\n# Simulated: model accuracy measured weekly after launch\nweekly_accuracy = [0.94, 0.93, 0.92, 0.89, 0.85, 0.81, 0.76]\nfor week, acc in enumerate(weekly_accuracy, start=1):\n    flag = \" <-- investigate\" if acc < 0.85 else \"\"\n    print(f\"week {week}: accuracy = {acc:.2f}{flag}\")", note: "No error was ever thrown here -- the API kept returning HTTP 200 responses with real predictions the entire time. Only by TRACKING accuracy over time (something you have to deliberately set up) does this decline become visible at all, ideally before it crosses a threshold that matters for the business."}
    ],
    warn: "Getting ground-truth labels for live predictions is often the hardest part of monitoring in practice — for many real systems, you don't immediately know if a prediction was 'right' (e.g. did the user actually churn? did the transaction turn out to be fraud?). Real monitoring setups often rely on delayed feedback loops or proxy signals when direct ground truth isn't instantly available.",
    mistakes: ["Assuming 'it passed evaluation once' means it's fine forever — the real world a model operates in keeps changing after launch.","Not planning HOW you'll get ground-truth labels for live predictions before you need them — this is often the actual hard engineering problem in monitoring.","Treating monitoring as optional/nice-to-have rather than a core part of responsibly shipping a model to production."],
    handsOn: "Take a model you've evaluated in this path (e.g. from Module 3 or 4). Write one paragraph: what real-world signal would tell you if this exact model started performing worse after 'deployment', and how quickly could you realistically find out (immediately? days later? months later)? Be honest about where the ground-truth-labels problem would bite you.",
    doneWhen: "You can explain why a live model needs ongoing monitoring beyond its pre-launch evaluation, and you've reasoned through a concrete ground-truth-availability challenge for a real model.",
    checks: [
      {q: "Why doesn't a degrading model typically throw an error or crash the way a buggy server would?", a: "The model keeps functioning and returning predictions normally (the API still responds successfully) — it's just increasingly WRONG, which is invisible unless you're actively measuring real-world accuracy/precision/recall over time, not just checking that the service is 'up'."}
    ],
    keyTakeaways: ["A live model can silently degrade without any crash or error — monitoring is how you'd notice.", "Monitoring means continuing to measure Module 4's metrics on real, ongoing traffic, not just at training time.", "Getting ground-truth labels for live predictions is often the hardest real-world part of monitoring."],
    resources: [
      {label: "Google Cloud — MLOps: monitoring pipelines", url: "https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning", kind: "docs"},
      {label: "Evidently AI — ML monitoring guide", url: "https://www.evidentlyai.com/ml-in-production/model-monitoring", kind: "reference"}
    ]
  },
  {
    id: "aiml-data-drift", title: "Data drift — when the input changes",
    concept: "Data drift (also called covariate shift) is when the STATISTICAL DISTRIBUTION of the model's real-world input data changes over time, diverging from what it was trained on — even if the underlying relationship between features and the correct answer hasn't changed at all. A concrete example: a model trained on customer ages skewing 25-40 starts seeing far more 55+ users after a product's audience shifts; the model was never trained on that region of the input space, so its predictions there are less trustworthy, even though nothing about the MODEL itself broke.",
    analogy: "Data drift is like a translator trained mostly on formal business English suddenly getting a flood of casual internet slang to translate. Nothing about their translation SKILL changed — but the INPUT they're now facing looks meaningfully different from what they trained on, so their output quality for this new kind of input can't be trusted the same way.",
    examples: [
      {code: "import numpy as np\nfrom scipy import stats\n\nnp.random.seed(0)\n# Training-time age distribution: centered around 32\ntraining_ages = np.random.normal(32, 6, 1000)\n\n# Live traffic a few months later: distribution has shifted older\nlive_ages_similar = np.random.normal(33, 6, 1000)     # barely shifted\nlive_ages_drifted = np.random.normal(50, 8, 1000)      # meaningfully shifted\n\n# Kolmogorov-Smirnov test: are these two samples from the same distribution?\nstat1, p1 = stats.ks_2samp(training_ages, live_ages_similar)\nstat2, p2 = stats.ks_2samp(training_ages, live_ages_drifted)\nprint(f\"similar traffic:  KS stat={stat1:.3f}, p-value={p1:.3f}\")\nprint(f\"drifted traffic:  KS stat={stat2:.3f}, p-value={p2:.3f}\")", note: "The KS STATISTIC is the number to watch in practice: 0.115 for the barely-shifted traffic vs. 0.812 for the meaningfully-drifted traffic -- a clear, order-of-magnitude difference. With a large sample size (1000 here), the p-value alone can be near-zero for BOTH cases, since even a trivial shift becomes 'statistically significant' at scale -- a real, important nuance: judge drift SEVERITY by the KS statistic's magnitude, not just whether the p-value crosses 0.05, especially with large real-world traffic volumes."}
    ],
    mistakes: ["Confusing drift detection with a claim about model correctness — a drift alert says the INPUT DATA looks different, not necessarily that predictions are now wrong (though it's a real risk worth investigating).","Only eyeballing input data occasionally instead of tracking distribution statistics systematically — drift can be gradual and easy to miss without measurement.","Ignoring WHICH features drifted — investigate the specific features flagged, since drift severity and impact varies a lot by feature."],
    handsOn: "Run the KS-test example with your own two synthetic distributions — one barely shifted from the 'training' baseline, one meaningfully shifted. Confirm the p-value and KS statistic clearly distinguish the two cases. Then think of one real feature from a model you've built in this path, and describe a realistic way its real-world distribution could drift after launch.",
    doneWhen: "You can define data drift in your own words, distinguish it from a model bug, and have run a real statistical test that detects it.",
    checks: [
      {q: "What is data drift, and why can it hurt model performance even though the model itself hasn't changed?", a: "Data drift is when the real-world input distribution diverges from what the model was trained on. The model's learned patterns may not generalize well to input regions it never saw during training, so predictions there become less trustworthy — even though the model's internal weights haven't changed at all."}
    ],
    keyTakeaways: ["Data drift is a shift in the input distribution away from what the model was trained on.", "It can degrade real-world performance without any change to the model itself.", "Statistical tests (e.g. Kolmogorov-Smirnov) give a concrete, measurable signal of drift rather than a guess."],
    resources: [
      {label: "SciPy — Kolmogorov-Smirnov two-sample test docs", url: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html", kind: "docs"},
      {label: "Evidently AI — Data drift explained", url: "https://www.evidentlyai.com/ml-in-production/data-drift", kind: "reference"}
    ]
  },
  {
    id: "aiml-concept-drift", title: "Concept drift — when the relationship itself changes",
    concept: "Concept drift is a distinct, often subtler problem from data drift: the relationship between the INPUT and the CORRECT ANSWER changes over time, even if the input distribution itself looks the same. A classic example: a fraud-detection model trained on historical fraud patterns keeps seeing similarly-distributed transactions, but fraudsters adapt their tactics — the same INPUT FEATURES that used to signal 'legitimate' now increasingly co-occur with actual fraud. The world's underlying rules shifted, not just what inputs look like.",
    analogy: "If data drift is a translator suddenly facing unfamiliar slang, concept drift is subtler and sneakier: the SAME words they've always translated have quietly started meaning something different in common usage (like how 'literally' now often means 'figuratively' in casual speech) — the input looks familiar, but the correct mapping to meaning has shifted underneath them.",
    examples: [
      {code: "# Illustrating the distinction: same input distribution, different correct-answer mapping\nimport numpy as np\n\nnp.random.seed(0)\ntransaction_amount = np.random.normal(200, 50, 8)   # SAME distribution before/after\n\n# BEFORE: only large amounts were flagged as fraud in this simplified toy rule\nwas_fraud_before = transaction_amount > 400          # rare\n\n# AFTER (concept drift): fraudsters shifted tactics -- now MID-size amounts are the fraud signal\nwas_fraud_after = (transaction_amount > 180) & (transaction_amount < 260)\n\nprint(\"amounts:\", transaction_amount.round(0))\nprint(\"fraud rule BEFORE:\", was_fraud_before)\nprint(\"fraud rule AFTER: \", was_fraud_after)", note: "This is a simplified illustration of the CONCEPT, not a real fraud dataset -- notice the input (transaction_amount) has the exact same distribution in both cases, but which values actually correlate with fraud has completely changed: the BEFORE rule flags none of these transactions, while the AFTER rule flags several mid-size ones. A model trained on the BEFORE rule would be confidently wrong under the AFTER reality, and a data-drift check on the input alone wouldn't catch this at all — the input values themselves haven't changed."}
    ],
    mistakes: ["Assuming a data-drift check alone is sufficient monitoring — concept drift can happen with a perfectly stable-looking input distribution, so it requires tracking actual outcome accuracy, not just input statistics.","Confusing concept drift with data drift — they're different problems with different detection strategies (data drift: compare input distributions; concept drift: compare model accuracy/error against ground truth over time).","Assuming concept drift is rare — it's common in any domain with adaptive actors (fraud, spam, ad-click behavior) or genuinely evolving real-world conditions."],
    handsOn: "Write one paragraph describing a realistic concept-drift scenario for a domain you're interested in (not necessarily fraud) — specifically explain what INPUT would look unchanged, but what underlying real-world relationship would have shifted, and why a plain data-drift check wouldn't catch it.",
    doneWhen: "You can clearly distinguish concept drift from data drift, and can describe a realistic real-world scenario where the input looks stable but the true input-to-answer relationship has changed.",
    checks: [
      {q: "How does concept drift differ from data drift, and why might a data-drift check fail to catch it?", a: "Data drift is a shift in the INPUT distribution; concept drift is a shift in the actual RELATIONSHIP between input and correct answer, which can happen even while the input distribution looks completely stable. A data-drift check only compares input statistics, so it can miss concept drift entirely — you need to track real outcome accuracy over time instead."}
    ],
    keyTakeaways: ["Concept drift is a change in the true input-to-answer relationship, distinct from data drift.", "It can occur even when the input distribution looks unchanged.", "Detecting it requires tracking real outcome accuracy over time, not just input statistics."],
    resources: [
      {label: "Evidently AI — Concept drift explained", url: "https://www.evidentlyai.com/ml-in-production/concept-drift", kind: "reference"},
      {label: "Google Cloud — MLOps continuous monitoring", url: "https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning", kind: "docs"}
    ]
  }
  ]
};
