// FORAGE — Cybersecurity path, Module 1: Networking & Linux Security Foundations
// ETHICS FRAMING (applies to the whole path): all content here is DEFENSIVE and educational —
// understanding how systems work and how to protect them, in authorized contexts only (your own
// lab, sanctioned CTF competitions, or explicitly permitted testing). No content in this path
// provides real attack payloads or instructions for targeting systems without authorization.
// Facts verified against standard networking references. Code snippets executed for real
// against safe, local, self-owned resources only (localhost, own files).
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "cyber-foundations", title: "Networking & Linux Security Foundations",
  why: "You can't secure what you don't understand. This module builds the same foundational networking and Linux knowledge every security professional needs, framed from day one around defense: knowing how systems work so you can recognize when something is wrong and know how to harden it.",
  topics: [
  {
    id: "cyber-ethics-scope", title: "Ethics and scope — the rule that comes first",
    concept: "Before any technical content: security skills are powerful, and using them against systems you don't own or have EXPLICIT WRITTEN AUTHORIZATION to test is illegal in virtually every jurisdiction — the Computer Fraud and Abuse Act (US) and equivalent laws elsewhere treat unauthorized access as a crime regardless of intent. This entire path teaches DEFENSIVE understanding and AUTHORIZED testing practice (your own local lab, sanctioned CTF/Capture-The-Flag competitions, or a real engagement with a signed authorization). Every concept from here forward is taught for that purpose — understanding a vulnerability class to defend against it, never to exploit systems you don't have permission to touch.",
    analogy: "A locksmith learns how locks work, including their weaknesses, specifically so they can help people secure their homes — practicing lockpicking on YOUR OWN lock, or a client's lock with their explicit permission, is a legitimate skill. Picking a stranger's lock without permission, even 'just to see if it works,' is a crime regardless of how curious or well-intentioned you are. Security skills follow the exact same line.",
    examples: [
      {code: "# The authorization checklist before ANY security testing, always\nauthorization_checklist = [\n    \"Do I own this system, OR\",\n    \"Do I have EXPLICIT WRITTEN permission from the owner, OR\",\n    \"Is this a sanctioned platform built for practice (e.g. a CTF, a designated training lab)?\",\n    \"If none of the above are true: STOP. Testing this system is not authorized.\",\n]\nfor item in authorization_checklist:\n    print(item)", note: "This is the mental checklist every security professional runs before touching ANY system, every single time -- 'I was just curious' or 'I didn't cause any real damage' are not legal defenses for unauthorized access in essentially any jurisdiction."}
    ],
    warn: "This module and the rest of this path deliberately do NOT provide exploit payloads, real attack scripts targeting live systems, or step-by-step 'how to break into X' instructions. All hands-on practice should happen against your own local machine, your own deliberately-vulnerable practice environments (like OWASP's own training platforms, referenced in later lessons), or sanctioned CTF competitions — never against a system you don't have explicit permission to test.",
    mistakes: ["Assuming 'no real harm done' or 'I told them afterward' makes unauthorized access legal — it generally does not, under laws like the CFAA.","Testing against a live production system 'just to check' without explicit written authorization — even well-intentioned bug-hunting on systems you don't own can constitute a real crime.","Treating this path's defensive framing as a limitation rather than the actual professional standard — real, employed security professionals overwhelmingly work defensively and under strict authorization; that IS the job, not a watered-down version of it."],
    handsOn: "Write down, in your own words, the three legitimate contexts where security testing is authorized (your own systems, explicit written permission, sanctioned practice platforms). Then identify one platform (research this yourself — e.g. a well-known CTF platform or an intentionally-vulnerable training app) you could practice on legally once you have hands-on skills later in this path.",
    doneWhen: "You can clearly state the authorization boundary for security testing and name at least one legitimate, sanctioned practice context.",
    checks: [
      {q: "Is it legal to test a website's security 'just to see if it's vulnerable' if you don't own it and haven't been given permission?", a: "No — unauthorized access or testing, even without malicious intent or actual damage, is generally illegal under laws like the Computer Fraud and Abuse Act (US) and equivalent laws elsewhere. Authorization must be explicit (ownership, written permission, or a sanctioned practice platform) before any testing."}
    ],
    keyTakeaways: ["Security testing requires explicit authorization: ownership, written permission, or a sanctioned practice platform.", "Unauthorized access is illegal regardless of intent or whether damage occurred.", "This entire path teaches defensive understanding and authorized practice — the actual professional standard."],
    resources: [
      {label: "OWASP — Testing Guide (scope and authorization)", url: "https://owasp.org/www-project-web-security-testing-guide/", kind: "docs"},
      {label: "TryHackMe — legal, sanctioned practice platform", url: "https://tryhackme.com/", kind: "practice"}
    ]
  },
  {
    id: "cyber-networking-basics", title: "How networks actually work",
    concept: "Every network connection follows the same basic pattern: an IP ADDRESS identifies a machine (like a street address), and a PORT identifies a specific SERVICE on that machine (like an apartment number) — port 80/443 for web traffic, port 22 for SSH remote access, port 53 for DNS. Understanding what's normally running on which ports is foundational to BOTH offense and defense — a defender who doesn't know their own system's normal open ports can't recognize an abnormal one.",
    analogy: "If an IP address is a building's street address, ports are the individual apartment numbers within it — mail (network traffic) addressed to '192.168.1.10, apartment 22' goes specifically to the SSH service, not the whole building. A security-conscious building manager knows exactly which apartments are supposed to be occupied (which ports SHOULD be open) — so an unexpected new occupant (an unexpectedly open port) immediately stands out as worth investigating.",
    examples: [
      {code: "# Common, well-known ports (memorize these -- they come up constantly in security work)\nwell_known_ports = {\n    20: \"FTP (data)\", 21: \"FTP (control)\",\n    22: \"SSH (secure remote login)\",\n    23: \"Telnet (INSECURE remote login -- avoid)\",\n    25: \"SMTP (email sending)\",\n    53: \"DNS (domain name resolution)\",\n    80: \"HTTP (unencrypted web)\",\n    443: \"HTTPS (encrypted web)\",\n    3306: \"MySQL database\",\n    5432: \"PostgreSQL database\",\n}\nfor port, service in sorted(well_known_ports.items()):\n    print(f\"port {port:>5}: {service}\")", note: "This is a reference table worth genuinely memorizing -- recognizing that port 23 (Telnet) being open on a modern system is an immediate red flag (it transmits credentials in PLAIN TEXT, unlike SSH's port 22) is a real, practical security-awareness skill, not just trivia."},
      {code: "import socket\n\ndef check_port(host, port, timeout=1):\n    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    sock.settimeout(timeout)\n    result = sock.connect_ex((host, port))   # 0 means the port is open/reachable\n    sock.close()\n    return result == 0\n\n# Checking YOUR OWN localhost -- always authorized, since it's your own machine\nfor port in [22, 80, 443, 3306, 9999]:\n    status = \"open\" if check_port(\"127.0.0.1\", port) else \"closed\"\n    print(f\"localhost:{port} -- {status}\")", note: "This checks ports on 127.0.0.1 (localhost) -- YOUR OWN machine, always a legitimate target for this kind of check. connect_ex returning 0 means the connection succeeded (port open); a non-zero value means it failed (closed/filtered). This exact technique, run against someone else's system without authorization, is a form of network scanning that requires permission -- the ethics lesson's boundary applies here directly."}
    ],
    mistakes: ["Running the port-check example (or any network scanning tool) against a host you don't own or have permission to test — even a 'harmless' check is scanning, and scanning without authorization can itself be a violation.","Confusing an IP address (identifies the MACHINE) with a port (identifies the SERVICE on that machine) — a very common beginner mix-up.","Assuming an open port is automatically a vulnerability — many open ports are intentional and necessary (e.g. 443 for a real website); the concern is UNEXPECTED or misconfigured open ports, not open ports in general."],
    handsOn: "Run the port-check example against your own localhost (127.0.0.1) and confirm the results match what you know is actually running on your machine. Memorize the well-known ports table — you'll need this vocabulary throughout the rest of the path.",
    doneWhen: "You can explain the IP-address-vs-port distinction, name at least 5 well-known ports and their services, and have safely checked your own localhost's port status.",
    checks: [
      {q: "Why is port 23 (Telnet) considered a security red flag on a modern system, while port 22 (SSH) is standard and expected?", a: "Telnet transmits data — including login credentials — in PLAIN TEXT over the network, meaning anyone intercepting the traffic can read them directly. SSH encrypts the connection, protecting credentials and data in transit, which is why SSH replaced Telnet as the standard for secure remote access."}
    ],
    keyTakeaways: ["An IP address identifies a machine; a port identifies a specific service on that machine.", "Knowing which ports SHOULD be open on your own systems is foundational to recognizing abnormal activity.", "Scanning ports on a system you don't own or have permission to test is a form of unauthorized activity — only test your own systems or authorized targets."],
    resources: [
      {label: "IANA — Service Name and Transport Protocol Port Number Registry", url: "https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml", kind: "reference"},
      {label: "Cloudflare Learning — What is a computer port?", url: "https://www.cloudflare.com/learning/network-layer/what-is-a-computer-port/", kind: "docs"}
    ]
  },
  {
    id: "cyber-linux-permissions", title: "Linux file permissions and hardening basics",
    concept: "Linux security starts with its permission model: every file has three permission sets (owner/group/other), each controlling READ, WRITE, and EXECUTE access, commonly shown as a string like `-rwxr-xr--` or a number like `754`. The PRINCIPLE OF LEAST PRIVILEGE — giving a file, process, or user only the access it genuinely needs, nothing more — is the foundational hardening idea underneath almost every Linux security practice, from file permissions to service accounts to firewall rules.",
    analogy: "Linux file permissions are like a building with three tiers of keys: your OWN office key (owner), a shared department key (group), and a general lobby key anyone in the building might have (other). The principle of least privilege says: don't hand out master keys to everyone just because it's convenient — give each person exactly the access their actual job requires, so a stolen or compromised key (or account) only opens what it was ever supposed to.",
    examples: [
      {code: "import os\nimport stat\n\n# Create a test file in a safe temp location and inspect its permissions\ntest_path = os.path.join(os.path.dirname(__file__), \"perm_test.txt\") if \"__file__\" in dir() else \"perm_test.txt\"\nwith open(test_path, \"w\") as f:\n    f.write(\"test\")\n\nmode = os.stat(test_path).st_mode\nprint(\"permission string:\", stat.filemode(mode))\nprint(\"octal:\", oct(mode)[-3:])\n\nos.chmod(test_path, 0o600)   # owner read/write ONLY -- no group/other access\nprint(\"after chmod 600:\", stat.filemode(os.stat(test_path).st_mode))\n\nos.remove(test_path)", note: "chmod 0o600 grants read+write to the OWNER only, with zero permissions for group or other -- exactly the least-privilege pattern for a sensitive file (like one containing credentials or private keys), which is why files like SSH private keys are REQUIRED to have restrictive permissions or SSH itself will refuse to use them."},
      {code: "# The permission digits, decoded (this is worth memorizing)\npermission_bits = {\n    7: \"rwx (read+write+execute)\",\n    6: \"rw- (read+write)\",\n    5: \"r-x (read+execute)\",\n    4: \"r-- (read only)\",\n    0: \"--- (no access)\",\n}\nprint(\"chmod 754 means:\")\nprint(\"  owner:\", permission_bits[7])\nprint(\"  group:\", permission_bits[5])\nprint(\"  other:\", permission_bits[4])", note: "Each digit in a chmod number (like 754) independently sets owner/group/other permissions using the same 3-bit encoding (4=read, 2=write, 1=execute, summed) -- 7=4+2+1=rwx, 5=4+1=r-x, 4=read-only. This decoding is genuinely useful to have memorized rather than looked up every time."}
    ],
    warn: "Run these examples on a REAL Linux system (WSL, a Linux VM, or a Linux server) — Windows' NTFS filesystem does NOT implement true Unix permission bits, so os.chmod() on native Windows silently has no real effect (the file stays fully readable/writable by everyone regardless of the chmod value). This is a genuine, verified platform difference, not a hypothetical caveat — always verify Linux-permission code on an actual Linux environment. Also: only create/modify files you own in a safe location — never run permission-modifying commands (chmod, chown) on system files you don't understand, especially with elevated privileges (sudo).",
    mistakes: ["Using overly permissive settings (like 777, granting everyone full access) 'to make an error go away' instead of diagnosing the real permission need — a very common, genuinely dangerous shortcut.","Confusing read/write/execute on a DIRECTORY (execute means 'can enter/traverse it', not 'can run it as a program') with the same bits on a FILE (execute means 'can run it as a program').","Running chmod/chown with sudo on system files without understanding the consequence — this can break the system or create real security holes."],
    handsOn: "Run both examples, confirm the permission string and octal notation match, and confirm chmod 600 correctly restricts access. Then create a few test files with different chmod values (644, 700, 755) and predict each one's permission string BEFORE checking it.",
    doneWhen: "You can read and set Linux file permissions in both string and octal notation, and can explain the principle of least privilege in your own words.",
    checks: [
      {q: "What does chmod 600 grant, and why is it the correct choice for a sensitive file like an SSH private key?", a: "chmod 600 grants read+write to the file's OWNER only, with zero access for group or other users — exactly the least-privilege setting needed for sensitive files, since anyone else with any access to the file could read the private key otherwise."}
    ],
    keyTakeaways: ["Linux permissions control read/write/execute access separately for owner, group, and other.", "The principle of least privilege — granting only necessary access — underlies almost all Linux security hardening.", "Overly permissive settings (like 777) as a quick fix for permission errors are a common, genuinely dangerous shortcut."],
    resources: [
      {label: "Linux man pages — chmod(1)", url: "https://man7.org/linux/man-pages/man1/chmod.1.html", kind: "docs"},
      {label: "DigitalOcean — An Introduction to Linux Permissions", url: "https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-permissions", kind: "reference"}
    ]
  }
  ]
};
