// FORAGE — Cybersecurity path, Module 2: Web Security Fundamentals
// DEFENSIVE FRAMING (continues Module 1's ethics rule): every vulnerability class here is
// explained conceptually and defended against — no exploit payloads or instructions targeting
// real systems. Facts verified against OWASP's own official documentation. Defensive code
// (parameterized queries, output escaping) executed for real against safe, local, self-owned
// SQLite databases and Python strings only.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "cyber-websec", title: "Web Security Fundamentals",
  why: "Most real-world breaches exploit a small set of well-understood web vulnerability classes. Understanding HOW they work — conceptually, defensively — is what lets you actually prevent them in code you write or review, which is the daily reality of application security work.",
  topics: [
  {
    id: "cyber-sql-injection", title: "SQL injection — and the fix that actually works",
    concept: "Per OWASP's own documentation, SQL injection happens when untrusted user input is used to build a database query, and the database can't tell the difference between INTENDED COMMAND STRUCTURE and DATA — so attacker-supplied text can alter the query's actual logic. OWASP's primary, leading defense is PARAMETERIZED QUERIES (prepared statements): instead of building a query by concatenating strings, you pass user input as separate, clearly-marked DATA parameters — the database engine then guarantees that data is only ever treated as data, never as executable query structure, no matter what characters it contains.",
    analogy: "Building a SQL query by string concatenation is like handwriting a form letter where you literally paste in whatever the recipient tells you to paste — if they write instructions instead of a name, your 'form letter' might now say something you never intended. A parameterized query is like a form with clearly labeled fill-in-the-blank fields: no matter what someone writes in the 'name' blank, it can never accidentally become a new instruction elsewhere in the letter — the structure and the data are kept genuinely separate.",
    examples: [
      {code: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE users (username TEXT, password TEXT)\")\nconn.execute(\"INSERT INTO users VALUES ('alice', 'secret123')\")\nconn.commit()\n\n# VULNERABLE pattern: building the query via string concatenation/f-string\ndef vulnerable_login(username):\n    query = f\"SELECT * FROM users WHERE username = '{username}'\"\n    return query   # returning the QUERY STRING itself, to inspect it -- not executing it\n\nnormal_input = vulnerable_login(\"alice\")\nprint(\"normal input produces:\", normal_input)\n\nmalicious_input = vulnerable_login(\"alice' OR '1'='1\")\nprint(\"malicious input produces:\", malicious_input)\nprint(\"notice: the query's LOGIC has been altered -- '1'='1' is always true,\")\nprint(\"which would match EVERY row, not just alice's\")", note: "This deliberately only PRINTS the constructed query string (never executes it) to safely illustrate the exact mechanism OWASP describes: attacker-supplied text becomes part of the query's LOGIC, not just its data, because string concatenation gives the database no way to distinguish the two."},
      {code: "# The FIX: parameterized queries -- the '?' placeholder keeps data as data, always\ndef safe_login(username):\n    cursor = conn.execute(\"SELECT * FROM users WHERE username = ?\", (username,))\n    return cursor.fetchall()\n\nprint(\"normal input:\", safe_login(\"alice\"))\nprint(\"malicious input:\", safe_login(\"alice' OR '1'='1\"))\nprint(\"the malicious string is treated as a LITERAL username to search for --\")\nprint(\"since no username actually equals that literal text, it correctly returns nothing\")\n\nconn.close()", note: "With a parameterized query, the SAME malicious input that broke the vulnerable version is now safely treated as pure DATA -- SQLite searches for a username that is LITERALLY \"alice' OR '1'='1\", finds no match, and correctly returns an empty result. This is OWASP's documented, primary, most effective defense against SQL injection."}
    ],
    warn: "Never test SQL injection payloads (even conceptual ones like this lesson's) against a real, live application you don't own or have explicit authorization to test. These examples run entirely against a local, in-memory SQLite database created for this lesson — genuinely safe because nothing outside this script is touched.",
    mistakes: ["Trying to 'sanitize' user input by manually stripping or escaping specific characters (like quotes) instead of using parameterized queries — manual escaping is fragile and historically has been repeatedly bypassed; parameterization is the actual robust fix.","Using string formatting/concatenation ANYWHERE in a SQL query that includes user input, even 'just this one time' — the vulnerability doesn't require malicious intent from the developer, just one unguarded query.","Assuming an ORM (object-relational mapper) automatically prevents all injection — most modern ORMs DO parameterize queries safely by default, but writing raw SQL fragments within an ORM can still reintroduce the vulnerability."],
    handsOn: "Run both examples and confirm the vulnerable version's query string is altered by the malicious input, while the parameterized version correctly treats it as harmless literal data. Then find a piece of code (yours or an open-source example) that builds a SQL query via string formatting and rewrite it using parameterized queries.",
    doneWhen: "You can explain what SQL injection is conceptually, why parameterized queries fix it, and have demonstrated both the vulnerable pattern and the fix safely against a local database.",
    checks: [
      {q: "Why do parameterized queries prevent SQL injection, when simply escaping special characters in user input does not reliably?", a: "Parameterized queries keep the query's STRUCTURE and the user-supplied DATA completely separate at the database engine level — the data is never interpreted as part of the query's logic, no matter what characters it contains. Manual character-escaping tries to neutralize dangerous characters after the fact, which has repeatedly proven fragile and bypassable across different contexts and encodings."}
    ],
    keyTakeaways: ["SQL injection happens when untrusted input alters a query's structure because the database can't distinguish command from data.", "Parameterized queries (prepared statements) are OWASP's primary, most reliable defense — they keep data as data, always.", "Manual character-escaping is a fragile, historically-bypassed defense compared to parameterization."],
    resources: [
      {label: "OWASP — SQL Injection", url: "https://owasp.org/www-community/attacks/SQL_Injection", kind: "docs"},
      {label: "OWASP — SQL Injection Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html", kind: "docs"}
    ]
  },
  {
    id: "cyber-xss", title: "Cross-site scripting (XSS) — and output encoding",
    concept: "Per OWASP's documentation, XSS happens when malicious script gets injected into a trusted website and the victim's browser executes it, believing it came from that trusted source — commonly used to steal session cookies or perform actions as the victim. OWASP describes three types: REFLECTED (the malicious input round-trips through a single request, often via a crafted link), STORED (the malicious script is saved on the server — e.g. in a comment field — and served to every visitor who views it), and DOM-based (a purely client-side JavaScript vulnerability). OWASP's primary defenses: OUTPUT ENCODING (converting special characters so they display as TEXT rather than execute as code) and input validation.",
    analogy: "A web page that inserts user input directly into the HTML without encoding is like a whiteboard where anyone can write not just messages, but also literal STICKY NOTES THAT CONTROL THE BUILDING'S INTERCOM SYSTEM — if the board can't tell the difference between 'a message to display' and 'a command to execute,' a malicious 'message' becomes a real action. Output encoding is like converting every submitted note into a photograph of handwriting first — no matter what someone wrote, it can only ever be DISPLAYED as an image of text, never accidentally trigger the intercom.",
    examples: [
      {code: "# VULNERABLE pattern: directly inserting user input into HTML (illustrative string, not rendered)\nuser_comment = \"<script>alert('this would run in a real browser')</script>\"\nvulnerable_html = f\"<div class='comment'>{user_comment}</div>\"\nprint(vulnerable_html)\nprint(\"if a real browser rendered this HTML, the <script> tag would EXECUTE,\")\nprint(\"not just display as text -- this is the core XSS mechanism OWASP describes\")", note: "This only builds and PRINTS a string -- it is never rendered in an actual browser, keeping this example completely safe. The point is illustrating the exact mechanism: unescaped user input inserted directly into HTML lets a script tag become genuinely executable code in a real page, not just displayed text."},
      {code: "import html\n\n# The FIX: output encoding -- convert special characters to their safe HTML entity form\nsafe_html = f\"<div class='comment'>{html.escape(user_comment)}</div>\"\nprint(safe_html)\nprint(\"the < and > characters are now &lt; and &gt; -- a browser displays this\")\nprint(\"as the LITERAL TEXT of the script tag, not as an executable script\")", note: "Python's built-in html.escape() converts dangerous characters (<, >, &, quotes) into their HTML-entity equivalents -- exactly OWASP's documented output-encoding defense. A browser rendering this encoded version would show the user's comment as harmless, literal, displayed TEXT (including the literal characters '<script>'), never executing it as code."}
    ],
    warn: "Never inject test XSS payloads into a real, live website you don't own or have explicit authorization to test — even a 'harmless' alert() payload against an unauthorized target is a genuine violation. These examples only build Python strings and never touch a real browser or live site.",
    mistakes: ["Encoding output in only SOME places where user input is displayed, missing others — XSS defenses need to be applied consistently everywhere untrusted data reaches the page, not just the obvious spots.","Relying purely on input validation (blocking specific characters at input time) instead of output encoding — OWASP recommends BOTH, but output encoding at the point of display is the more reliable, defense-in-depth layer.","Confusing STORED XSS's severity — since the malicious script is saved and served to every future visitor, it's generally considered more dangerous than reflected XSS, which requires tricking one specific victim into clicking a crafted link."],
    handsOn: "Run both examples and confirm the encoded version's special characters are converted to their safe entity form. Then take a piece of code (yours or an example) that inserts a variable into an HTML string, and add html.escape() (or your language/framework's equivalent) around the user-supplied part.",
    doneWhen: "You can explain what XSS is, distinguish reflected/stored/DOM-based XSS conceptually, and have demonstrated output encoding as a defense with real code.",
    checks: [
      {q: "Why does converting < and > to &lt; and &gt; (output encoding) prevent a malicious <script> tag from executing in a browser?", a: "A browser interprets &lt; and &gt; as the literal characters '<' and '>' to DISPLAY, not as HTML tag delimiters — so an encoded <script> tag renders as visible text reading '<script>...' rather than being parsed and executed as an actual script element."}
    ],
    keyTakeaways: ["XSS happens when malicious script is injected into a trusted page and the victim's browser executes it as if it were legitimate.", "Reflected, stored, and DOM-based XSS differ in how the malicious script reaches the victim's browser.", "Output encoding (converting special characters to safe entities) is OWASP's primary defense, applied consistently everywhere untrusted data is displayed."],
    resources: [
      {label: "OWASP — Cross Site Scripting (XSS)", url: "https://owasp.org/www-community/attacks/xss/", kind: "docs"},
      {label: "OWASP — XSS Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html", kind: "docs"}
    ]
  },
  {
    id: "cyber-auth-secrets", title: "Authentication basics and secrets hygiene",
    concept: "Passwords should NEVER be stored in plain text — a breach of a plaintext password database exposes every user's real password immediately. Instead, passwords are stored as a HASH (a one-way transformation) using a purpose-built, SLOW password-hashing algorithm (like bcrypt or Argon2) — deliberately slow to make brute-force guessing computationally expensive, unlike a fast general-purpose hash (like MD5 or plain SHA-256), which is a common and serious mistake. Separately, SECRETS (API keys, database passwords) must never be committed to source control — exactly the discipline this very Forage platform follows, and the same idea from the AI Engineer and Full-Stack paths' deployment lessons, now framed as a security fundamental.",
    analogy: "Storing plaintext passwords is like a hotel keeping a paper list of every guest's actual door key taped to the front desk — anyone who breaches the desk instantly has every key. Password HASHING is like the hotel instead keeping a record that can verify 'yes, this matches the key we issued' without ever storing a literal copy of the key itself — even if that verification record leaks, it doesn't hand over anyone's actual key. Using a SLOW hashing algorithm is like making each verification check take a full second on purpose — trivial for one genuine login attempt, but brutally expensive for someone trying millions of guesses.",
    examples: [
      {code: "import hashlib\nimport time\n\n# Why a FAST hash (like plain SHA-256) is a bad choice for passwords\npassword = \"hunter2\"\nstart = time.perf_counter()\nfor _ in range(100_000):\n    hashlib.sha256(password.encode()).hexdigest()\nelapsed = time.perf_counter() - start\nprint(f\"100,000 SHA-256 hashes took {elapsed*1000:.1f} ms\")\nprint(\"this speed is exactly what makes fast hashes BAD for passwords --\")\nprint(\"an attacker with a stolen hash database can try millions of guesses per second\")", note: "SHA-256 is a fine, fast, general-purpose hash for things like file integrity checks -- but that SAME speed is a liability for passwords, since it lets an attacker brute-force guess passwords against a stolen hash database extremely quickly. This measured speed is the concrete, numeric reason purpose-built slow password hashes exist."},
      {code: "# bcrypt is DELIBERATELY slow -- a genuine security feature, not a performance bug\n# (illustrative pattern -- the 'bcrypt' package would need installing to actually run this)\nbcrypt_example = \"\"\"\nimport bcrypt\n\nhashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())\n# Verifying a login attempt:\nis_correct = bcrypt.checkpw(attempted_password.encode(), hashed)\n\"\"\"\nprint(bcrypt_example)\nprint(\"bcrypt.gensalt() also adds a random SALT per password, so even two users\")\nprint(\"with the IDENTICAL password get completely different stored hashes --\")\nprint(\"defeating precomputed 'rainbow table' lookup attacks\")", note: "This is a WORKED PATTERN illustrating the correct real-world API shape (not executed here, since it needs the bcrypt package installed) -- the two properties that matter are DELIBERATE SLOWNESS (unlike SHA-256's speed) and per-password SALTING, both purpose-built defenses against different attack strategies (brute-force and precomputed lookup tables, respectively)."}
    ],
    warn: "Never store real passwords, API keys, or other credentials in plain text in code, databases, or version control — even in a 'private' repository or a project you consider low-stakes. This applies to every project you ever build, not just ones explicitly labeled as security-sensitive.",
    mistakes: ["Using a fast, general-purpose hash (MD5, plain SHA-1/SHA-256) for passwords instead of a purpose-built slow algorithm (bcrypt, Argon2, scrypt) — a genuinely common and serious real-world mistake.","Storing passwords without a per-password salt — without one, identical passwords produce identical hashes, letting an attacker use precomputed lookup tables to crack many accounts at once.","Committing a .env file or hardcoded API key/database password to a git repository, even briefly — once committed, it typically remains in the repository's history even after being 'removed' in a later commit."],
    handsOn: "Run the SHA-256 timing example and note how fast 100,000 hashes complete — that speed is precisely the vulnerability. Then research (via the bcrypt documentation linked below) what a 'work factor' or 'cost parameter' controls in bcrypt, and explain in one sentence why it's tunable over time.",
    doneWhen: "You can explain why passwords need slow, purpose-built hashing (not fast general-purpose hashes), what a salt defends against, and can state the secrets-in-source-control rule.",
    checks: [
      {q: "Why is a fast hash algorithm like SHA-256 a poor choice for storing passwords, even though it's a legitimate, secure hash function for other uses?", a: "SHA-256's speed, while fine for things like file integrity checks, becomes a liability for passwords — an attacker with a stolen hash database can compute millions of guesses per second against it. Purpose-built password hashes (bcrypt, Argon2) are deliberately slow, making large-scale guessing computationally expensive."}
    ],
    keyTakeaways: ["Passwords must be hashed with a slow, purpose-built algorithm (bcrypt/Argon2), never stored in plain text or hashed with a fast general-purpose hash.", "A per-password salt defeats precomputed lookup-table attacks by ensuring identical passwords produce different hashes.", "Secrets (API keys, DB passwords) must never be committed to source control, in any repository, regardless of perceived stakes."],
    resources: [
      {label: "OWASP — Password Storage Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html", kind: "docs"},
      {label: "bcrypt — Python package documentation", url: "https://pypi.org/project/bcrypt/", kind: "docs"}
    ]
  }
  ]
};
