// FORAGE — Data Scientist path, Module 3: ML for Analysts, Storytelling & Capstone
// scikit-learn facts consistent with the AI Engineer path (same verified 1.9.0 environment),
// framed from a DATA-ANALYST perspective (when/why to reach for ML) rather than duplicating the
// AI Engineer path's modeling depth. Every code snippet executed for real. Capstone lessons are
// project-based and correctly get 0 quizzes per the light-quiz rule.

module.exports = {
  id: "data-ml-storytelling", title: "ML for Analysts, Storytelling & Capstone",
  why: "Modules 1-2 gave you the statistical and data-wrangling foundation. This module adds two final pieces: knowing WHEN a simple statistical answer beats a machine learning model (a genuine analyst judgment call), and turning findings into a story a non-technical stakeholder actually acts on — then a capstone tying the whole path together.",
  topics: [
  {
    id: "data-ml-vs-stats", title: "When to reach for ML — and when not to",
    concept: "Not every data question needs machine learning. If you need to explain WHY something happens with a clear, interpretable relationship (e.g. 'each additional year of experience predicts $2,000 more salary'), a simple statistical model (like linear regression, Module 1's correlation ideas extended) is often both sufficient AND more honest about its own limits than a complex ML model would be. Reach for ML specifically when the relationship is genuinely complex/non-linear AND prediction accuracy matters more than interpretability — the AI Engineer path's Module 3 covers the how; this lesson covers the analyst's judgment call of whether to.",
    analogy: "Using a complex ML model to answer 'does more marketing spend correlate with more sales' is like hiring a forensic accountant to check if a store's total register matches its receipts — technically capable, but a much simpler tool (a straightforward correlation or basic regression) already answers the question clearly, and answers it in a way you can actually EXPLAIN to your manager in one sentence.",
    examples: [
      {code: "import numpy as np\nfrom scipy import stats\nfrom sklearn.linear_model import LinearRegression\n\nnp.random.seed(0)\nexperience = np.random.uniform(0, 15, 200)\nsalary = 40000 + experience * 2500 + np.random.normal(0, 5000, 200)\n\n# A simple, interpretable answer: correlation + linear regression\ncorr = np.corrcoef(experience, salary)[0, 1]\nmodel = LinearRegression().fit(experience.reshape(-1, 1), salary)\nprint(f\"correlation: {corr:.3f}\")\nprint(f\"each extra year of experience predicts +${model.coef_[0]:,.0f} salary\")\nprint(\"this ONE sentence is a complete, honest, explainable answer\")", note: "A strong linear correlation (this data was designed with a real linear relationship) means a simple linear regression genuinely captures the pattern well -- and its single coefficient translates directly into a plain-English business sentence, something a complex model's internals rarely offer as cleanly."},
      {code: "# When the relationship is NOT simple/linear, a linear model genuinely underperforms\nnp.random.seed(0)\nx_nonlinear = np.random.uniform(-3, 3, 200)\ny_nonlinear = x_nonlinear**2 * 10 + np.random.normal(0, 3, 200)   # a real U-shaped pattern\n\nlinear_corr = np.corrcoef(x_nonlinear, y_nonlinear)[0, 1]\nprint(f\"linear correlation on U-shaped data: {linear_corr:.3f}\")\nprint(\"a near-zero correlation here does NOT mean 'no relationship' --\")\nprint(\"it means no LINEAR relationship; a U-shape needs a different tool (e.g. a tree-based model)\")", note: "This demonstrates a genuine limitation of relying purely on linear correlation: a clear, strong U-shaped relationship can still show a correlation coefficient near 0, because correlation only measures LINEAR association -- exactly the moment where reaching for a more flexible model (or at minimum, a different statistical approach) becomes the right call, not a linear one."}
    ],
    mistakes: ["Reaching for a complex model by default, when a simple, interpretable statistic would answer the actual business question just as well (and more transparently).","Concluding 'no relationship' from a low correlation without checking whether the TRUE relationship might be non-linear (as the U-shaped example shows).","Optimizing purely for prediction accuracy when the actual stakeholder need is understanding WHY — the two goals sometimes call for different tools."],
    handsOn: "Run both examples and confirm the linear case gives a clean, high correlation and interpretable coefficient, while the U-shaped case gives a near-zero correlation despite an obviously real relationship. Write one sentence describing a real business question where a simple stat would be the RIGHT choice, and one where you'd genuinely want ML instead.",
    doneWhen: "You can articulate when a simple statistical approach is the better choice versus when ML is genuinely warranted, and have demonstrated correlation's blind spot for non-linear relationships with real code.",
    checks: [
      {q: "A dataset shows a near-zero linear correlation between two variables. Does this prove there's no meaningful relationship between them?", a: "No — correlation only measures LINEAR association. A strong non-linear relationship (like a U-shape) can produce a near-zero correlation coefficient while a real, meaningful relationship clearly exists — always visualize the data (or consider non-linear methods) before concluding 'no relationship.'"}
    ],
    keyTakeaways: ["A simple, interpretable statistic is often the RIGHT choice when explainability matters more than squeezing out extra predictive accuracy.", "Reach for ML when the relationship is genuinely complex/non-linear and raw predictive accuracy is the priority.", "Low correlation doesn't mean 'no relationship' — it means no LINEAR relationship; non-linear patterns can hide from correlation entirely."],
    resources: [
      {label: "scikit-learn — Choosing the right estimator (map)", url: "https://scikit-learn.org/stable/machine_learning_map.html", kind: "docs"},
      {label: "scikit-learn — LinearRegression docs", url: "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html", kind: "docs"}
    ]
  },
  {
    id: "data-ml-tabular-business", title: "A minimal ML model for business data",
    concept: "When ML genuinely IS the right call (last lesson), a data scientist's most common task is a straightforward tabular prediction: given some business features (customer attributes, transaction details), predict an outcome (will they churn? is this transaction fraudulent?). This lesson applies the AI Engineer path's classical ML pattern (fit/predict/evaluate) to a realistic BUSINESS framing — customer churn prediction — with an emphasis on connecting the model's output back to a business DECISION, not just a raw accuracy number.",
    analogy: "A churn model is like a doctor's risk assessment: the point isn't the raw probability number itself, but what ACTION it triggers — a high-risk patient (or high-churn-risk customer) gets proactive outreach before it's too late. The model is only useful insofar as its output changes what someone actually DOES.",
    examples: [
      {code: "import numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import classification_report\n\nnp.random.seed(0)\nn = 500\nmonths_active = np.random.uniform(1, 36, n)\nsupport_tickets = np.random.poisson(2, n)\nmonthly_spend = np.random.uniform(10, 200, n)\n\n# Churn risk rises with more support tickets and shorter tenure, falls with higher spend\nchurn_score = -0.15*months_active + 0.8*support_tickets - 0.01*monthly_spend + np.random.normal(0, 2, n)\nchurned = (churn_score > np.percentile(churn_score, 75)).astype(int)   # top 25% = churned\n\nX = np.column_stack([months_active, support_tickets, monthly_spend])\nXtr, Xte, ytr, yte = train_test_split(X, churned, test_size=0.3, random_state=42, stratify=churned)\n\nmodel = LogisticRegression().fit(Xtr, ytr)\nprint(classification_report(yte, model.predict(Xte), target_names=[\"stayed\", \"churned\"]))", note: "This mirrors the AI Engineer path's classification pattern (Module 3/4) exactly -- fit/predict/evaluate -- but framed around a genuine business scenario: predicting customer churn from tenure, support tickets, and spend. classification_report gives precision/recall per class, connecting straight back to Module 1's evaluation concepts."},
      {code: "# Connecting the model back to a BUSINESS decision, not just a metric\nrisk_scores = model.predict_proba(Xte)[:, 1]      # probability of churning\nhigh_risk_threshold = 0.5\nhigh_risk_customers = (risk_scores > high_risk_threshold).sum()\nprint(f\"{high_risk_customers} of {len(Xte)} test customers flagged as high churn risk\")\nprint(\"business action: proactively reach out to these customers with a retention offer\")\nprint(\"this connects the model's OUTPUT directly to a concrete business DECISION\")", note: "The model's raw probability output only becomes useful once it's tied to an actual action (outreach to high-risk customers) -- this is the analyst's real job: not just building a model, but connecting its predictions to a concrete business decision that changes what someone does."}
    ],
    mistakes: ["Stopping at a model's accuracy/precision numbers without connecting the prediction to a real business action — a model nobody acts on has zero business value regardless of its metrics.","Choosing a threshold (like 0.5) without considering the actual COST of false positives vs false negatives for the business (e.g. an unnecessary retention offer vs a missed at-risk customer) — the right threshold often isn't the default.","Building a churn/prediction model without first checking whether a simpler analysis (like the last lesson's correlation approach) would already answer the real question."],
    handsOn: "Run both examples and confirm the classification report and business-framed output. Then adjust high_risk_threshold to 0.3 and 0.7, and observe how the number of flagged customers changes — write one sentence about which threshold you'd recommend and why, considering the real-world cost of a false positive (unnecessary offer) versus a false negative (missed at-risk customer).",
    doneWhen: "You can apply a classification model to a business scenario, connect its output to a concrete decision, and reason about threshold tradeoffs in business terms.",
    checks: [
      {q: "Why is a churn prediction model's raw accuracy number not the actual measure of its business value?", a: "A model's value comes from the ACTIONS its predictions enable (e.g. proactive outreach to at-risk customers) — a highly accurate model that nobody acts on has no business value, while connecting predictions to a concrete decision is what actually matters."}
    ],
    keyTakeaways: ["A business ML model's value comes from the decisions/actions its predictions enable, not the raw metric alone.", "The classification threshold should reflect the real business cost of false positives vs false negatives, not just default to 0.5.", "Always check whether a simpler statistical approach would already answer the real business question before reaching for ML."],
    resources: [
      {label: "scikit-learn — classification_report documentation", url: "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html", kind: "docs"},
      {label: "AI Engineer path — Model Evaluation module (deeper metrics coverage)", url: "/learn/aiml-confusion-matrix", kind: "course"}
    ]
  },
  {
    id: "data-storytelling", title: "Data storytelling — communicating to non-technical stakeholders",
    concept: "The best analysis is worthless if it doesn't change a decision — and most stakeholders are NOT data scientists. Effective data storytelling means leading with the SO-WHAT (the recommendation/insight), not the methodology; using ONE clear chart per point rather than a dense dashboard; and translating statistical language into plain business language ('customers with 3+ support tickets are twice as likely to churn' beats 'the coefficient on support_tickets was statistically significant at p<0.05').",
    analogy: "Presenting raw statistical output to a business stakeholder is like handing someone a car's full diagnostic computer log when they just asked 'is my car safe to drive to work tomorrow?' — technically all the information is there, but it answers a different question than the one being asked. Good data storytelling translates the diagnostic log into 'yes, safe to drive; the brake pads will need replacing within a month' — the actual decision-relevant answer.",
    examples: [
      {code: "# BAD: leads with methodology, uses statistical jargon\nbad_summary = \"\"\"\nWe ran a logistic regression with 3 features (months_active, support_tickets,\nmonthly_spend). The coefficient on support_tickets was 0.8 with p < 0.001.\nThe model achieved 78% precision and 71% recall on the held-out test set.\n\"\"\"\n\n# GOOD: leads with the decision-relevant insight, plain language\ngood_summary = \"\"\"\nCustomers who contact support 3+ times are roughly twice as likely to churn.\nRecommendation: flag customers after their 3rd support ticket for a retention\ncall. Based on our model, this would catch about 100 of the ~125 customers\nwho are likely to churn each month.\n\"\"\"\nprint(bad_summary)\nprint(good_summary)", note: "Same underlying analysis, two very different presentations -- the GOOD version leads with the actionable insight and a concrete recommendation in plain language, saving the methodology (available on request) for anyone who wants to dig deeper. This is the difference between a report that gets read and acted on, versus one that gets skimmed and shelved."},
      {code: "# One clear chart beats a dense dashboard -- illustrating the PRINCIPLE, not literal plotting code\nchart_principle = \"\"\"\nInstead of: a 12-panel dashboard with every possible metric\nDo: ONE bar chart showing churn rate by support-ticket-count bucket,\n    with the key threshold (3+ tickets) visually highlighted\n\nEach chart should answer ONE question clearly, titled with the INSIGHT\n(e.g. 'Churn risk doubles after 3 support tickets'), not a generic label\nlike 'Churn Rate by Support Tickets' that makes the reader do the work\nof finding the point themselves.\n\"\"\"\nprint(chart_principle)", note: "This is a WORKED PRINCIPLE, not literal runnable plotting code -- the key idea (titling a chart with the INSIGHT rather than a generic description) is a small change that measurably improves how well a chart communicates on its own, without requiring the viewer to interpret it themselves."}
    ],
    mistakes: ["Leading a report/presentation with methodology (what model, what test) instead of the actual finding and recommendation — most stakeholders care about the SO-WHAT, not the HOW.","Using statistical jargon (p-values, coefficients, precision/recall) with a non-technical audience without translating it into a plain business statement first.","Presenting many charts/metrics at once instead of the ONE chart that best supports the specific decision being made — more information isn't automatically more persuasive or useful."],
    handsOn: "Take a finding from any earlier lesson in this module (or your own past analysis) and write BOTH a 'bad' technical-jargon version and a 'good' plain-language, recommendation-led version, following the pattern above.",
    doneWhen: "You can translate a technical finding into a plain-language, recommendation-led summary that a non-technical stakeholder could act on immediately.",
    checks: [
      {q: "Why should a data analysis summary for a non-technical stakeholder lead with the recommendation rather than the methodology?", a: "Most stakeholders care about what decision or action the finding supports (the 'so-what'), not the technical details of how it was derived — leading with methodology risks losing the actual point, while methodology can always be provided for anyone who wants to dig deeper."}
    ],
    keyTakeaways: ["Lead with the recommendation/insight (the 'so-what'), not the methodology.", "Translate statistical language into plain business language for non-technical audiences.", "One clear, insight-titled chart per point beats a dense dashboard of many metrics."],
    resources: [
      {label: "Storytelling with Data — book & blog (Cole Nussbaumer Knaflic)", url: "https://www.storytellingwithdata.com/", kind: "book"},
      {label: "Harvard Business Review — Data Storytelling framework", url: "https://hbr.org/2018/07/how-to-tell-a-story-with-data", kind: "reference"}
    ]
  },
  {
    id: "data-capstone", title: "Capstone: end-to-end analysis and write-up",
    concept: "Your capstone: pick a real, publicly available dataset (Kaggle, government open data, or one relevant to your interests) and run a genuine end-to-end analysis: explore the data (Module 1's stats), pull/join/aggregate as needed (Module 2's SQL/pandas), check correlations and consider whether a simple stat or ML model fits (this module's lessons 1-2), and produce a stakeholder-facing write-up (this module's lesson 3) — a one-page summary with a clear recommendation, not a code notebook dump.",
    analogy: "This capstone is the difference between a chef's messy kitchen prep (all the real work, but not what's served) and the actual finished plate that goes out to the table. Both matter, but only the finished plate — the clear, decision-ready write-up — is what an interviewer or stakeholder actually evaluates you on.",
    examples: [
      {code: "# A worked skeleton for the capstone's final write-up structure\nwriteup_skeleton = \"\"\"\n1. THE QUESTION (1-2 sentences)\n   What business/real-world question does this analysis answer?\n\n2. THE FINDING (2-3 sentences, plain language, Module 3.3's storytelling lesson)\n   What did you discover? Lead with the insight, not the method.\n\n3. THE RECOMMENDATION (1-2 sentences)\n   What should someone DO based on this finding?\n\n4. THE EVIDENCE (a few key numbers/one clear chart)\n   The minimum supporting detail needed to trust the finding.\n\n5. METHODOLOGY (available but NOT leading -- for anyone who wants to dig in)\n   What data, what approach (simple stats vs ML, and why you chose it), what\n   you'd improve with more time or data.\n\"\"\"\nprint(writeup_skeleton)", note: "This is a WORKED STRUCTURE, not a template to fill in mechanically -- the ordering itself is the point: finding and recommendation FIRST (what a reader actually needs), methodology LAST (for those who want it), mirroring exactly the storytelling lesson's core principle applied to a real deliverable."}
    ],
    mistakes: ["Submitting a raw notebook as the 'deliverable' instead of a clear write-up — the analysis work and the COMMUNICATION of it are both real skills, and only the second one is directly visible to most evaluators.","Picking a dataset with no genuine question worth answering — a strong capstone starts from a real question, not from 'I found a dataset and did some things to it.'","Skipping the 'what I'd improve' honesty in methodology — acknowledging real limitations is a sign of genuine analytical maturity, not weakness."],
    handsOn: "Choose a real dataset and question, run the full analysis pipeline (explore, wrangle, test correlation/simple-stats-vs-ML judgment, evaluate), and write the final one-page summary following the skeleton above. Then rehearse presenting your finding and recommendation out loud in under 2 minutes, without reading from notes.",
    doneWhen: "You have a complete end-to-end analysis with a clear, recommendation-led one-page write-up, and can present the finding fluently in under 2 minutes.",
    checks: [],
    keyTakeaways: ["A capstone's deliverable is a clear, decision-ready write-up, not a raw notebook.", "Lead the write-up with the finding and recommendation; methodology comes last, for those who want it.", "A strong capstone starts from a genuine question, not from 'I found a dataset and did some things.'"],
    resources: [
      {label: "Kaggle — Datasets", url: "https://www.kaggle.com/datasets", kind: "practice"},
      {label: "Common Core — Career track (interview framing)", url: "/stream/common-core", kind: "course"},
      {label: "Forage Interview — practice presenting this analysis live", url: "/interview", kind: "practice"}
    ]
  }
  ]
};
