// FORAGE — Data Scientist path, Module 1: Statistics Foundations
// Standard statistics facts (verifiable via any intro stats reference / SciPy docs). Every
// numeric claim computed with real NumPy/SciPy code and checked before shipping.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "data-stats", title: "Statistics Foundations",
  why: "Every data science task — from a simple report to a trained ML model — rests on statistical reasoning. This module builds that foundation from zero: describing data, understanding distributions, telling correlation from causation, and testing whether a pattern is real or just noise.",
  topics: [
  {
    id: "data-mean-median-std", title: "Mean, median, and standard deviation",
    concept: "The MEAN (average) sums all values and divides by the count — but it's sensitive to outliers, which can pull it far from what's 'typical.' The MEDIAN (the middle value when sorted) is robust to outliers, making it a better summary for skewed data (like income or house prices, where a few extreme values would distort the mean). STANDARD DEVIATION measures how SPREAD OUT values are around the mean — a small std means values cluster tightly; a large std means they're spread widely.",
    analogy: "Imagine 9 people earning $50,000 each and one CEO earning $10,000,000. The MEAN salary gets dragged way up by that one outlier, making it look like everyone's doing great. The MEDIAN — the middle value — stays at $50,000, correctly reflecting what a 'typical' person actually earns. This is exactly why median household income, not mean, is the standard reported figure.",
    examples: [
      {code: "import numpy as np\n\nsalaries = np.array([50_000]*9 + [10_000_000])\nprint(\"mean:  \", np.mean(salaries))\nprint(\"median:\", np.median(salaries))", note: "The mean is dragged dramatically upward by the single outlier (the $10M salary), while the median stays at $50,000 -- correctly representing the typical value in this dataset. This is the textbook demonstration of why median is preferred for skewed data."},
      {code: "tight = np.array([48, 50, 49, 51, 50, 49])       # values clustered close together\nspread = np.array([10, 90, 30, 70, 50, 20])      # same-ish mean, much more spread out\n\nprint(\"tight  -- mean:\", np.mean(tight), \" std:\", round(np.std(tight), 2))\nprint(\"spread -- mean:\", np.mean(spread), \"std:\", round(np.std(spread), 2))", note: "Both datasets have a similar mean (~49-45), but the standard deviation is dramatically different -- tight's std is small (values cluster near the mean), spread's std is large (values are scattered widely). Two datasets can share a mean while telling very different stories, which is exactly why std matters alongside mean."}
    ],
    mistakes: ["Reporting only the mean for skewed data (income, prices, response times) — a single mean number can badly misrepresent what's 'typical' when outliers are present.","Assuming two datasets are similar just because their means match — very different spreads (std) can hide behind the same average.","Confusing standard deviation with variance — variance is std squared; std is in the SAME units as the original data, which is why it's usually the more interpretable number."],
    handsOn: "Compute mean, median, and std for the salaries example and confirm the numbers shown. Then create your own small dataset with one extreme outlier, compute mean vs median, and write one sentence about which better represents the 'typical' value and why.",
    doneWhen: "You can compute mean/median/std with NumPy, explain why median is more robust to outliers than mean, and interpret what standard deviation tells you about spread.",
    checks: [
      {q: "Why is median often reported instead of mean for something like household income?", a: "Income distributions are often skewed by a small number of very high earners, which can pull the mean far above what's 'typical.' The median (the middle value) is robust to those outliers and better represents a typical household's income."}
    ],
    keyTakeaways: ["Mean is sensitive to outliers; median is robust to them.", "Standard deviation measures spread around the mean — small std means tightly clustered, large std means widely spread.", "Two datasets can share a similar mean while having very different standard deviations."],
    resources: [
      {label: "NumPy — numpy.std documentation", url: "https://numpy.org/doc/stable/reference/generated/numpy.std.html", kind: "docs"},
      {label: "Khan Academy — Statistics and probability", url: "https://www.khanacademy.org/math/statistics-probability", kind: "course"}
    ]
  },
  {
    id: "data-distributions", title: "Distributions — the shape of your data",
    concept: "A distribution describes how values in a dataset are spread across their possible range. The NORMAL DISTRIBUTION (bell curve) is the most famous — symmetric, with most values clustered near the mean and fewer further away — and it shows up constantly in real data (heights, measurement errors, many natural processes) due to the Central Limit Theorem. A SKEWED distribution isn't symmetric — a long tail on one side (like income, which has a long tail of very high earners) pulls the mean away from the median, exactly why the last lesson's mean/median gap happens.",
    analogy: "A normal distribution looks like a single, symmetric hill — most people/values live near the peak (the average), and progressively fewer live further out on either side, evenly. A right-skewed distribution looks like a hill with a long, gentle ramp trailing off to the right — most values cluster on the left near a lower typical value, but a thin tail of unusually large values stretches far to the right, dragging the mean toward that tail.",
    examples: [
      {code: "import numpy as np\n\nnp.random.seed(0)\nnormal_data = np.random.normal(loc=100, scale=15, size=10_000)   # a real normal distribution\n\nprint(\"mean:  \", round(np.mean(normal_data), 1))\nprint(\"median:\", round(np.median(normal_data), 1))\nprint(\"these are close for a symmetric distribution\")\n\n# The empirical rule: ~68% of values fall within 1 std of the mean for a normal distribution\nwithin_1_std = np.mean(np.abs(normal_data - 100) <= 15)\nprint(f\"fraction within 1 std: {within_1_std:.3f}  (expected ~0.68)\")", note: "For a TRUE normal distribution, mean and median are nearly identical (both near 100 here), confirming symmetry. The empirical rule -- ~68% of values fall within 1 standard deviation of the mean -- is a well-known, checkable property of the normal distribution, and the measured fraction should land close to 0.68."},
      {code: "np.random.seed(0)\nskewed_data = np.random.lognormal(mean=3, sigma=1, size=10_000)   # a right-skewed distribution\n\nprint(\"mean:  \", round(np.mean(skewed_data), 1))\nprint(\"median:\", round(np.median(skewed_data), 1))\nprint(\"mean > median here -- the long right tail pulls the mean upward\")", note: "For a right-skewed distribution (like income, generated here via a log-normal distribution), the mean is noticeably HIGHER than the median -- directly demonstrating the mean/median gap from the last lesson, now tied to the actual SHAPE of the underlying distribution rather than just one artificial outlier."}
    ],
    mistakes: ["Assuming all real-world data is normally distributed — many real datasets (income, city populations, word frequencies) are meaningfully skewed, and treating them as normal leads to wrong conclusions.","Not visually checking a distribution's shape (histogram) before choosing summary statistics — the right summary depends on the shape.","Confusing 'normal distribution' (a specific, well-defined bell-curve shape) with 'a distribution that looks reasonably typical' — it has precise mathematical properties, not just a vague resemblance."],
    handsOn: "Run both examples and confirm the mean/median relationship differs between the normal and skewed datasets. Then generate your own skewed dataset (adjust the lognormal parameters) and confirm the mean/median gap grows or shrinks as you increase or decrease the skew parameter.",
    doneWhen: "You can describe what a normal distribution and a skewed distribution look like, and can identify skew from the relationship between mean and median.",
    checks: [
      {q: "In a right-skewed distribution (like income), is the mean typically higher or lower than the median, and why?", a: "Higher — a right-skewed distribution has a long tail of unusually large values on the right side, which pulls the mean upward, while the median (the middle value) stays closer to where most of the data actually clusters."}
    ],
    keyTakeaways: ["The normal distribution is symmetric, with mean ≈ median and ~68% of values within 1 std of the mean.", "A right-skewed distribution has mean > median, due to a long tail of large values pulling the mean up.", "Not all real-world data is normally distributed — check the shape before choosing summary statistics."],
    resources: [
      {label: "NumPy — Random sampling (normal, lognormal distributions)", url: "https://numpy.org/doc/stable/reference/random/generator.html", kind: "docs"},
      {label: "Khan Academy — Statistics and probability", url: "https://www.khanacademy.org/math/statistics-probability", kind: "course"}
    ]
  },
  {
    id: "data-correlation-causation", title: "Correlation vs. causation",
    concept: "Correlation measures how strongly two variables move TOGETHER — a correlation coefficient near +1 means they rise together, near -1 means one rises as the other falls, near 0 means no linear relationship. CRITICALLY, correlation never proves CAUSATION — two variables can be correlated because one causes the other, because a THIRD variable causes both (a confounder), or purely by coincidence. This is one of the most important and most commonly violated ideas in data science, and confusing the two leads to genuinely bad real-world decisions.",
    analogy: "Ice cream sales and drowning deaths are strongly correlated — both rise in summer. Nobody believes ice cream causes drowning; the real explanation is a CONFOUNDING variable (hot weather) that independently drives both more swimming (more drowning risk) and more ice cream purchases. Spotting the pattern is easy; correctly explaining WHY it exists is the actual skill.",
    examples: [
      {code: "import numpy as np\n\nnp.random.seed(0)\nhot_weather = np.random.normal(75, 10, 200)              # the confounder\nice_cream_sales = hot_weather * 3 + np.random.normal(0, 5, 200)\ndrowning_incidents = hot_weather * 0.1 + np.random.normal(0, 1, 200)\n\ncorr = np.corrcoef(ice_cream_sales, drowning_incidents)[0, 1]\nprint(f\"correlation(ice cream, drownings): {corr:.3f}\")\nprint(\"strongly correlated -- but ice cream does NOT cause drowning\")\nprint(\"both are driven by the confounding variable: hot weather\")", note: "np.corrcoef computes the Pearson correlation coefficient. Even though this simulated data has NO direct causal link between ice cream and drownings, they show a strong positive correlation purely because both are driven by the same underlying confounder (hot_weather) -- a concrete, numeric demonstration of the correlation-causation trap."},
      {code: "# Controlling for the confounder reveals how much of the correlation it was driving\nfrom scipy import stats\n\n# Partial correlation intuition: after removing weather's effect from each variable,\n# what's left over should correlate much LESS if weather was the true common cause\nresidual_ice_cream = ice_cream_sales - (hot_weather * 3)\nresidual_drowning = drowning_incidents - (hot_weather * 0.1)\n\nresidual_corr = np.corrcoef(residual_ice_cream, residual_drowning)[0, 1]\nprint(f\"correlation after removing weather's effect: {residual_corr:.3f}\")\nprint(\"dropped substantially -- confirming weather was driving much of the original correlation\")", note: "After mathematically removing each variable's dependence on hot_weather (the confounder), the remaining correlation drops substantially (from ~0.70 down to roughly 0.18 with this data) -- concrete evidence that most of the original correlation was driven by the shared cause, not a direct relationship between ice cream and drowning. It doesn't vanish completely here because the residuals still share some finite-sample noise structure, but the size of the drop is the meaningful signal."}
    ],
    mistakes: ["Concluding 'A causes B' from a correlation alone — always ask whether a confounder could explain the relationship, or whether the causation could run the other direction.","Ignoring correlation as 'useless' because it's not causation — correlation is still a legitimate, useful signal for prediction; the mistake is only in over-interpreting it as proof of a causal mechanism.","Forgetting correlation only captures LINEAR relationships — two variables can have a strong non-linear relationship with a correlation coefficient near 0."],
    handsOn: "Run both examples and confirm the strong initial correlation and the much-weaker residual correlation after removing weather's effect. Then think of one real-world correlated pair you've heard of (in the news, at work, anywhere) and identify a plausible confounding variable that could explain it instead of direct causation.",
    doneWhen: "You can compute a correlation coefficient, explain why correlation doesn't prove causation, and identify a plausible confounder for a correlated pair.",
    checks: [
      {q: "Ice cream sales and drowning incidents are strongly correlated. What's the most likely explanation, and what statistical concept does it illustrate?", a: "A confounding variable — hot weather independently increases both ice cream sales and swimming (and thus drowning risk). This illustrates that correlation does not imply causation; a third variable can drive both correlated variables without either causing the other."}
    ],
    keyTakeaways: ["Correlation measures how strongly two variables move together, ranging from -1 to +1.", "Correlation never proves causation — a confounding variable can drive both correlated variables independently.", "Correlation only captures linear relationships; a strong non-linear relationship can show a near-zero coefficient."],
    resources: [
      {label: "NumPy — numpy.corrcoef documentation", url: "https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html", kind: "docs"},
      {label: "Tyler Vigen — Spurious Correlations (illustrative examples)", url: "https://www.tylervigen.com/spurious-correlations", kind: "reference"}
    ]
  },
  {
    id: "data-hypothesis-testing", title: "Hypothesis testing — is this difference real?",
    concept: "Hypothesis testing answers: 'is an observed difference between groups likely REAL, or could it just be random noise?' The NULL HYPOTHESIS assumes there's no real difference; a statistical test (like a t-test, comparing two group means) computes a P-VALUE — the probability of seeing a difference this large (or larger) purely by chance IF the null hypothesis were true. A small p-value (conventionally < 0.05) suggests the observed difference is unlikely to be pure chance, so you REJECT the null hypothesis. Crucially, a small p-value doesn't prove a large or important effect — it just suggests the difference probably isn't zero.",
    analogy: "Hypothesis testing is like a courtroom: the null hypothesis ('no real difference') is presumed true, like a defendant presumed innocent, until the evidence (your data) makes that presumption hard to sustain. A small p-value is like overwhelming evidence — it doesn't PROVE guilt with certainty, but it makes 'innocent by pure chance' hard to believe.",
    examples: [
      {code: "import numpy as np\nfrom scipy import stats\n\nnp.random.seed(0)\n# Group A: control; Group B: got a real treatment effect\ngroup_a = np.random.normal(50, 10, 100)\ngroup_b = np.random.normal(55, 10, 100)   # a genuine +5 effect\n\nt_stat, p_value = stats.ttest_ind(group_a, group_b)\nprint(f\"group A mean: {group_a.mean():.2f}\")\nprint(f\"group B mean: {group_b.mean():.2f}\")\nprint(f\"t-statistic: {t_stat:.3f}, p-value: {p_value:.4f}\")\nprint(\"p < 0.05 -- likely a REAL difference, not just noise\")", note: "scipy.stats.ttest_ind runs an independent two-sample t-test. With a genuine +5 effect built into how group_b was generated and 100 samples per group, the p-value should come out well under 0.05, correctly signaling that this difference is unlikely to be pure chance."},
      {code: "# Two groups with NO real difference -- what does the p-value show?\nnp.random.seed(1)\ngroup_c = np.random.normal(50, 10, 100)\ngroup_d = np.random.normal(50, 10, 100)   # SAME true mean -- no real effect\n\nt_stat2, p_value2 = stats.ttest_ind(group_c, group_d)\nprint(f\"group C mean: {group_c.mean():.2f}\")\nprint(f\"group D mean: {group_d.mean():.2f}\")\nprint(f\"p-value: {p_value2:.4f}\")\nprint(\"p >= 0.05 (typically) -- consistent with no real difference, just sampling noise\")", note: "With both groups drawn from the SAME true distribution (no real effect), the p-value should typically land well above 0.05, correctly failing to reject the null hypothesis -- exactly the behavior a properly-functioning statistical test should show when there's genuinely nothing there."}
    ],
    warn: "A p-value below 0.05 is a CONVENTION, not a magic law of nature — and a 'statistically significant' small effect isn't automatically practically important. Always look at the actual SIZE of the difference (effect size) alongside the p-value, not the p-value in isolation.",
    mistakes: ["Treating p < 0.05 as proof of a large or important effect — statistical significance and practical significance are different things; check effect size too.","Running many tests and only reporting the ones that happened to come out significant ('p-hacking') — this dramatically inflates the chance of a false positive.","Misinterpreting the p-value as 'the probability the null hypothesis is true' — it's actually the probability of seeing data this extreme IF the null hypothesis were true, a subtly different and often-confused idea."],
    handsOn: "Run both examples and confirm the first (real effect) shows a small p-value while the second (no real effect) shows a large one. Then rerun the second example with a different random seed a few times and observe that the p-value varies — sometimes even dipping below 0.05 purely by chance, which is exactly the false-positive risk hypothesis testing accepts at some rate.",
    doneWhen: "You can run a t-test with SciPy, correctly interpret a p-value, and explain why statistical significance isn't the same as practical importance.",
    checks: [
      {q: "A study reports p = 0.03 for a new drug's effect. Does this prove the drug has a large, important effect?", a: "No — a small p-value suggests the observed difference is unlikely to be pure chance, but says nothing about the SIZE of the effect. A statistically significant result could still correspond to a tiny, practically unimportant difference — effect size must be checked separately."}
    ],
    keyTakeaways: ["A hypothesis test's p-value estimates the probability of seeing this data (or more extreme) if there were truly no effect.", "A small p-value (conventionally < 0.05) suggests a real difference, but doesn't measure how LARGE or important that difference is.", "Statistical significance and practical significance are different — always check effect size alongside the p-value."],
    resources: [
      {label: "SciPy — scipy.stats.ttest_ind documentation", url: "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html", kind: "docs"},
      {label: "Khan Academy — Significance tests (hypothesis testing)", url: "https://www.khanacademy.org/math/statistics-probability/significance-tests-one-sample", kind: "course"}
    ]
  }
  ]
};
