// FORAGE — Full-Stack Developer path, Module 1: JavaScript Fundamentals
// Facts verified against MDN's own JavaScript Guide (closures, async/promises). Every code
// snippet run for real with Node.js and output checked before shipping.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "fs-js-fundamentals", title: "JavaScript Fundamentals",
  why: "JavaScript is the one language that runs natively in every browser and, via Node.js, on the server too — it's the thread connecting everything in this path. This module builds real JavaScript fluency from zero, focused on the parts that trip up beginners and matter most for building real apps.",
  topics: [
  {
    id: "fs-js-variables-scope", title: "Variables and scope — let, const, and why var is avoided",
    concept: "Modern JavaScript uses `let` (reassignable) and `const` (cannot be reassigned) for variables, both BLOCK-scoped — they only exist within the `{ }` block they're declared in. The older `var` keyword is FUNCTION-scoped (it leaks out of blocks like if/for into the whole function) and can be redeclared, which causes real, confusing bugs — modern JavaScript style avoids it almost entirely in favor of let/const.",
    analogy: "Think of `var` as a walkie-talkie that broadcasts to the entire building no matter which room you're in — convenient-sounding, but everyone hears everything, causing chaos in a big building. `let`/`const` are like a conversation that stays in the room it started in — once you leave that room (block), the conversation is over, which is exactly the predictability you want in real code.",
    examples: [
      {code: "// var leaks out of blocks -- a classic source of bugs\nif (true) {\n  var leaked = \"I'm visible outside the if-block!\";\n}\nconsole.log(leaked);   // works -- var ignores block boundaries\n\nif (true) {\n  let scoped = \"I'm only visible inside the if-block\";\n}\ntry {\n  console.log(scoped);   // ReferenceError -- let respects block boundaries\n} catch (e) {\n  console.log(\"Error:\", e.message);\n}", note: "var 'leaks' out of the if-block into the surrounding scope -- a real, common source of bugs (you might accidentally reuse a variable name you thought was contained). let correctly throws a ReferenceError once you try to use it outside its block, which is far safer and more predictable."},
      {code: "const x = 5;\ntry {\n  x = 10;               // TypeError -- const cannot be reassigned\n} catch (e) {\n  console.log(\"Error:\", e.message);\n}\n\nconst arr = [1, 2, 3];\narr.push(4);            // this is FINE -- const prevents REASSIGNING the variable,\nconsole.log(arr);        // not mutating the object/array it points to", note: "A common beginner confusion: const does NOT make an array or object immutable -- it only prevents the VARIABLE itself from being reassigned to point at something else. Mutating the contents (like .push()) is still allowed, which is why arr.push(4) succeeds even though arr is const."}
    ],
    mistakes: ["Using `var` out of old habit or copied code — it leaks scope in ways that cause real bugs; default to `const`, use `let` only when reassignment is genuinely needed.","Assuming `const` makes an object/array fully immutable — it only locks the VARIABLE binding, not the object's contents.","Not understanding block scope — a variable declared inside an if/for block with let/const genuinely doesn't exist outside it."],
    handsOn: "Run both examples in Node (or a browser console) and confirm the errors/behavior shown. Then write a small function using a for loop with `let` as the loop variable, and explain in one sentence why `let` (not `var`) is the standard modern choice for loop variables.",
    doneWhen: "You can explain the difference between let/const and var, and correctly predict whether a variable is accessible outside a given block.",
    checks: [
      {q: "Does declaring an array with `const` prevent you from pushing new items into it?", a: "No — const only prevents the VARIABLE from being reassigned to point at a different value; it doesn't make the array's contents immutable. Methods like .push() that mutate the existing array still work fine."}
    ],
    keyTakeaways: ["let and const are block-scoped; var is function-scoped and leaks out of blocks.", "const prevents reassignment of the variable, not mutation of the object/array it points to.", "Modern JavaScript style defaults to const, uses let only when reassignment is needed, and avoids var."],
    resources: [
      {label: "MDN — let", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let", kind: "docs"},
      {label: "MDN — JavaScript Guide: Grammar and types", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types", kind: "docs"}
    ]
  },
  {
    id: "fs-js-functions-closures", title: "Functions and closures",
    concept: "A closure is what MDN's own docs describe as 'a function bundled together with references to its surrounding state' — when a function is defined inside another function, it 'remembers' the variables from that outer scope even after the outer function has finished running. This is what powers common patterns like private counters and callback functions that carry context with them, and it's a genuinely essential concept for understanding React's hooks later in this path.",
    analogy: "A closure is like a backpack a function carries with it wherever it goes, packed with whatever variables existed in its birthplace — even long after that birthplace (the outer function call) has finished and is gone, the function can still reach into its backpack and use what's there.",
    examples: [
      {code: "function makeCounter() {\n  let count = 0;             // 'count' lives in the closure's backpack\n  return function () {\n    count += 1;\n    return count;\n  };\n}\n\nconst counter1 = makeCounter();\nconsole.log(counter1());   // 1\nconsole.log(counter1());   // 2\nconsole.log(counter1());   // 3\n\nconst counter2 = makeCounter();   // a completely separate closure/backpack\nconsole.log(counter2());   // 1 -- starts fresh, independent of counter1", note: "Each call to makeCounter() creates a brand-new 'count' variable and a brand-new closure over it -- counter1 and counter2 are completely independent, each with their own private count that persists between calls, exactly matching MDN's description of a closure remembering its surrounding state."},
      {code: "// Arrow functions -- a shorter function syntax, commonly used in modern JS\nconst square = (x) => x * x;\nconst add = (a, b) => a + b;\n\nconsole.log(square(5));     // 25\nconsole.log(add(3, 4));      // 7\n\n// Arrow functions are especially common as short callbacks\nconst nums = [1, 2, 3, 4];\nconst doubled = nums.map((n) => n * 2);\nconsole.log(doubled);        // [2, 4, 6, 8]", note: "Arrow functions are a concise syntax widely used for short functions and callbacks (like the argument to .map() here) -- functionally similar to a regular function for most everyday purposes, though they also behave differently with 'this' in ways covered later when relevant."}
    ],
    mistakes: ["Assuming all closures created from the same outer function SHARE state — each call to the outer function creates a fresh, independent closure (as counter1 vs counter2 shows).","Confusing closures with a vague 'magic' concept — it's the specific, well-defined behavior of a function remembering the scope it was defined in.","Overusing closures where a simpler approach (like a class or plain object) would be clearer — closures are powerful but not always the most readable choice."],
    handsOn: "Run the counter example and confirm counter1 and counter2 behave independently. Then write your own closure-based function — e.g. a function that returns a function which multiplies its argument by a fixed number set when the outer function was called.",
    doneWhen: "You can explain what a closure is in your own words and have written one that demonstrates a function 'remembering' state from its outer scope.",
    checks: [
      {q: "In the makeCounter example, why does counter2() start at 1 instead of continuing from counter1's count?", a: "Each call to makeCounter() creates a brand-new 'count' variable and a brand-new closure over it — counter1 and counter2 are entirely independent closures, each with their own private state, not sharing anything."}
    ],
    keyTakeaways: ["A closure is a function bundled with references to the scope it was defined in.", "Each call to an outer function creates a fresh, independent closure — they don't share state.", "Closures power common patterns like private state and callbacks that carry context."],
    resources: [
      {label: "MDN — Closures", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures", kind: "docs"},
      {label: "MDN — Arrow function expressions", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions", kind: "docs"}
    ]
  },
  {
    id: "fs-js-array-methods", title: "Array methods — map, filter, reduce",
    concept: "Modern JavaScript favors transforming arrays with dedicated methods over manual for-loops: `.map()` transforms EVERY element into a new array of the same length; `.filter()` keeps only elements that pass a test, producing a shorter (or equal) array; `.reduce()` combines every element into a SINGLE final value (a sum, an object, anything). These three cover the vast majority of everyday array transformations, and chaining them (`.filter().map()`) reads like a clear pipeline of what's happening to the data.",
    analogy: "`.map()` is like sending every item on a conveyor belt through the same machine, one-for-one, and getting a new belt with everything transformed. `.filter()` is a sorting gate that only lets through items meeting a condition, discarding the rest. `.reduce()` is a machine that takes the whole belt and crushes it down into one final result — like weighing an entire batch into a single total.",
    examples: [
      {code: "const prices = [10, 25, 8, 42, 15];\n\nconst withTax = prices.map((p) => p * 1.08);       // same length, each transformed\nconsole.log(withTax.map((p) => Math.round(p * 100) / 100));\n\nconst expensive = prices.filter((p) => p > 15);     // shorter, only matches kept\nconsole.log(expensive);\n\nconst total = prices.reduce((sum, p) => sum + p, 0);   // one final value\nconsole.log(total);", note: "map() returns 5 items (same length as prices), filter() returns only the items > 15 (a shorter array), and reduce() collapses everything into one number (the sum), starting from an initial value of 0. These three distinct SHAPES of output (same-length, filtered, single-value) are the key to knowing which method fits a given task."},
      {code: "// Chaining: filter then map reads like a clear pipeline\nconst products = [\n  { name: \"Widget\", price: 20, inStock: true },\n  { name: \"Gadget\", price: 45, inStock: false },\n  { name: \"Gizmo\", price: 15, inStock: true },\n];\n\nconst availableNames = products\n  .filter((p) => p.inStock)\n  .map((p) => p.name);\n\nconsole.log(availableNames);   // ['Widget', 'Gizmo']", note: "Chaining .filter() then .map() reads almost like a sentence: 'take the products, keep the in-stock ones, then get just their names.' This chained style is idiomatic modern JavaScript and generally considered clearer than an equivalent manual for-loop with an if-check and a push."}
    ],
    mistakes: ["Using `.map()` when you actually want to filter (its length always matches the input) — reach for `.filter()` when you want fewer items out.","Forgetting `.reduce()`'s initial value argument (the `0` above) — omitting it changes behavior in ways that can silently produce wrong results on edge cases like an empty array.","Writing a manual for-loop with a mutable accumulator when a chained `.filter().map()` would be clearer and less error-prone."],
    handsOn: "Run both examples and confirm the outputs. Then, using the products array, write a chained expression that returns the TOTAL price of only the in-stock products (hint: filter, then reduce).",
    doneWhen: "You can correctly choose between map/filter/reduce based on the shape of output needed, and can chain them to express a multi-step transformation clearly.",
    checks: [
      {q: "You need to transform every element of an array into something else, keeping the same number of elements. Which array method fits, and why not the others?", a: ".map() — it always returns a new array of the SAME length, with each element transformed. .filter() would potentially return fewer elements (based on a test), and .reduce() collapses everything into a single value, not an array of the same length."}
    ],
    keyTakeaways: [".map() transforms every element (same length out); .filter() keeps only matching elements (shorter or equal); .reduce() collapses everything into one value.", "Chaining .filter().map() reads as a clear, idiomatic pipeline.", "reduce() needs an initial value to behave correctly on edge cases like an empty array."],
    resources: [
      {label: "MDN — Array.prototype.map()", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map", kind: "docs"},
      {label: "MDN — Array.prototype.reduce()", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce", kind: "docs"}
    ]
  },
  {
    id: "fs-js-async", title: "Async JavaScript — promises and async/await",
    concept: "JavaScript is single-threaded but handles slow operations (network requests, timers) WITHOUT blocking everything else, using an event loop and PROMISES — an object representing a value that will be available LATER (either resolved successfully or rejected with an error). `async`/`await` is modern, cleaner syntax for working with promises: marking a function `async` lets you `await` a promise inside it, pausing that function (but not the whole program) until the promise resolves, making asynchronous code read almost like synchronous code.",
    analogy: "A promise is like a coat-check ticket at a restaurant: you don't wait standing at the counter for your coat (blocking); you get a ticket immediately and go sit down, and the ticket represents a coat that WILL be ready. `await` is like being told 'I'll bring your coat to your table the moment it's ready, and the waiter can serve other tables in the meantime' — everyone else's service (the rest of the program) doesn't have to stop and wait alongside you.",
    examples: [
      {code: "function delay(ms, value) {\n  return new Promise((resolve) => {\n    setTimeout(() => resolve(value), ms);\n  });\n}\n\nasync function main() {\n  console.log(\"starting...\");\n  const result = await delay(100, \"done!\");   // pauses HERE, not the whole program\n  console.log(result);\n}\n\nmain();\nconsole.log(\"this logs BEFORE 'done!' -- main() didn't block the rest of the program\");", note: "Notice the console.log AFTER main() runs and prints BEFORE 'done!' -- calling an async function doesn't pause the surrounding code; only the code INSIDE that async function pauses at each await, while everything else keeps running. This is the core non-blocking behavior async/await provides."},
      {code: "async function fetchUserSafely(id) {\n  try {\n    const user = await delay(50, { id, name: `user-${id}` });\n    console.log(\"got:\", user);\n    return user;\n  } catch (error) {\n    console.log(\"failed:\", error.message);\n    return null;\n  }\n}\n\nfetchUserSafely(42);", note: "try/catch around an await is the standard, correct way to handle a promise that might REJECT (e.g. a failed network request) -- without it, an unhandled rejection can crash or silently break your program, so real async code always needs this error-handling pattern."}
    ],
    mistakes: ["Forgetting `await` before a promise-returning call — you get the Promise OBJECT itself, not its resolved value, a very common beginner bug.","Not wrapping awaited code in try/catch — unhandled promise rejections cause real, often confusing failures in production.","Assuming `await` blocks the ENTIRE program — it only pauses execution within that specific async function; everything else keeps running."],
    handsOn: "Run both examples in Node and confirm the ordering of the log statements matches what's described. Then write your own async function that awaits a delayed value and logs it, and deliberately trigger an error path (e.g. reject the promise) to confirm your try/catch handles it gracefully.",
    doneWhen: "You can explain why await only pauses its own async function (not the whole program), and can write a basic async function with proper try/catch error handling.",
    checks: [
      {q: "Why does 'this logs BEFORE done!' print before the awaited result in the delay() example?", a: "Calling main() doesn't block the rest of the program — only the code INSIDE main() pauses at the await. Everything outside that async function (like the console.log after calling main()) keeps running immediately, which is exactly the non-blocking behavior async/await is designed to provide."}
    ],
    keyTakeaways: ["A promise represents a value that will be available later, either resolved or rejected.", "async/await lets asynchronous code read like synchronous code, without blocking the rest of the program.", "Always wrap awaited code in try/catch to handle promise rejections gracefully."],
    resources: [
      {label: "MDN — Using promises", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises", kind: "docs"},
      {label: "MDN — async function", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function", kind: "docs"}
    ]
  },
  {
    id: "fs-dom-basics", title: "The DOM — how JavaScript touches the page",
    concept: "The DOM (Document Object Model) is the browser's live, in-memory representation of an HTML page as a tree of objects — JavaScript reads and modifies this tree to change what's actually shown, using methods like `document.querySelector()` to find elements and properties like `.textContent`/`.style` to change them. Every framework you'll learn later (React included) ultimately works by manipulating the DOM under the hood — understanding it directly first makes frameworks feel like a helpful abstraction rather than magic.",
    analogy: "If an HTML file is a recipe, the DOM is the actual dish being cooked, sitting on the counter, that you can still poke, rearrange, and modify LIVE while it's there — changing an ingredient in the recipe file itself does nothing to a dish that's already been made; you have to reach into the actual dish (the DOM) to change what's currently on the counter.",
    examples: [
      {code: "// (Illustrative -- this runs in a BROWSER, where `document` exists; not in plain Node)\n// <div id=\"greeting\">Hello</div>\n\nconst el = document.querySelector(\"#greeting\");\nconsole.log(el.textContent);      // \"Hello\"\n\nel.textContent = \"Hello, Forage!\";  // directly changes what's shown on the page\nel.style.color = \"blue\";             // directly changes the element's styling\n\nconsole.log(el.textContent);      // \"Hello, Forage!\"", note: "querySelector uses CSS-style selectors ('#greeting' targets the element with id='greeting') to find an element in the live page. Changing .textContent or .style immediately updates what the USER SEES -- no page reload needed, which is the whole point of dynamic, JavaScript-driven pages."},
      {code: "// (Illustrative browser example) -- responding to a user click\nconst button = document.querySelector(\"#myButton\");\nlet clickCount = 0;\n\nbutton.addEventListener(\"click\", () => {\n  clickCount += 1;\n  document.querySelector(\"#counter\").textContent = `Clicked ${clickCount} times`;\n});", note: "addEventListener is how JavaScript reacts to user actions (clicks, typing, etc.) -- this closure-based pattern (the arrow function 'remembers' clickCount, tying back to the closures lesson) is the fundamental building block behind every interactive web page, before any framework is introduced."}
    ],
    warn: "The DOM examples in this lesson are BROWSER-only (they reference `document`, which doesn't exist in a plain Node.js script) — run them in an actual HTML page's browser console or a linked script, not in Node directly.",
    mistakes: ["Trying to run DOM code (document.querySelector, etc.) in plain Node.js — `document` only exists in a browser environment (or a browser-like testing environment).","Directly manipulating the DOM extensively in large apps without a framework — it becomes hard to keep the UI in sync with data as an app grows, which is exactly the problem React (next module) solves.","Forgetting `addEventListener` callbacks are closures — they can access variables from their surrounding scope, which is how the click counter in the example 'remembers' clickCount between clicks."],
    handsOn: "Create a simple HTML file with a button and a div, link a script that uses querySelector and addEventListener to update the div's text on each click (matching the second example). Open it in a real browser and confirm the click counter works.",
    doneWhen: "You can explain what the DOM is, use querySelector to find an element, and use addEventListener to respond to a user interaction — verified in an actual browser.",
    checks: [
      {q: "Why do the DOM examples in this lesson only work in a browser, not in a plain Node.js script?", a: "The DOM (document object) is provided by the BROWSER environment — Node.js runs JavaScript outside a browser and doesn't have a page to represent, so `document` simply doesn't exist there unless you add a browser-emulation library."}
    ],
    keyTakeaways: ["The DOM is the browser's live, in-memory tree representation of an HTML page.", "JavaScript reads/modifies the DOM to change what's actually shown, without a page reload.", "Frameworks like React ultimately manipulate the DOM under the hood — understanding it directly demystifies what frameworks automate."],
    resources: [
      {label: "MDN — Introduction to the DOM", url: "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction", kind: "docs"},
      {label: "MDN — Document.querySelector()", url: "https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector", kind: "docs"}
    ]
  }
  ]
};
