// FORAGE — Full-Stack Developer path, Module 2: React Fundamentals
// Facts verified against React's own official docs (react.dev): state-a-components-memory,
// rendering-lists, and referenced hooks/props documentation. JS-logic-only snippets (state
// update patterns, key-based diffing simulation) executed for real with Node; JSX-rendering
// examples are labeled illustrative since they need a browser/React runtime, matching React's
// own documented behavior exactly.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "fs-react", title: "React Fundamentals",
  why: "Module 1 built direct DOM skills; now you'll see WHY frameworks like React exist. Manually keeping a complex UI in sync with changing data gets unmanageable fast — React lets you describe WHAT the UI should look like for a given state, and it handles updating the actual DOM efficiently.",
  topics: [
  {
    id: "fs-react-components-props", title: "Components and props",
    concept: "A React component is a JavaScript function that returns JSX (HTML-like syntax embedded in JS) describing what should appear on screen. PROPS (short for 'properties') are how a parent component passes data DOWN to a child component — read-only from the child's perspective, similar to function arguments. Breaking a UI into small, focused components that each take clear props is the core organizing principle of React apps, mirroring how you'd break a large program into small, well-named functions.",
    analogy: "A component is like a custom, reusable stamp: you design the stamp once (the component), then use it repeatedly with different ink colors or labels (different props) to produce many similar-but-customized impressions, instead of hand-drawing every single instance from scratch.",
    examples: [
      {code: "// (Illustrative JSX -- runs inside a React app, needs a build step like Next.js/Vite)\nfunction Greeting({ name, isVip }) {\n  return (\n    <p>\n      Hello, {name}!{isVip && \" You're a VIP member.\"}\n    </p>\n  );\n}\n\nfunction App() {\n  return (\n    <div>\n      <Greeting name=\"Aditi\" isVip={true} />\n      <Greeting name=\"Rahul\" isVip={false} />\n    </div>\n  );\n}", note: "Greeting is reused TWICE with different props (name, isVip), producing two different outputs from one component definition -- exactly the reusable-stamp idea. Props flow ONE WAY: from App down into Greeting; Greeting cannot modify App's data directly, only read what it's given."},
      {code: "// The underlying JS pattern -- destructuring props, which you already know from Module 1\nfunction formatGreeting({ name, isVip }) {   // same destructuring pattern as any JS function\n  return `Hello, ${name}!` + (isVip ? \" You're a VIP member.\" : \"\");\n}\n\nconsole.log(formatGreeting({ name: \"Aditi\", isVip: true }));\nconsole.log(formatGreeting({ name: \"Rahul\", isVip: false }));", note: "This plain-JS version demonstrates the exact same destructuring pattern React components use for props -- {name, isVip} pulled out of a single object argument -- proving props aren't a new concept, just a JS destructuring pattern applied to a specific object React passes in."}
    ],
    mistakes: ["Trying to modify a prop directly inside a child component — props are read-only from the child's side; data flows down, and changes flow back up via callback functions (a later lesson).","Making components too large/monolithic — small, focused components (mirroring well-factored functions) are easier to reuse, test, and reason about.","Forgetting props are just a single object argument — the destructuring syntax `({ name, isVip })` is standard JavaScript, not special React magic."],
    handsOn: "Using the plain-JS formatGreeting function (runnable in Node right now), call it with 2-3 different prop objects and confirm the outputs. This proves you understand the underlying data-flow pattern before adding JSX/browser complexity on top.",
    doneWhen: "You can explain what props are, that they flow one-way (parent to child), and can write a function that destructures a props-like object exactly as a React component would.",
    checks: [
      {q: "Can a child component directly modify a prop value it receives from its parent?", a: "No — props are read-only from the child's perspective. Data flows one way, down from parent to child; a child that needs to affect the parent's data does so via a callback function passed down as a prop, not by mutating the prop directly."}
    ],
    keyTakeaways: ["A React component is a function returning JSX describing the UI.", "Props pass data one-way, from parent to child, and are read-only in the child.", "Props destructuring is standard JavaScript object destructuring, not special React syntax."],
    resources: [
      {label: "React docs — Passing Props to a Component", url: "https://react.dev/learn/passing-props-to-a-component", kind: "docs"},
      {label: "React docs — Your First Component", url: "https://react.dev/learn/your-first-component", kind: "docs"}
    ]
  },
  {
    id: "fs-react-usestate", title: "State with useState",
    concept: "Per React's own documentation, `useState` is a Hook that lets a component 'remember' a value BETWEEN renders — it returns an array `[value, setValue]` via array destructuring, where `value` is the current state and `setValue(newValue)` updates it AND triggers React to re-render the component with the new value. Critically, state is preserved across re-renders of the SAME component instance, but resets to its initial value if the component unmounts and mounts again — and two instances of the same component have completely independent, isolated state.",
    analogy: "Think of useState as giving a component its own private sticky note that persists between the component's redraws — each time the component re-renders (redraws itself), it checks the same sticky note rather than starting fresh, which is why a counter can keep incrementing instead of resetting to 0 every time you interact with it. Two separate instances of the same component type each get their OWN sticky note — writing on one never affects the other.",
    examples: [
      {code: "// (Illustrative JSX -- matches React's own official Counter example exactly)\nimport { useState } from \"react\";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>Increment</button>\n    </>\n  );\n}", note: "This is React's own documented pattern verbatim: useState(0) returns [count, setCount] via array destructuring. Calling setCount schedules a re-render with the new value; React remembers count between renders of the SAME component instance, which is why clicking Increment repeatedly keeps counting up instead of resetting."},
      {code: "// The underlying closure idea (Module 1, lesson 2) -- why state 'sticks' between calls\nfunction makeStateHolder(initial) {\n  let value = initial;\n  const get = () => value;\n  const set = (newValue) => { value = newValue; };\n  return [get, set];\n}\n\nconst [getCount, setCount] = makeStateHolder(0);\nconsole.log(getCount());   // 0\nsetCount(getCount() + 1);\nsetCount(getCount() + 1);\nconsole.log(getCount());   // 2 -- the closure 'remembers' value between calls", note: "This is a SIMPLIFIED illustration of the closure-based idea underlying persistent state (React's real internal implementation is more sophisticated and tied to the component tree) -- but it demonstrates concretely, with runnable code, why a closure can 'remember' a value across multiple calls, echoing the makeCounter example from Module 1."}
    ],
    mistakes: ["Mutating state directly (e.g. array.push() on a state array) instead of calling the setter — React needs the SETTER call to know a re-render is needed; direct mutation can silently fail to update the UI.","Assuming state persists automatically across a full page reload — it doesn't; useState only persists between re-renders of a mounted component, not across page loads.","Forgetting each component INSTANCE has isolated state — rendering the same component twice creates two independent 'sticky notes', not a shared one."],
    handsOn: "Run the makeStateHolder example and confirm it prints 0 then 2, building real intuition for the 'remembers between calls' idea. Then, if you have a React environment available (or use an online sandbox), build the Counter component and confirm clicking Increment actually increases the displayed count.",
    doneWhen: "You can explain what useState returns and why state persists between renders, and have demonstrated the underlying 'remembers a value' idea with real closure-based code.",
    checks: [
      {q: "If you render the same component twice on a page, and each uses useState, do they share state or have independent state?", a: "Independent state — each component INSTANCE gets its own separate state, even though they're the same component type. Changing one instance's state has no effect on the other's."}
    ],
    keyTakeaways: ["useState returns [value, setValue] via array destructuring; calling setValue updates state and triggers a re-render.", "State persists across re-renders of the same component instance, but resets on unmount/remount.", "Each component instance has completely isolated state, even for the same component type."],
    resources: [
      {label: "React docs — State: A Component's Memory", url: "https://react.dev/learn/state-a-components-memory", kind: "docs"},
      {label: "React docs — useState reference", url: "https://react.dev/reference/react/useState", kind: "docs"}
    ]
  },
  {
    id: "fs-react-rendering-lists", title: "Rendering lists — and why 'key' matters",
    concept: "Rendering a list of data in React typically uses `.map()` (Module 1!) to turn an array into an array of JSX elements — and React REQUIRES each element in a rendered list to have a unique `key` prop. Per React's own docs, keys let React 'match up' list items across re-renders when the array changes (items added, removed, or reordered) — WITHOUT stable keys, React can't reliably tell which item is which, leading to subtle bugs like component state landing on the wrong item after a reorder. React's own docs explicitly warn that using the array INDEX as a key 'often leads to subtle and confusing bugs' when the list can reorder or change.",
    analogy: "React's own documentation uses this exact image: imagine files on your desktop had no names, only positions ('the first file, the second file'). Delete the first file, and suddenly the second file IS the first file by position — even though nothing about that file actually changed. A stable `key` (like a person's unique ID) is the FILE NAME that lets React correctly track 'this is the same item' even as its position in the list shifts.",
    examples: [
      {code: "// (Illustrative JSX -- matches React's own official docs pattern)\nfunction PeopleList({ people }) {\n  return (\n    <ul>\n      {people.map((person) => (\n        <li key={person.id}>{person.name}</li>    // GOOD: stable, unique id\n      ))}\n    </ul>\n  );\n}\n\n// BAD (per React's own docs -- avoid this when the list can reorder):\n// {people.map((person, index) => <li key={index}>{person.name}</li>)}", note: "Using person.id (a stable identifier from the DATA itself) as the key, rather than the array index, is React's own explicitly documented best practice -- the id doesn't change even if the person's position in the list changes, which is exactly the property a key needs to have."},
      {code: "// Simulating WHY index-as-key breaks on reorder/deletion (plain JS logic, runnable now)\nlet peopleV1 = [{ id: 1, name: \"Amy\" }, { id: 2, name: \"Bo\" }, { id: 3, name: \"Cy\" }];\nlet peopleV2 = [{ id: 2, name: \"Bo\" }, { id: 3, name: \"Cy\" }];   // Amy (id 1) was deleted\n\nconsole.log(\"--- using index as key ---\");\npeopleV1.forEach((p, i) => console.log(`key=${i} -> ${p.name}`));\npeopleV2.forEach((p, i) => console.log(`key=${i} -> ${p.name}`));\n// notice: Bo's key CHANGES from 1 to 0 -- React would think Bo's item was REPLACED, not just shifted\n\nconsole.log(\"--- using id as key ---\");\npeopleV1.forEach((p) => console.log(`key=${p.id} -> ${p.name}`));\npeopleV2.forEach((p) => console.log(`key=${p.id} -> ${p.name}`));\n// notice: Bo's key stays 2 in both -- React correctly recognizes it as the SAME item", note: "This demonstrates the exact bug React's docs warn about: with index-as-key, Bo's key silently shifts from 1 to 0 after Amy is deleted, so React would treat that list slot as a NEW/different item rather than recognizing Bo as the same person who just moved up -- with id-as-key, Bo's key correctly stays 2 throughout, letting React track identity correctly across the change."}
    ],
    mistakes: ["Using the array index as key for a list that can reorder, insert, or delete — React's own docs explicitly call this out as a source of subtle bugs (e.g. component state landing on the wrong row).","Omitting `key` entirely — React falls back to using the index anyway (with the same risks) and also logs a console warning.","Using a NON-unique or unstable value (like a random number generated on every render) as a key — it must be stable across re-renders and unique among siblings to work correctly."],
    handsOn: "Run the plain-JS simulation and confirm Bo's index-based key shifts from 1 to 0 after a deletion, while the id-based key stays stable at 2. Then, in your own words, write one sentence explaining why that shifting index would confuse React about which list item is which.",
    doneWhen: "You can explain why React requires keys for lists, why index-as-key is risky for reorderable lists, and have demonstrated the underlying identity-tracking problem with real code.",
    checks: [
      {q: "Why does React's documentation specifically warn against using the array index as a key for a list that can be reordered or have items removed?", a: "The index is just a POSITION, not a stable identity — when items are added, removed, or reordered, an item's index can change even though the item itself hasn't. React uses the key to match items across renders, so a shifting index makes React think an item was replaced rather than just moved, causing subtle bugs like state landing on the wrong item."}
    ],
    keyTakeaways: ["React requires a unique, stable key when rendering a list so it can track item identity across re-renders.", "React's own docs warn against using array index as key for lists that can reorder, insert, or delete.", "A stable identifier from the data itself (like an id) is the correct key choice."],
    resources: [
      {label: "React docs — Rendering Lists", url: "https://react.dev/learn/rendering-lists", kind: "docs"},
      {label: "React docs — keeping list items in order with key", url: "https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key", kind: "docs"}
    ]
  },
  {
    id: "fs-react-events-forms", title: "Handling events and forms",
    concept: "React handles user interactions (clicks, typing) by attaching event handler FUNCTIONS directly in JSX (e.g. `onClick={handleClick}`), following the same closure-based callback pattern from Module 1's addEventListener. For form inputs, React commonly uses CONTROLLED COMPONENTS: the input's displayed value is driven by state (`value={text}`), and every keystroke calls a handler (`onChange`) that updates that state — meaning React's state is always the single source of truth for what's in the box, not the DOM itself.",
    analogy: "An uncontrolled input is like a whiteboard anyone can scribble on freely — you'd have to walk over and READ it to know its current content. A controlled input is like a digital display that ONLY shows whatever value you explicitly tell it to show — every time someone 'writes' on it (types), that input immediately reports the keystroke back to you, and you decide what the display shows next by updating your own record (state) first.",
    examples: [
      {code: "// (Illustrative JSX -- a controlled text input, standard React pattern)\nimport { useState } from \"react\";\n\nfunction NameForm() {\n  const [name, setName] = useState(\"\");\n\n  function handleSubmit(e) {\n    e.preventDefault();          // stop the browser's default full-page-reload form submit\n    console.log(\"Submitted:\", name);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input\n        value={name}                              // state drives what's shown -- controlled\n        onChange={(e) => setName(e.target.value)}   // every keystroke updates state\n      />\n      <button type=\"submit\">Submit</button>\n    </form>\n  );\n}", note: "The input's value is ALWAYS exactly what's in the `name` state variable -- React state is the single source of truth. e.preventDefault() stops the browser's default behavior (a full page reload on form submit), letting React handle the submission with JavaScript instead."},
      {code: "// The underlying event-handler pattern is the same closure idea from Module 1's addEventListener\nfunction simulateControlledInput() {\n  let currentValue = \"\";              // stands in for React state\n  const handleChange = (typedChar) => {\n    currentValue += typedChar;         // simulating each keystroke updating state\n    console.log(\"input now shows:\", currentValue);\n  };\n\n  for (const char of \"Hi\") {\n    handleChange(char);\n  }\n}\nsimulateControlledInput();", note: "This plain-JS simulation mirrors the controlled-input pattern: each 'keystroke' calls a handler that updates the tracked value, and the displayed value always reflects that tracked state -- the exact same closure-based callback structure as the addEventListener click-counter example from Module 1, just applied to typing instead of clicking."}
    ],
    mistakes: ["Forgetting `e.preventDefault()` in a form's onSubmit handler — the browser's default full-page-reload behavior will fire, undoing whatever React was managing.","Setting an input's `value` from state without an `onChange` handler — the input becomes read-only/frozen, since nothing updates the state that drives its displayed value.","Confusing controlled and uncontrolled inputs — mixing patterns inconsistently (e.g. setting value but not handling onChange properly) is a very common source of React form bugs."],
    handsOn: "Run the simulateControlledInput example and confirm it prints the growing string after each simulated keystroke, mirroring how a controlled input's state grows with each real keystroke. Then, if you have a React environment, build the NameForm component and confirm typing updates what's shown and submitting logs the name.",
    doneWhen: "You can explain what a controlled component is, why e.preventDefault() is needed in form handlers, and can trace the state-update flow for a controlled input's onChange handler.",
    checks: [
      {q: "In a controlled input, what determines what's currently displayed in the box — the DOM's own internal input state, or something else?", a: "React state is the single source of truth — the input's displayed value is driven by whatever the state variable currently holds (via the value prop), and onChange updates that state on every keystroke, rather than the DOM tracking its own independent value."}
    ],
    keyTakeaways: ["React event handlers follow the same closure-based callback pattern as native addEventListener.", "A controlled component's displayed value is driven entirely by React state, not the DOM's own internal state.", "e.preventDefault() is needed in form onSubmit handlers to stop the browser's default full-page-reload behavior."],
    resources: [
      {label: "React docs — Responding to Events", url: "https://react.dev/learn/responding-to-events", kind: "docs"},
      {label: "React docs — Reacting to Input with State", url: "https://react.dev/learn/reacting-to-input-with-state", kind: "docs"}
    ]
  }
  ]
};
