// FORAGE — Full-Stack Developer path, Module 3: Backend, Deployment & Capstone
// Node/Express facts verified against Express's own official routing guide. Server code
// executed for real with a live Express server and real HTTP requests via fetch. Capstone
// lessons are project-based and correctly get 0 quizzes per the light-quiz rule.

module.exports = {
  id: "fs-backend-deploy", title: "Backend, Deployment & Capstone",
  why: "Modules 1-2 built the front-end half of full-stack development. This module builds the back-end half — a real Node.js server handling requests — then ties EVERYTHING in this path together into one deployed, working full-stack application, the capstone that proves you can ship a complete product end to end.",
  topics: [
  {
    id: "fs-node-express-basics", title: "Node.js and Express — your first backend server",
    concept: "Node.js runs JavaScript OUTSIDE the browser, which is what lets JavaScript power a server. Express is the most widely-used Node web framework, providing simple ROUTING: you register a handler function for a specific HTTP method + path (e.g. `app.get('/api/users', handler)`), and Express calls it whenever a matching request arrives — the same client-server/REST concepts from earlier in this platform (Software Engineer Module 3), now actually implemented in JavaScript instead of just diagrammed.",
    analogy: "Express is like a receptionist with a very specific instruction sheet: 'if someone asks for X in this particular way, hand them to THIS person; if they ask for Y, hand them to THAT person.' Each `app.get(path, handler)` line is one entry on that instruction sheet, and Express's whole job is matching incoming requests to the right entry and routing them there.",
    examples: [
      {code: "const express = require(\"express\");\nconst app = express();\napp.use(express.json());        // parses JSON request bodies automatically\n\napp.get(\"/api/health\", (req, res) => {\n  res.json({ status: \"ok\" });\n});\n\napp.get(\"/api/users/:id\", (req, res) => {     // :id is a URL parameter\n  res.json({ id: req.params.id, name: `User ${req.params.id}` });\n});\n\nconst server = app.listen(3999, () => console.log(\"server running\"));\n\n// Real requests against the running server (using Node's built-in fetch)\n(async () => {\n  const health = await fetch(\"http://localhost:3999/api/health\");\n  console.log(await health.json());\n\n  const user = await fetch(\"http://localhost:3999/api/users/42\");\n  console.log(await user.json());\n\n  server.close();\n})();", note: "req.params.id captures the ':id' portion of the URL -- requesting /api/users/42 makes req.params.id equal '42'. This mirrors FastAPI's path-parameter pattern from the AI Engineer path, just in JavaScript/Express instead of Python -- the underlying REST concept is identical across languages/frameworks."},
      {code: "const express2 = require(\"express\");\nconst app2 = express2();\napp2.use(express2.json());\n\napp2.post(\"/api/echo\", (req, res) => {\n  res.json({ youSent: req.body });    // req.body is the parsed JSON from the request\n});\n\nconst server2 = app2.listen(4000, () => console.log(\"server2 running\"));\n\n(async () => {\n  const response = await fetch(\"http://localhost:4000/api/echo\", {\n    method: \"POST\",\n    headers: { \"Content-Type\": \"application/json\" },\n    body: JSON.stringify({ message: \"hello from the client\" }),\n  });\n  console.log(await response.json());\n  server2.close();\n})();", note: "express.json() middleware parses the incoming request body into req.body automatically -- without it, req.body would be undefined. This POST + JSON body pattern is the exact same request-body concept from FastAPI's Pydantic models in the AI Engineer path, expressed in Express's simpler, un-validated form."}
    ],
    mistakes: ["Forgetting `app.use(express.json())` — without it, req.body is undefined for JSON POST requests, a very common first-timer bug.","Defining routes in a conflicting order where a more general route (e.g. `/api/users/new`) is shadowed by an earlier parameterized route (`/api/users/:id` matching 'new' as an id) — Express matches routes in the order they're defined.","Forgetting to send a response at all in a handler — the client's request will hang waiting indefinitely if res.json()/res.send() is never called."],
    handsOn: "Run both examples and confirm the responses match. Then add a new route `app.get('/api/users/:id/greeting', ...)` that returns a personalized greeting using the id param, and test it with fetch.",
    doneWhen: "You can set up a basic Express server with GET/POST routes, correctly use req.params and req.body, and have verified it with real HTTP requests.",
    checks: [
      {q: "Without app.use(express.json()), what happens when a client sends a POST request with a JSON body?", a: "req.body will be undefined — the express.json() middleware is what parses the incoming JSON request body into a usable JavaScript object; without it, Express doesn't automatically parse the body for you."}
    ],
    keyTakeaways: ["Express routes match an HTTP method + path to a handler function.", "req.params captures URL parameters (:id); req.body holds the parsed JSON body (requires express.json() middleware).", "The underlying REST concepts are identical to FastAPI's — just expressed in JavaScript/Express instead of Python."],
    resources: [
      {label: "Express — Routing guide", url: "https://expressjs.com/en/guide/routing.html", kind: "docs"},
      {label: "Express — official docs", url: "https://expressjs.com/", kind: "docs"}
    ]
  },
  {
    id: "fs-fullstack-connecting", title: "Connecting frontend to backend",
    concept: "A full-stack app is a React frontend (Module 2) making HTTP requests to a backend API (last lesson) using `fetch` — the same async/await patterns from Module 1. The critical piece that trips up beginners: CORS (Cross-Origin Resource Sharing) — by default, a browser blocks a frontend running on one origin (e.g. localhost:3000) from calling a backend on a DIFFERENT origin (e.g. localhost:4000) unless the backend explicitly allows it via CORS headers. This is a browser SECURITY feature, not a bug, and every full-stack developer hits it at least once.",
    analogy: "CORS is like a building's security desk checking a badge: by default, staff from Building A (your frontend's origin) aren't allowed into Building B (your backend's origin) unless Building B's security desk has explicitly pre-approved that specific building's badges. The backend has to proactively say 'yes, I'll accept requests from that origin' — the browser won't just let it happen silently.",
    examples: [
      {code: "// Frontend-side fetch call (this is what a React component would do in an effect/handler)\nasync function getUsers() {\n  const response = await fetch(\"http://localhost:4001/api/users\");\n  if (!response.ok) {\n    throw new Error(`Request failed: ${response.status}`);\n  }\n  return response.json();\n}\n\n// (Illustrative usage inside a React component)\n// useEffect(() => { getUsers().then(setUsers); }, []);\nconsole.log(\"fetch pattern matches Module 1's async/await lesson exactly\");", note: "This is the exact async/await + fetch pattern from Module 1, now applied to talking to YOUR OWN backend instead of a generic delay() example -- checking response.ok before parsing is a real-world best practice, since fetch does NOT automatically throw on HTTP error statuses like 404/500."},
      {code: "const express = require(\"express\");\nconst cors = require(\"cors\");\nconst app = express();\napp.use(cors());                 // allows requests from any origin (fine for dev/learning)\napp.use(express.json());\n\napp.get(\"/api/users\", (req, res) => {\n  res.json([{ id: 1, name: \"Amy\" }, { id: 2, name: \"Bo\" }]);\n});\n\nconst server = app.listen(4001, () => console.log(\"cors-enabled server running\"));\n\n(async () => {\n  const response = await fetch(\"http://localhost:4001/api/users\");\n  console.log(await response.json());\n  server.close();\n})();", note: "app.use(cors()) explicitly tells Express to add the response headers that permit cross-origin browser requests -- WITHOUT this line, a real browser-based frontend on a different port/origin would have the request BLOCKED by the browser itself (this Node-to-Node fetch test doesn't enforce CORS the way a real browser does, but the header is what a real browser checks)."}
    ],
    warn: "CORS is enforced by the BROWSER, not by Node.js scripts calling each other directly — this lesson's fetch-in-Node examples will 'work' even without CORS configured, because Node doesn't enforce it. A REAL browser-based frontend calling a cross-origin backend WILL be blocked without proper CORS headers — always test cross-origin behavior in an actual browser, not just a Node script.",
    mistakes: ["Testing CORS-dependent behavior only in Node scripts (which don't enforce it) instead of an actual browser, and being surprised when it fails in the real app.","Not checking `response.ok` before parsing a fetch response — fetch only rejects on network failure, NOT on HTTP error statuses like 404 or 500.","Enabling `cors()` with no restrictions in a real production app without considering security — wide-open CORS is fine for learning/development, but production APIs often restrict allowed origins."],
    handsOn: "Run both examples. Then set up a minimal real React app (or use an existing one) on one port and a separate Express server (with and then without CORS enabled) on another port, and confirm in an ACTUAL BROWSER that the request fails without CORS and succeeds with it — this is the only way to see real CORS enforcement.",
    doneWhen: "You can explain what CORS is and why it exists, and have confirmed (in a real browser, not just Node) that cross-origin requests are blocked without proper CORS configuration.",
    checks: [
      {q: "Why might a fetch-in-Node-script test of a CORS-restricted API 'work fine' while the same request from an actual browser-based frontend gets blocked?", a: "CORS is a BROWSER security feature, not something enforced by Node.js scripts calling each other. A Node script has no CORS enforcement at all, so it will succeed regardless of headers — only a real browser actually checks CORS headers and blocks disallowed cross-origin requests."}
    ],
    keyTakeaways: ["A full-stack app connects a React frontend to a backend API via fetch, using async/await.", "CORS is a browser security feature blocking cross-origin requests unless the backend explicitly allows them.", "Always test CORS-dependent behavior in a real browser, not a Node script, since Node doesn't enforce it."],
    resources: [
      {label: "MDN — Cross-Origin Resource Sharing (CORS)", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS", kind: "docs"},
      {label: "Express — cors middleware package", url: "https://expressjs.com/en/resources/middleware/cors.html", kind: "docs"}
    ]
  },
  {
    id: "fs-deployment-basics", title: "Deploying a full-stack app",
    concept: "Deployment means making your app reachable on the public internet instead of only localhost. Modern platforms (Vercel, Netlify, Railway, Render) have largely automated what used to be a manual, error-prone process: connect a GitHub repo, the platform detects the framework, runs the build, and deploys — often automatically redeploying on every push to your main branch (continuous deployment). For a full-stack app, you typically need to deploy the FRONTEND (often as static/SSR assets) and decide where the BACKEND/database lives — sometimes the same platform, sometimes a dedicated backend host or managed database service like Supabase (which this very platform, Forage, uses).",
    analogy: "Deploying used to be like manually shipping a physical package yourself — packing it, addressing it, carrying it to the post office. Modern platforms are like a service that watches your workshop (GitHub repo) and automatically ships a fresh package the moment you finish a new version — you just keep building, and shipping happens on its own.",
    examples: [
      {code: "# A typical deployment flow (conceptual, not a single runnable script)\n\"\"\"\n1. Push code to a GitHub repository\n2. Connect the repo to a hosting platform (e.g. Vercel)\n3. Platform detects the framework (e.g. Next.js) and configures the build automatically\n4. Platform runs the build command (e.g. `npm run build`)\n5. On success, the app is live at a public URL\n6. Every future push to main triggers an automatic redeploy\n\"\"\"\nprint(\"environment variables (API keys, DB URLs) are configured in the platform's\")\nprint(\"dashboard, NEVER committed to the repo -- this is the same secrets discipline\")\nprint(\"from Module 8 of the AI Engineer path (Docker), applied to web deployment\")", note: "This is a WALKTHROUGH of the conceptual flow, not literal code to run -- the key transferable idea across almost every modern platform is: connect the repo, let the platform auto-detect and build, keep secrets OUT of the repo and in the platform's environment variable settings instead."}
    ],
    warn: "NEVER commit real API keys, database passwords, or other secrets directly into your repository — even a private one. Use environment variables configured in the hosting platform's dashboard (or a local `.env` file that's explicitly excluded via `.gitignore`), exactly the discipline used throughout this very Forage platform's own codebase.",
    mistakes: ["Committing a `.env` file with real secrets to a public (or even private) GitHub repo — a very common, very costly real-world mistake.","Assuming the frontend and backend must be deployed on the same platform/service — modern architectures often mix and match (e.g. a Vercel-hosted frontend calling a Supabase-hosted backend/database, exactly like this Forage app itself).","Not testing the PRODUCTION build locally before deploying — a project that works in dev mode can sometimes fail in a production build due to different optimizations/environment assumptions."],
    handsOn: "Write out (in your own words) a deployment plan for your own capstone project (next lesson): which platform you'd use for the frontend, where the backend/database would live, and what secrets/environment variables it would need — without committing any real secret values anywhere.",
    doneWhen: "You can explain the modern connect-repo-and-auto-deploy flow, and can articulate a concrete deployment plan (frontend host, backend/database host, secrets handling) for a real project.",
    checks: [
      {q: "Where should real API keys and database passwords live for a deployed app — committed in the repo, or somewhere else?", a: "In environment variables configured through the hosting platform's dashboard (or a local .env file excluded via .gitignore) — never committed directly into the repository, even a private one, since that risks real exposure of sensitive credentials."}
    ],
    keyTakeaways: ["Modern deployment platforms auto-detect your framework and redeploy automatically on every push (continuous deployment).", "Frontend and backend/database can live on different platforms — mixing services is common and normal.", "Secrets (API keys, DB passwords) belong in environment variables, never committed to the repo."],
    resources: [
      {label: "Vercel — Deploying documentation", url: "https://vercel.com/docs/deployments/overview", kind: "docs"},
      {label: "The Twelve-Factor App — Config (environment variables)", url: "https://12factor.net/config", kind: "reference"}
    ]
  },
  {
    id: "fs-capstone", title: "Capstone: ship a full-stack app",
    concept: "Your capstone: build a small but complete full-stack app combining everything in this path — a React frontend (Module 2) that fetches from and posts to your own Express backend (this module), which stores data somewhere real (even a simple in-memory array is fine for a first version, or a real database if you're ready), deployed live on the public internet. Scope it deliberately small — a to-do list, a simple notes app, a mini link-shortener — the GOAL is a complete, working, DEPLOYED loop, not an ambitious feature list you don't finish.",
    analogy: "This capstone is like building and actually launching a small boat, rather than perfecting blueprints for a yacht you never put in the water. A small, complete, floating boat teaches you far more — and proves far more to an interviewer — than an elaborate design that never left the drawing board.",
    examples: [
      {code: "# Suggested minimal-but-complete scope for a first full-stack capstone\nscope = \"\"\"\nFrontend: React app with a form (controlled input, Module 2) and a rendered list\n          (with proper keys, Module 2) of items fetched from your API.\n\nBackend:  Express server (this module) with:\n            GET  /api/items   -> list all items\n            POST /api/items   -> add a new item\n          Data can start as a simple in-memory array -- swap for a real database later.\n\nGlue:     Frontend calls the backend via fetch (async/await, Module 1),\n          with CORS enabled on the backend for local development.\n\nDeploy:   Both pieces live on the public internet (last lesson), with secrets\n          in environment variables, not the repo.\n\"\"\"\nprint(scope)", note: "This is a WORKED SCOPE EXAMPLE, not a template to copy verbatim -- the point is the shape: small, complete, and touching every layer (frontend state/rendering, backend routes, the fetch glue between them, and real deployment) rather than a partial, ambitious build that never reaches 'done'."}
    ],
    mistakes: ["Scoping the capstone too ambitiously and never reaching a deployed, working state — a small complete loop beats a large incomplete one, every time.","Skipping deployment and calling it 'done' when it only runs on localhost — the deployed, publicly-reachable version is the actual proof of full-stack capability.","Not testing the deployed version end-to-end after shipping — confirm the live frontend can actually talk to the live backend, not just that each deploys without error individually."],
    handsOn: "Build your capstone following the scope pattern above (or your own similarly-small scope), get it fully working locally first, then deploy both frontend and backend, and confirm the LIVE, deployed version works end-to-end — not just localhost.",
    doneWhen: "You have a small, complete, DEPLOYED full-stack app where the live frontend successfully talks to the live backend, verified by actually using it at its public URL.",
    checks: [],
    keyTakeaways: ["A small, complete, deployed full-stack app is a stronger capstone than a large, ambitious, unfinished one.", "The capstone should exercise every layer: frontend state/rendering, backend routes, the fetch glue, and real deployment.", "Always verify the LIVE deployed version end-to-end, not just that each piece deploys without error."],
    resources: [
      {label: "Vercel — Deploying documentation", url: "https://vercel.com/docs/deployments/overview", kind: "docs"},
      {label: "Common Core — Career track (interview framing)", url: "/stream/common-core", kind: "course"},
      {label: "Forage Interview — practice explaining this project live", url: "/interview", kind: "practice"}
    ]
  }
  ]
};
