// FAANG-caliber MCQ bank for Stream 1 (Industry Foundations).
// Each: [lessonSlug, prompt, options[], correctIndex, explanation, difficulty(1-3), styleTag]
// Authored to interview standard; code-based answers executed/verified before seeding.
// m1t1 and m4t1 already seeded (10 questions) — this file covers the rest.

module.exports = [
// ---------------- MONTH 1: LINUX ----------------
["m1t2","You are in /home/ani/projects. Which command lands you in /home/ani in one step?",
 ["cd ..","cd .","cd /home","cd projects"],0,
 "`..` means the parent of where you stand; from /home/ani/projects that is /home/ani. `.` is the current folder, and cd /home would overshoot.",1,"conceptual"],
["m1t2","What is the difference between `/etc/hosts` and `etc/hosts` typed as an argument?",
 ["The first is absolute (from root); the second is relative to your current folder","Nothing — Linux treats them identically","The second is invalid syntax","The first only works as root"],0,
 "A leading slash means 'start from the root /'. Without it, the path is resolved relative to your current directory, so the two usually point to different files.",2,"conceptual"],
["m1t2","From any folder, which reliably takes you to your home directory?",
 ["cd ~","cd home","cd /home","cd .."],0,
 "`~` always expands to your home directory regardless of where you are. `/home` is the parent that contains all users' homes, not yours specifically.",1,"conceptual"],
["m1t3","`rm important.txt` — where does the file go?",
 ["It is deleted permanently; there is no recycle bin","To a trash folder you can restore from","To /tmp for 30 days","It is hidden, not deleted"],0,
 "Unlike a desktop delete, `rm` removes the file immediately and permanently. This is why you read the command twice before pressing Enter.",1,"conceptual"],
["m1t3","You run `cp report.txt`. What happens?",
 ["An error — cp needs both a source AND a destination","It copies report.txt to report.txt.bak","It copies report.txt into your home folder","It prints the file's contents"],0,
 "cp always takes source THEN destination. With only one argument it cannot know where to copy to, so it errors with 'missing destination file operand'.",2,"code-output"],
["m1t3","Which single command both moves AND can rename a file?",
 ["mv","cp","rn","touch"],0,
 "mv does double duty: `mv a.txt b.txt` renames; `mv a.txt dir/` moves. cp copies (leaving the original), and `rn` is not a standard command.",1,"conceptual"],
["m1t9","What does `sudo` do?",
 ["Runs one command with administrator (root) privileges after confirming your password","Permanently makes you the root user","Skips the password prompt for that command","Installs a package"],0,
 "sudo elevates a SINGLE command to root, prompting for your own password. It is temporary borrowed authority, which is why pasting unknown sudo commands is dangerous.",2,"conceptual"],
["m1t9","On Ubuntu, what is the correct order to install a new program?",
 ["sudo apt update, then sudo apt install <name>","sudo apt install, then sudo apt update","apt get <name>","sudo install apt <name>"],0,
 "`apt update` refreshes the catalogue of available packages; `apt install` then fetches and installs. Running install against a stale catalogue can fail or pull old versions.",2,"conceptual"],
["m1t4","`ls -l` shows `-rwxr-xr--` for a file. Who can EXECUTE it?",
 ["Owner and group","Only the owner","Everyone","No one"],0,
 "The triplets after the first char are owner(rwx), group(r-x), others(r--). Both owner and group have the x (execute) bit; 'others' has r-- (read only, no execute).",2,"code-output"],
["m1t4","Why is `chmod 777 file` considered a bad habit?",
 ["It grants read+write+execute to everyone — a security hole","It deletes the file's owner","It makes the file read-only","It only works as root"],0,
 "777 means rwx for owner, group, AND others. Giving every user full control is a classic security smell; grant the least access that makes it work instead.",2,"conceptual"],
["m1t5","What does the pipe do in `cat log.txt | grep ERROR`?",
 ["Feeds cat's output as grep's input, so grep filters those lines","Runs cat and grep independently","Writes cat's output to a file named grep","Counts the lines in log.txt"],0,
 "The `|` connects two commands: the left command's standard output becomes the right command's standard input. Here grep keeps only lines containing ERROR.",1,"conceptual"],
["m1t5","Which pipeline counts how many .txt files are in a folder?",
 ["ls | grep .txt | wc -l","ls -l txt","count *.txt","grep txt | ls"],0,
 "ls lists names, grep keeps the .txt ones, and `wc -l` counts the remaining lines. Composing small tools with pipes is the core Unix idea.",2,"code-output"],
["m1t6","A server says 'port already in use'. What does that actually mean?",
 ["A process is still running and holding that port","The port number is invalid","You lack permission to the folder","The firewall is off"],0,
 "The port is occupied by a running process. You find it (e.g. with ps or lsof) and stop it — the error is about a live process, not a broken port.",2,"conceptual"],
["m1t6","You ran `sleep 300 &`. What does the `&` do?",
 ["Runs the command in the background so your shell stays usable","Runs it as root","Repeats it 300 times","Deletes it after running"],0,
 "A trailing `&` starts the command in the background and immediately returns your prompt. You can then find it with `ps` and stop it with `kill <PID>`.",2,"conceptual"],

// ---------------- MONTH 2: PYTHON & GIT ----------------
["m2t1","What does `range(3)` produce when looped?",
 ["0, 1, 2","1, 2, 3","0, 1, 2, 3","3"],0,
 "range(n) starts at 0 and STOPS BEFORE n, yielding 0,1,2. This off-by-one is a classic beginner and interview trap.",1,"code-output"],
["m2t1","What prints?\n\nx = 7\nprint(x % 2)",
 ["1","0","3","3.5"],0,
 "`%` is modulo — the remainder of division. 7 divided by 2 leaves remainder 1, which is the standard way to test odd/even.",1,"code-output"],
["m2t1","Why does `if x = 5:` raise a SyntaxError?",
 ["= assigns; comparison needs == inside a condition","x is undefined","5 is not a boolean","if requires parentheses"],0,
 "A single `=` is assignment, not comparison. Conditions need `==`. Python deliberately forbids assignment in an `if` test to catch this bug.",2,"conceptual"],
["m2t2","You need to answer 'what value belongs to this key' fast. Which structure?",
 ["dict","list","tuple","set"],0,
 "A dict maps keys to values with average O(1) lookup — exactly 'give me the value FOR this key'. Scanning a list for the same answer is O(n).",1,"conceptual"],
["m2t2","What is `len({1, 2, 2, 3, 3, 3})`?",
 ["3","6","1","2"],0,
 "A set stores only UNIQUE elements, so duplicates collapse: {1,2,3}. Its length is 3. This is the go-to trick for de-duplicating.",2,"code-output"],
["m2t2","Which statement about a tuple is TRUE?",
 ["It cannot be changed after creation (immutable)","It is always sorted","It removes duplicates","It maps keys to values"],0,
 "Tuples are immutable — you cannot append or reassign elements. That immutability lets them be dict keys and signals 'this record is fixed'.",2,"conceptual"],
["m2t3","Why prefer `except ValueError:` over a bare `except:`?",
 ["A bare except also hides bugs you needed to see","Bare except is a syntax error","ValueError is faster","Bare except cannot be used in functions"],0,
 "Catching everything silently swallows real errors (typos, logic bugs), making failures invisible. Catch the SPECIFIC error you expect and let the rest surface.",2,"conceptual"],
["m2t3","What does `with open('f.txt') as f:` give you over a plain open()?",
 ["It automatically closes the file when the block ends","It reads the file faster","It creates the file if missing","It locks the file forever"],0,
 "The `with` context manager guarantees the file is closed even if an error occurs inside the block — preventing leaked file handles.",2,"conceptual"],
["m2t8","In a Python class, what is `self`?",
 ["A reference to the particular object the method is called on","The class itself","A reserved keyword like def","The parent class"],0,
 "`self` is the specific instance in hand, so `self.name` means 'this object's name'. Forgetting it as the first method parameter is the classic OOP error.",2,"conceptual"],
["m2t8","Class vs object — which is correct?",
 ["A class is a blueprint; an object is one concrete instance of it","A class is an instance of an object","They are the same thing","An object is a blueprint for classes"],0,
 "The class defines the shape (attributes + methods); each object is one thing built from that blueprint, with its own data. Cookie-cutter vs cookies.",1,"conceptual"],
["m2t8","Which of these is the OOP pillar 'inheritance'?",
 ["A class extends another, reusing and specialising its behaviour","Hiding internal data behind methods","Bundling data and methods together","Same method name behaving differently per class"],0,
 "Inheritance = a class builds on another (Dog extends Animal). Encapsulation is bundling/hiding; polymorphism is same-name-different-behaviour; abstraction is exposing what, hiding how.",2,"conceptual"],
["m2t5","What is the difference between `git add` and `git commit`?",
 ["add stages which changes to include; commit saves them as a snapshot","They are identical","commit uploads to GitHub; add saves locally","add creates a branch; commit merges it"],0,
 "add chooses WHAT goes into the next snapshot (the staging area); commit records that snapshot with a message. Uploading to GitHub is `git push`.",2,"conceptual"],
["m2t5","Why commit small and often rather than one big commit weekly?",
 ["Small commits are easy to understand and to undo/return to","Git charges per large commit","Big commits corrupt the repo","Small commits run tests automatically"],0,
 "A focused history lets you (and reviewers) understand each change and roll back to a recent good state instead of losing days of work.",1,"conceptual"],
["m2t7","What extra thing does a pull request add beyond a plain merge?",
 ["Review — teammates see and approve changes before they join main","Nothing, it is just a rename","It deletes the branch automatically","It runs the code in production"],0,
 "A PR is a proposal others review and discuss before merging into main. Every company works this way, which is why the branch→PR habit matters.",2,"conceptual"],

// ---------------- MONTH 3: SQL ----------------
["m3t1","If you omit ORDER BY, what order do rows come back in?",
 ["No guaranteed order — you must ORDER BY to control it","Always ascending by primary key","Insertion order, always","Random, but reshuffled each row"],0,
 "SQL gives no ordering guarantee without ORDER BY; the engine may return rows in any order that is convenient. Never rely on 'it looked sorted'.",2,"conceptual"],
["m3t1","Which is correct for filtering text?",
 ["WHERE name = 'ani'","WHERE name = ani","WHERE name == 'ani'","WHERE name is ani"],0,
 "String literals need single quotes, and SQL equality uses a single `=`. `ani` without quotes is read as a column name; `==` is not standard SQL.",1,"code-output"],
["m3t2","INNER JOIN vs LEFT JOIN — the key difference?",
 ["INNER keeps only matching rows; LEFT keeps all left-table rows, filling blanks","LEFT is faster","INNER sorts the result","They are identical for one-to-one data"],0,
 "A LEFT JOIN preserves every row from the left table even with no match (NULLs on the right). INNER drops non-matching rows entirely.",2,"conceptual"],
["m3t2","You JOIN two tables but forget the ON condition. What happens?",
 ["A cross join — every row paired with every row (huge result)","A syntax error stops it","Only matching rows return","The first table is returned unchanged"],0,
 "Without ON, SQL pairs every left row with every right row (a Cartesian product). On big tables this explodes — a classic accidental bug.",3,"conceptual"],
["m3t3","WHERE vs HAVING — which is right?",
 ["WHERE filters rows before grouping; HAVING filters groups after aggregation","They are interchangeable","HAVING runs first","WHERE only works with JOINs"],0,
 "You cannot filter an aggregate (like AVG) with WHERE because it runs before grouping. HAVING filters the grouped results afterward.",2,"conceptual"],
["m3t3","What does GROUP BY do?",
 ["Collapses rows into one summary row per category for aggregates","Sorts the rows","Removes duplicate columns","Joins two tables"],0,
 "GROUP BY buckets rows by a column so aggregates (COUNT, AVG, SUM) are computed per bucket — e.g. average score per course.",1,"conceptual"],
["m3t4","What is a CTE (the WITH clause)?",
 ["A named temporary result used to build a query in readable steps","A permanent table","A type of index","A backup of the database"],0,
 "A CTE (`WITH high AS (...)`) names an intermediate result so a complex query reads as clear steps instead of deeply nested subqueries.",2,"conceptual"],

// ---------------- MONTH 4: DSA ----------------
["m4t2","Why is reading `array[i]` O(1)?",
 ["The address is computed directly from the index, independent of size","Arrays are always small","It scans until it finds index i","Modern CPUs cache everything"],0,
 "An array element's memory address is base + i×size, a direct calculation. It takes the same time whether the array has 10 or 10 million items.",2,"conceptual"],
["m4t3","A hash map turns Two-Sum from O(n^2) into O(n) because…",
 ["You check each number's complement in O(1) instead of comparing all pairs","Hash maps sort the data","It skips half the array","Recursion is used"],0,
 "For each number you ask the dict in O(1) 'have I seen target - n?'. One pass replaces the nested loop that compared every pair.",2,"conceptual"],
["m4t3","What is `len([10,20,30][-1])`... i.e. what is `[10,20,30][-1]`?",
 ["30","10","3","an error"],0,
 "Negative indices count from the end: -1 is the last element. This is a common way to grab the final item without computing the length.",1,"code-output"],
["m4t5","What two parts must every correct recursion have?",
 ["A base case that stops, and a step that shrinks toward it","A loop and a counter","Two function calls","A global variable"],0,
 "Without a base case recursion never stops (stack overflow); without a shrinking step it never reaches the base case. Both are required.",2,"conceptual"],
["m4t5","What does this return?\n\ndef f(n):\n    if n <= 1: return 1\n    return n * f(n-1)\n\nf(4)",
 ["24","10","4","1"],0,
 "This is factorial: 4×3×2×1 = 24. Tracing it: f(4)=4·f(3)=4·3·f(2)=4·3·2·f(1)=4·3·2·1.",2,"code-output"],
["m4t6","Why must binary search's input be sorted?",
 ["It discards a half based on comparing to the middle, which only works if ordered","Sorting makes it use less memory","Unsorted arrays cannot be indexed","It does not need to be sorted"],0,
 "Each step decides 'go left or right' by comparing to the middle element. That decision is only valid if the data is ordered; on unsorted input it gives wrong answers.",2,"conceptual"],
["m4t6","What is binary search's time complexity and why?",
 ["O(log n) — each step discards half the remaining items","O(n) — it may scan everything","O(n^2) — nested comparisons","O(1) — it jumps straight to the answer"],0,
 "Halving the search space each step means ~20 steps for a million items. Doubling the data adds just one step — the signature of logarithmic growth.",2,"big-o"],
["m4t7","Stack vs queue — which pairing is correct?",
 ["Stack = last-in-first-out; queue = first-in-first-out","Stack = FIFO; queue = LIFO","Both are FIFO","Both are LIFO"],0,
 "A stack is LIFO (like undo — the last action reverses first); a queue is FIFO (like a line — first to arrive is served first).",1,"conceptual"],

// ---------------- MONTH 5: SHIP IT ----------------
["m5t1","What problem do containers solve?",
 ["They package an app with its dependencies so it runs the same everywhere","They make code run faster","They replace the operating system","They encrypt your code"],0,
 "A container bundles code + libraries + environment, killing 'works on my machine'. It is the venv idea taken to the whole environment.",1,"conceptual"],
["m5t1","Image vs container?",
 ["An image is the blueprint; a container is a running instance of it","A container is the blueprint; an image runs it","They are identical","An image is a running container"],0,
 "You build an IMAGE once (the recipe) and run many CONTAINERS from it (running instances) — like a class and its objects.",2,"conceptual"],
["m5t2","In a Dockerfile, why copy requirements and install deps BEFORE copying the rest of the code?",
 ["So Docker caches the install layer and only re-runs it when deps change","It is required syntax","Otherwise pip fails","To make the image bigger"],0,
 "Docker caches each layer. Installing deps before copying source means a code change reuses the cached dependency layer, making rebuilds fast.",3,"conceptual"],
["m5t8","404 vs 500 — which is correct?",
 ["404 = the requested thing does not exist (client side); 500 = the server itself failed","404 = server crash; 500 = not found","Both mean the server is down","404 = success; 500 = redirect"],0,
 "4xx codes blame the request (404 = not found); 5xx codes blame the server (500 = it errored while handling the request). Knowing this speeds debugging.",2,"conceptual"],
["m5t8","What is an API, versus a web page?",
 ["A URL that returns structured data (often JSON) for programs, not HTML for humans","A faster kind of website","A database","A programming language"],0,
 "An API endpoint returns data (JSON) meant to be consumed by code. A web page returns HTML meant to be rendered for a person.",1,"conceptual"],
];
