// FORAGE — Software Engineer path, Module 1: Big-O & Algorithmic Thinking
// Facts grounded in standard CS complexity theory (verifiable via any algorithms reference);
// every timing/complexity claim demonstrated by actually running and timing real Python code.
// Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "swe-bigo", title: "Big-O & Algorithmic Thinking",
  why: "Every technical interview and every real engineering decision about 'will this scale' comes down to reasoning about how an algorithm's cost grows with input size. This module builds that reasoning from zero, with every claim demonstrated by actually timing real code, not just quoted from a table.",
  topics: [
  {
    id: "swe-what-is-bigo", title: "What Big-O actually measures",
    concept: "Big-O notation describes how an algorithm's RUNTIME (or memory) grows as the input size (n) grows — not the exact runtime in seconds (which depends on hardware), but the SHAPE of growth. O(n) means runtime grows roughly proportionally to input size; O(n²) means it grows roughly with the square of input size; O(1) means it doesn't grow with input size at all. This lets you compare algorithms in a way that's independent of any specific machine.",
    analogy: "Think of Big-O like comparing 'how much longer does it take to photocopy documents as the stack grows' rather than 'how many seconds exactly.' A photocopier that takes roughly twice as long for twice as many pages is O(n) — linear. One where doubling the pages QUADRUPLES the time (because it re-checks every prior page for each new page) is O(n²) — quadratic. The exact seconds depend on the copier model; the SHAPE of how time grows is what Big-O captures.",
    examples: [
      {code: "import time\n\ndef sum_list(lst):          # O(n) -- one pass through the list\n    total = 0\n    for x in lst:\n        total += x\n    return total\n\nfor n in [1_000, 10_000, 100_000, 1_000_000]:\n    lst = list(range(n))\n    start = time.perf_counter()\n    sum_list(lst)\n    elapsed = time.perf_counter() - start\n    print(f\"n={n:>9,}: {elapsed*1000:.2f} ms\")", note: "As n grows 10x each time (1,000 -> 10,000 -> 100,000 -> 1,000,000), the runtime should grow roughly 10x each time too, since this is a single pass through the list -- O(n). Real timing confirms the theoretical shape, not just asserts it."},
      {code: "def has_duplicate_slow(lst):    # O(n^2) -- checks every pair\n    for i in range(len(lst)):\n        for j in range(i + 1, len(lst)):\n            if lst[i] == lst[j]:\n                return True\n    return False\n\nimport time\nfor n in [500, 1_000, 2_000, 4_000]:\n    lst = list(range(n))   # no duplicates -- worst case, checks everything\n    start = time.perf_counter()\n    has_duplicate_slow(lst)\n    elapsed = time.perf_counter() - start\n    print(f\"n={n:>6,}: {elapsed*1000:.2f} ms\")", note: "As n DOUBLES each time (500 -> 1,000 -> 2,000 -> 4,000), the runtime should roughly QUADRUPLE each time -- the signature of O(n^2), since nested loops mean the work grows with n*n, not n."}
    ],
    mistakes: ["Confusing Big-O with exact runtime in seconds — it describes GROWTH SHAPE, not an exact speed, and is deliberately hardware-independent.","Assuming a lower-order algorithm is always faster in absolute terms — for very small n, an O(n²) algorithm with low overhead can beat an O(n log n) one with high overhead; Big-O describes behavior as n grows LARGE.","Only ever discussing Big-O in the abstract — actually timing code (like these examples) builds real intuition that abstract tables don't."],
    handsOn: "Run both timing examples yourself. For the O(n) example, confirm runtime roughly scales with n. For the O(n²) example, confirm runtime roughly scales with n² (quadruples when n doubles). Then write your own O(n) function (e.g. finding the max of a list) and time it at a few input sizes to confirm the same linear pattern.",
    doneWhen: "You can explain what Big-O measures (growth shape, not exact speed) and have empirically confirmed O(n) vs O(n²) growth by timing real code.",
    checks: [
      {q: "An O(n²) algorithm's input size doubles. What happens to its runtime, roughly?", a: "It roughly quadruples (4x) — quadratic growth means runtime scales with the SQUARE of the input size, so doubling n roughly quadruples the work (2² = 4)."}
    ],
    keyTakeaways: ["Big-O describes how runtime/memory grows with input size, not exact seconds.", "O(n) grows proportionally; O(n²) grows with the square of input size.", "Timing real code empirically confirms theoretical complexity, building real intuition."],
    resources: [
      {label: "MIT OCW — 6.006 Introduction to Algorithms", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", kind: "course"},
      {label: "Big-O Cheat Sheet — common complexities reference", url: "https://www.bigocheatsheet.com/", kind: "reference"}
    ]
  },
  {
    id: "swe-common-complexities", title: "The complexity classes you'll actually see",
    concept: "In roughly increasing order of cost: O(1) constant (array index lookup), O(log n) logarithmic (binary search — halving the search space each step), O(n) linear (a single pass), O(n log n) linearithmic (efficient sorting like merge sort), O(n²) quadratic (nested loops over the same data), O(2ⁿ) exponential (naive recursive solutions that re-solve the same subproblem repeatedly). Recognizing these patterns in your own code — 'I have a loop inside a loop over the same data' means O(n²) — is the actual interview and engineering skill.",
    analogy: "O(1) is looking up a word by its exact page number — instant, regardless of dictionary size. O(log n) is looking up a word by flipping to the middle and eliminating half the dictionary each time (binary search). O(n) is reading the dictionary cover to cover once. O(n²) is, for every word, reading the ENTIRE dictionary again to check something about it. The pattern of your ACCESS STRATEGY determines which class you're in, not the size of the dictionary itself.",
    examples: [
      {code: "def binary_search(sorted_lst, target):   # O(log n)\n    lo, hi = 0, len(sorted_lst) - 1\n    steps = 0\n    while lo <= hi:\n        steps += 1\n        mid = (lo + hi) // 2\n        if sorted_lst[mid] == target:\n            return mid, steps\n        elif sorted_lst[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1, steps\n\nfor n in [1_000, 1_000_000, 1_000_000_000]:\n    lst = list(range(n))\n    _, steps = binary_search(lst, n - 1)\n    print(f\"n={n:>15,}: {steps} steps\")", note: "Notice how SLOWLY the step count grows even as n grows by 1000x each time -- that's the hallmark of O(log n): doubling n only adds roughly ONE more step, because each step eliminates HALF the remaining search space."},
      {code: "def fib_naive(n):        # O(2^n) -- recomputes the same subproblems repeatedly\n    if n <= 1:\n        return n\n    return fib_naive(n - 1) + fib_naive(n - 2)\n\nimport time\nfor n in [20, 25, 30]:\n    start = time.perf_counter()\n    fib_naive(n)\n    elapsed = time.perf_counter() - start\n    print(f\"fib({n}): {elapsed*1000:.1f} ms\")", note: "Each +5 to n roughly multiplies the runtime by ~11x (since 2^5=32, with real overhead)-- explosive growth, the signature of exponential complexity. This naive recursive Fibonacci recomputes the same smaller subproblems over and over, which is exactly the trap a well-designed algorithm (dynamic programming) avoids."}
    ],
    mistakes: ["Writing nested loops over the same collection without noticing it's O(n²) — this is the single most common accidental-complexity mistake.","Using naive recursion that re-solves identical subproblems (like naive Fibonacci) without realizing it's exponential — a huge, often invisible cost.","Assuming O(log n) is 'basically O(n)' — the difference is enormous at scale (log₂ of a billion is only ~30)."],
    handsOn: "Run the binary_search example and observe how few steps it takes even for n = 1 billion. Run the naive Fibonacci example and observe the runtime explosion as n grows by just 5 each time. Write one sentence naming a nested-loop pattern you've seen (or written) that was accidentally O(n²).",
    doneWhen: "You can name the common complexity classes in order and correctly identify O(n²) nested-loop patterns and O(2ⁿ) naive-recursion patterns in real code.",
    checks: [
      {q: "Why does binary search (O(log n)) barely slow down even as the input grows from 1,000 to 1 billion?", a: "Each step of binary search eliminates HALF the remaining search space, so the number of steps needed grows only logarithmically — doubling n adds roughly one more step, which is why log n grows so slowly even for enormous inputs."}
    ],
    keyTakeaways: ["Complexity classes in rough order: O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ).", "Nested loops over the same data are the most common accidental O(n²) pattern.", "Naive recursion that re-solves identical subproblems is a common hidden exponential-cost trap."],
    resources: [
      {label: "Big-O Cheat Sheet", url: "https://www.bigocheatsheet.com/", kind: "reference"},
      {label: "MIT OCW — 6.006 Introduction to Algorithms", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", kind: "course"}
    ]
  },
  {
    id: "swe-arrays-strings", title: "Arrays and strings — the interview workhorses",
    concept: "Arrays (Python lists) support O(1) index access (`lst[i]`) but O(n) insertion/deletion at the FRONT or middle (everything after has to shift). Strings in Python are IMMUTABLE — every 'modification' (like `s += char` in a loop) conceptually creates a brand-new string, which is O(n) per operation, making naive string-building an O(n²) ALGORITHM overall. The standard, always-safe fix is building a LIST of pieces and joining once at the end with `''.join(...)`, which is a genuine O(n) algorithm regardless of implementation details.",
    analogy: "A Python list is like a row of numbered parking spots — jumping straight to spot #47 is instant, but inserting a new car at spot #1 means physically shoving every other car down one spot. A Python string is like a printed, laminated sign — you can't edit one letter; 'changing' it means printing an entirely new sign from scratch every time, which gets expensive if you do it repeatedly in a loop.",
    examples: [
      {code: "import time\n\ndef build_string_naive(n):     # O(n^2) as an ALGORITHM -- each += conceptually makes a new string\n    s = \"\"\n    for i in range(n):\n        s += \"x\"\n    return s\n\ndef build_string_fast(n):      # O(n) -- build a list, join once\n    parts = []\n    for i in range(n):\n        parts.append(\"x\")\n    return \"\".join(parts)\n\nfor n in [50_000, 100_000, 200_000, 400_000]:\n    t0 = time.perf_counter(); build_string_naive(n); t1 = time.perf_counter()\n    t2 = time.perf_counter(); build_string_fast(n); t3 = time.perf_counter()\n    print(f\"n={n:>7,}: naive={((t1-t0)*1000):.2f}ms  fast={((t3-t2)*1000):.2f}ms\")", note: "The naive version is consistently slower (roughly 1.5-2x here) but NOT dramatically quadratic at these sizes -- worth knowing honestly: CPython has a specific optimization that resizes a string in place when it has only one reference (similar to how list.append() grows), which softens the real-world cost of this exact pattern. The underlying ALGORITHM is still O(n^2) in general (it degrades badly if the string has extra references, or in most other languages/implementations) -- ''.join() remains the correct, always-safe idiom regardless of implementation quirks."},
      {code: "lst = [1, 2, 3, 4, 5]\nprint(lst[2])          # O(1) -- index access is instant\n\nlst.insert(0, 0)       # O(n) -- everything shifts right by one\nprint(lst)              # [0, 1, 2, 3, 4, 5]\n\nlst.append(6)           # O(1) amortized -- adding to the END is cheap\nprint(lst)", note: "insert(0, ...) at the front is O(n) because every existing element must shift; append() at the end is O(1) amortized (occasionally the underlying array resizes, but averaged over many appends it's constant time) -- WHERE you insert matters a lot for cost."}
    ],
    mistakes: ["Building a string with repeated `+=` inside a loop — accidentally O(n²); use a list + `''.join()` instead.","Using `list.insert(0, x)` repeatedly in a loop without realizing each call is O(n) — an accidental O(n²) pattern in disguise.","Forgetting that Python strings are immutable — every apparent 'mutation' actually creates a new string object."],
    handsOn: "Run both string-building functions and confirm the timing gap grows as n increases. Then find (or recall) a piece of code you've written that repeatedly used += on a string in a loop, and rewrite it using the list+join pattern.",
    doneWhen: "You can explain why naive string concatenation in a loop is O(n²), and can identify and fix the pattern using list+join.",
    checks: [
      {q: "Why is building a string with `s += \"x\"` inside a loop of n iterations an accidental O(n²) operation, not O(n)?", a: "Python strings are immutable, so each += creates an entirely new string by copying the old one plus the addition — that single copy is O(current length), and doing this n times (with growing length each time) sums to O(n²) total work, not O(n)."}
    ],
    keyTakeaways: ["Array index access is O(1); inserting at the front/middle is O(n) due to shifting.", "Python strings are immutable — naive concatenation in a loop is an accidental O(n²) trap.", "The fix: build a list of pieces and join once with ''.join()."],
    resources: [
      {label: "Python docs — Time complexity of common list operations", url: "https://wiki.python.org/moin/TimeComplexity", kind: "docs"},
      {label: "Python docs — str.join()", url: "https://docs.python.org/3/library/stdtypes.html#str.join", kind: "docs"}
    ]
  },
  {
    id: "swe-hash-maps", title: "Hash maps — trading memory for speed",
    concept: "A hash map (Python `dict`) gives O(1) AVERAGE-case lookup, insertion, and deletion by key — instead of scanning a list to find a match (O(n)), a hash map computes a hash of the key that tells it almost exactly where to look. This is arguably THE single most useful data structure for turning an O(n²) brute-force solution into an O(n) one: whenever you catch yourself writing 'for each item, search the rest of the list for a match,' a hash map converts that inner search into an O(1) lookup.",
    analogy: "Searching an unsorted list for a name is like flipping through every page of a phone book one by one. A hash map is like a phone book with a magic index that tells you EXACTLY which page to open, instantly, no matter how thick the book is — you trade some extra memory (the index) for a massive speed advantage on lookups.",
    examples: [
      {code: "def has_duplicate_slow(lst):     # O(n^2) from the earlier lesson\n    for i in range(len(lst)):\n        for j in range(i + 1, len(lst)):\n            if lst[i] == lst[j]:\n                return True\n    return False\n\ndef has_duplicate_fast(lst):     # O(n) using a hash set\n    seen = set()\n    for x in lst:\n        if x in seen:            # O(1) average lookup\n            return True\n        seen.add(x)               # O(1) average insert\n    return False\n\nimport time\nlst = list(range(20_000)) + [5]   # a duplicate near the front, worst case for slow version's early exit avoided by design\nt0 = time.perf_counter(); has_duplicate_slow(lst[:4000]); t1 = time.perf_counter()\nt2 = time.perf_counter(); has_duplicate_fast(lst[:4000]); t3 = time.perf_counter()\nprint(f\"slow (O(n^2)): {(t1-t0)*1000:.2f} ms\")\nprint(f\"fast (O(n)):   {(t3-t2)*1000:.2f} ms\")", note: "Same problem, two very different costs: the O(n^2) version checks every pair; the O(n) version uses a hash set to remember what it's already seen, turning the inner 'have I seen this?' check into an O(1) average lookup. The fast version should be dramatically quicker at n=4,000."},
      {code: "# Classic pattern: counting frequencies with a dict\nwords = [\"apple\", \"banana\", \"apple\", \"cherry\", \"banana\", \"apple\"]\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1     # O(1) average per lookup+update\nprint(counts)   # {'apple': 3, 'banana': 2, 'cherry': 1}", note: "counts.get(w, 0) is an O(1) average lookup that returns 0 if the key isn't present yet -- this single-pass frequency-counting pattern (O(n) total) is one of the most common hash-map uses in real code and interviews alike."}
    ],
    mistakes: ["Reaching for nested loops to find 'have I seen this before' when a hash set/dict would do it in O(1) average — one of the most common interview 'optimize this' moments.","Forgetting hash map operations are AVERAGE-case O(1), not worst-case guaranteed — pathological hash collisions can degrade this, though it's rare in practice with Python's built-in dict.","Using a list instead of a set purely for membership checks ('x in my_list') — that's O(n) per check; a set makes it O(1) average."],
    handsOn: "Run both has_duplicate implementations and confirm the fast version is meaningfully quicker at n=4,000. Then take any nested-loop pattern you've written (or the earlier example) and rewrite it using a hash set/dict to eliminate the inner loop.",
    doneWhen: "You can explain why hash maps give O(1) average lookup, and have converted an O(n²) nested-loop pattern into an O(n) hash-map-based one.",
    checks: [
      {q: "Why does using a hash set for 'have I seen this value before' turn an O(n²) nested-loop check into an O(n) one?", a: "The inner 'search the rest of the list for a match' becomes an O(1) average hash-set lookup instead of an O(n) scan — doing that O(1) check once per item in a single pass gives O(n) total instead of O(n) checks each costing O(n), which multiplies to O(n²)."}
    ],
    keyTakeaways: ["Hash maps (dict/set) give O(1) average-case lookup, insertion, and deletion.", "The 'for each item, check if seen before' pattern is the classic O(n²)-to-O(n) hash-map optimization.", "Membership checks ('x in ...') are O(n) on a list but O(1) average on a set."],
    resources: [
      {label: "Python docs — dict / hash table implementation notes", url: "https://wiki.python.org/moin/TimeComplexity", kind: "docs"},
      {label: "NeetCode — Arrays & Hashing pattern", url: "https://neetcode.io/roadmap", kind: "practice"}
    ]
  },
  {
    id: "swe-two-pointer-sliding-window", title: "Two pointers & sliding window — the O(n²)-to-O(n) toolkit",
    concept: "Beyond hash maps, two more patterns routinely turn a brute-force O(n²) solution into O(n): TWO POINTERS (typically on a sorted array — one pointer starts at each end and they move toward each other based on a comparison) and SLIDING WINDOW (maintaining a contiguous range/'window' over an array or string, expanding and shrinking it as you scan once, instead of re-scanning from scratch for every starting point). Both share the same core idea: do a single, smart pass instead of restarting a nested scan.",
    analogy: "Two pointers on a sorted array is like two people searching a sorted bookshelf from opposite ends, walking toward each other and comparing notes — far faster than one person checking every possible PAIR of books. A sliding window is like reading a long sentence through a movable window that shows only a few words at a time, sliding it one word at a step instead of re-reading the whole sentence from scratch for every possible window position.",
    examples: [
      {code: "def two_sum_sorted(sorted_lst, target):    # O(n) -- two pointers\n    lo, hi = 0, len(sorted_lst) - 1\n    while lo < hi:\n        s = sorted_lst[lo] + sorted_lst[hi]\n        if s == target:\n            return (lo, hi)\n        elif s < target:\n            lo += 1          # need a bigger sum -> move left pointer up\n        else:\n            hi -= 1          # need a smaller sum -> move right pointer down\n    return None\n\nnums = [2, 4, 7, 11, 15, 20]\nprint(two_sum_sorted(nums, 18))   # finds 7 + 11 = 18 -> (2, 3)", note: "Instead of checking every pair (O(n^2)), the two pointers each move AT MOST n times total, giving O(n). The key insight: on a SORTED array, if the current sum is too small, only moving the LEFT pointer up can help; if too large, only moving the RIGHT pointer down can help -- so no pair is ever redundantly re-checked."},
      {code: "def longest_unique_substring(s):    # O(n) -- sliding window\n    seen = {}\n    start = 0\n    best = 0\n    for end, ch in enumerate(s):\n        if ch in seen and seen[ch] >= start:\n            start = seen[ch] + 1     # shrink window past the repeat\n        seen[ch] = end\n        best = max(best, end - start + 1)\n    return best\n\nprint(longest_unique_substring(\"abcabcbb\"))   # 3 -- \"abc\"\nprint(longest_unique_substring(\"bbbbb\"))       # 1 -- \"b\"\nprint(longest_unique_substring(\"pwwkew\"))      # 3 -- \"wke\"", note: "The window [start, end] expands by one character each step and only shrinks (moving start forward) when a repeat is found -- a SINGLE pass, O(n), instead of checking every possible substring (which would be O(n^2) or worse). This is a genuinely common real interview question, and the three test cases confirm it against well-known expected answers."}
    ],
    mistakes: ["Trying two pointers on an UNSORTED array without sorting first (or realizing the technique needs that ordering to work) — it relies on the sorted-order guarantee to safely eliminate pairs.","Forgetting to properly shrink the sliding window's start when a repeat/violation is found — a common off-by-one source of bugs.","Reaching for brute-force nested loops out of habit before checking whether two-pointer or sliding-window applies — recognizing WHEN these patterns fit is the actual interview skill."],
    handsOn: "Run both examples and confirm the outputs match the comments. Then take the two_sum_sorted function and trace through it by hand on a small array, writing down what lo/hi/sum are at each step, to build real intuition for why the sorted-order guarantee makes the technique correct.",
    doneWhen: "You can implement a basic two-pointer solution on a sorted array and a basic sliding-window solution on a string, and explain in your own words why each avoids the O(n²) brute-force cost.",
    checks: [
      {q: "Why does the two-pointer technique for two_sum require the array to be SORTED first?", a: "The technique relies on being able to safely decide which pointer to move based on whether the current sum is too small or too large — that logic only works correctly because sorted order guarantees moving the left pointer up always increases the sum and moving the right pointer down always decreases it."}
    ],
    keyTakeaways: ["Two pointers (on sorted data) and sliding window are single-pass O(n) alternatives to O(n²) brute force.", "Two pointers requires sorted order to safely decide which pointer to move.", "Sliding window expands and shrinks a contiguous range in one pass instead of re-scanning from every start."],
    resources: [
      {label: "NeetCode — Two Pointers & Sliding Window patterns", url: "https://neetcode.io/roadmap", kind: "practice"},
      {label: "LeetCode — Explore: Two Pointer technique", url: "https://leetcode.com/explore/learn/card/array-and-string/", kind: "practice"}
    ]
  }
  ]
};
