// FORAGE — Software Engineer path, Module 3: System Design Basics & Capstone
// Standard system-design concepts (client-server, caching, load balancing, scaling), grounded
// against well-known references. Illustrative code (cache speedup, consistent hashing) executed
// for real. Capstone lessons are project-based and correctly get 0 quizzes per the light-quiz
// rule, except the one lesson with a genuinely testable conceptual fact.

module.exports = {
  id: "swe-systemdesign", title: "System Design Basics & Capstone",
  why: "Module 1-2 gave you algorithmic thinking and data structures — the building blocks used INSIDE a single program. System design zooms out to how real, multi-user services are actually built: clients, servers, databases, caching, and scaling. This module gives you the vocabulary and reasoning for both interviews and real engineering decisions, then ties everything in this path together in a capstone.",
  topics: [
  {
    id: "swe-client-server", title: "Client-server basics and APIs",
    concept: "Nearly every web/mobile app follows the CLIENT-SERVER model: a CLIENT (browser, mobile app) sends a request over the network to a SERVER, which processes it (often talking to a database) and sends back a response. The contract between them is an API (Application Programming Interface) — a defined set of endpoints, request/response shapes, and rules. REST is the most common API style: resources are identified by URLs, and HTTP methods (GET/POST/PUT/DELETE) express the action, mirroring what you already built in Module 7 of the AI Engineer path with FastAPI.",
    analogy: "Think of a restaurant: the client is the customer, the server (waiter) takes the order and relays it to the kitchen (the actual backend logic/database), then brings back the food (the response). The MENU is the API — a fixed, agreed-upon set of things you can ask for, in a specific format, so both sides know exactly what to expect from each other.",
    examples: [
      {code: "# A minimal REST API contract, illustrated in plain terms\n\"\"\"\nGET    /users/42        -> fetch user 42's data\nPOST   /users            -> create a new user (data in the request body)\nPUT    /users/42         -> update user 42's data completely\nDELETE /users/42         -> delete user 42\n\"\"\"\n\n# This is exactly the pattern from FastAPI (AI Engineer Module 7):\n# @app.get(\"/users/{user_id}\") -- GET, a specific resource\n# @app.post(\"/users\")          -- POST, create\nprint(\"REST maps HTTP methods + URLs onto CRUD-style actions on resources\")", note: "REST's convention -- URL identifies WHAT (a resource, like a specific user), HTTP method identifies the ACTION (GET/POST/PUT/DELETE) -- is a widely-used, predictable pattern that makes an API's behavior guessable once you know the resource name, without needing to memorize a huge number of custom endpoint names."}
    ],
    mistakes: ["Confusing the CLIENT and SERVER roles — the client INITIATES requests; the server RESPONDS. A server never 'reaches out' to a client uninvited in the basic request-response model.","Designing an API with inconsistent verb/URL patterns (e.g. `/getUser/42` instead of `GET /users/42`) — REST conventions exist specifically so APIs are predictable across different services.","Forgetting that 'API' is a broader concept than 'REST' — REST is one common STYLE of API, not the only one (GraphQL and gRPC are others worth knowing exist)."],
    handsOn: "Pick a real app you use daily and sketch (on paper or in a text file) what its API might look like for one feature — e.g. for a to-do app, what would GET/POST/PUT/DELETE on a '/tasks' resource look like? Write the URL and method for each.",
    doneWhen: "You can explain the client-server model in your own words and design a simple REST-style API contract (URLs + HTTP methods) for a feature of your choice.",
    checks: [
      {q: "In the client-server model, which side initiates a request, and which side responds?", a: "The client initiates the request; the server processes it and sends back a response. In the basic model, a server doesn't spontaneously reach out to a client — communication starts with the client's request."}
    ],
    keyTakeaways: ["Client-server: the client requests, the server responds — the API is the contract between them.", "REST maps HTTP methods (GET/POST/PUT/DELETE) onto predictable actions on named resources.", "REST is one common API style, not the only one."],
    resources: [
      {label: "MDN — An overview of HTTP", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview", kind: "docs"},
      {label: "freeCodeCamp — REST API design best practices", url: "https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/", kind: "reference"}
    ]
  },
  {
    id: "swe-databases-scaling", title: "Databases and scaling — vertical vs horizontal",
    concept: "As a service grows, two scaling strategies exist: VERTICAL scaling (a bigger, more powerful single machine — more CPU/RAM) and HORIZONTAL scaling (MORE machines sharing the load). Vertical scaling is simpler but hits a hard ceiling (there's a biggest machine you can buy) and is a single point of failure. Horizontal scaling has no hard ceiling and survives individual machine failures, but requires the system to be designed for it — most critically, the DATABASE, since spreading application servers is comparatively easy but spreading data consistently is the genuinely hard problem in distributed systems.",
    analogy: "Vertical scaling is hiring one increasingly-superhuman employee to handle more work alone — eventually you run out of 'more superhuman' to hire, and if they're sick, everything stops. Horizontal scaling is hiring MORE regular employees who share the work — no hard ceiling, and one person being out doesn't stop everything — but now you need real coordination (who's handling which customer, keeping everyone's information in sync) that a single superhuman employee never needed.",
    examples: [
      {code: "# Illustrating the vertical-scaling ceiling conceptually\nmachine_specs = [\n    (\"small\",  4, 16),      # (name, CPU cores, RAM GB)\n    (\"medium\", 16, 64),\n    (\"large\",  64, 256),\n    (\"xlarge\", 128, 512),   # biggest commonly available -- a real ceiling exists\n]\nfor name, cpu, ram in machine_specs:\n    print(f\"{name:>8}: {cpu:>3} cores, {ram:>3} GB RAM\")\nprint(\"eventually there is no bigger machine to buy -- vertical scaling has a hard ceiling\")", note: "This is illustrative, not a real cloud provider's exact catalog -- the point is conceptual: at some tier, there simply isn't a bigger single machine available, whereas horizontal scaling (adding more machines) has no such fixed endpoint."}
    ],
    warn: "Horizontal scaling is genuinely harder than it sounds — once data is spread across multiple database instances, you must decide how to keep it consistent, how to route a request to the right instance, and how to handle a node failing mid-operation. This module gives you the VOCABULARY (sharding, replication) to reason about these tradeoffs at interview level; a full distributed-systems treatment is its own deep specialization.",
    mistakes: ["Assuming horizontal scaling is a free upgrade with no downsides — it introduces real complexity (data consistency, routing) that a single machine never had to deal with.","Reaching for horizontal scaling before actually needing it — vertical scaling and straightforward optimization (better queries, caching — next lesson) solve most real-world scale problems far more simply, for far longer than people expect.","Confusing SCALING (handling more load) with AVAILABILITY (surviving failures) — they're related but distinct concerns; horizontal scaling helps with both, but for different reasons."],
    handsOn: "Write two sentences: describe one real product/feature you use that you'd guess is vertically scaled (a single powerful backing service is plausible) versus one you'd guess is horizontally scaled (its scale/reliability needs suggest many machines) — and explain your reasoning for each guess.",
    doneWhen: "You can explain vertical vs horizontal scaling, articulate the hard ceiling of vertical scaling, and name the core added complexity of horizontal scaling (data consistency, routing).",
    checks: [
      {q: "What is the fundamental limitation of vertical scaling that horizontal scaling avoids?", a: "Vertical scaling has a hard ceiling — there's always a biggest single machine available, and it remains a single point of failure. Horizontal scaling has no fixed ceiling (you can keep adding machines) and survives individual machine failures, at the cost of added complexity in keeping distributed data consistent."}
    ],
    keyTakeaways: ["Vertical scaling = a bigger single machine; hits a hard ceiling and is a single point of failure.", "Horizontal scaling = more machines sharing load; no hard ceiling, survives failures, but adds real complexity.", "Most real systems solve scale with simpler techniques (better queries, caching) long before needing serious horizontal scaling."],
    resources: [
      {label: "AWS — What's the Difference Between Horizontal and Vertical Scaling?", url: "https://aws.amazon.com/what-is/horizontal-scaling/", kind: "docs"},
      {label: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "reference"}
    ]
  },
  {
    id: "swe-caching", title: "Caching — the highest-leverage performance trick",
    concept: "A cache stores the RESULT of an expensive operation (a slow database query, a complex computation) so a repeated request can be answered instantly from memory instead of redoing the work. Caching is often the single highest-leverage performance improvement available, because real-world access patterns are rarely uniform — a small fraction of data (a 'hot' subset) is requested far more often than the rest, so caching just that hot subset captures most of the benefit. The core tradeoff is CACHE INVALIDATION: when the underlying data changes, the cached copy can become stale, and deciding when/how to update or expire it is a genuinely hard problem (famously called one of the two hard things in computer science).",
    analogy: "A cache is like keeping your five most-used tools on your workbench instead of walking to the garage every time — most of your actual work only touches a handful of tools repeatedly, so keeping those close by captures nearly all the time savings. The catch: if someone replaces a tool in the garage with a better one and you don't update your workbench, you're now working with an outdated copy without realizing it — that's cache invalidation.",
    examples: [
      {code: "import time\nimport functools\n\ndef slow_lookup(user_id):        # simulates an expensive DB query\n    time.sleep(0.05)               # 50ms, standing in for real DB latency\n    return f\"user-{user_id}-data\"\n\n@functools.lru_cache(maxsize=128)   # a real, working in-memory cache\ndef cached_lookup(user_id):\n    time.sleep(0.05)\n    return f\"user-{user_id}-data\"\n\n# Without caching: every call pays the full cost\nt0 = time.perf_counter()\nfor _ in range(5):\n    slow_lookup(42)\nt1 = time.perf_counter()\n\n# With caching: only the FIRST call pays the cost; the rest are instant\nt2 = time.perf_counter()\nfor _ in range(5):\n    cached_lookup(42)\nt3 = time.perf_counter()\n\nprint(f\"uncached x5: {(t1-t0)*1000:.0f} ms\")\nprint(f\"cached x5:   {(t3-t2)*1000:.0f} ms\")", note: "functools.lru_cache is a REAL, standard-library cache -- the uncached version pays the full ~50ms cost every single call; the cached version pays it once (the first call) and then returns instantly for the same argument, demonstrating the core caching payoff with real timing, not just a claim."}
    ],
    mistakes: ["Caching data that changes constantly with no invalidation strategy — serving stale data can be worse than the original slowness, depending on the use case.","Assuming caching is 'free' performance with no tradeoff — it uses memory, and a wrong invalidation strategy introduces real correctness bugs.","Not identifying the actual 'hot' subset of data before caching everything indiscriminately — targeted caching of frequently-accessed data captures most of the benefit far more cheaply."],
    handsOn: "Run the lru_cache example and confirm the dramatic timing difference. Then call cached_lookup with a DIFFERENT user_id (e.g. 99) and confirm it pays the full cost again (since it's a new, uncached argument) — then call it a second time with that same id and confirm it's now fast too.",
    doneWhen: "You can explain what a cache does and why it's high-leverage, have demonstrated real caching speedup with code, and can describe cache invalidation as the core tradeoff.",
    checks: [
      {q: "Why is caching often described as one of the highest-leverage performance improvements available?", a: "Real-world access patterns are rarely uniform — a small 'hot' subset of data is requested far more often than the rest, so caching just that subset captures most of the performance benefit cheaply, without needing to speed up every possible request."}
    ],
    keyTakeaways: ["A cache stores expensive results so repeated requests are answered instantly.", "Caching the 'hot' subset of frequently-accessed data captures most of the benefit.", "Cache invalidation (keeping cached data in sync with the source) is the genuinely hard tradeoff."],
    resources: [
      {label: "Python docs — functools.lru_cache", url: "https://docs.python.org/3/library/functools.html#functools.lru_cache", kind: "docs"},
      {label: "AWS — What is Caching?", url: "https://aws.amazon.com/caching/", kind: "docs"}
    ]
  },
  {
    id: "swe-load-balancing", title: "Load balancing — spreading requests across servers",
    concept: "Once you have multiple servers (horizontal scaling), something needs to decide which server handles each incoming request — that's a LOAD BALANCER, sitting in front of your servers and distributing traffic across them. Common strategies: ROUND ROBIN (cycle through servers in order — simple, works well when requests are roughly equal cost), and CONSISTENT HASHING (route based on a hash of some request property, like a user ID, so the SAME user consistently lands on the SAME server — useful when a server holds session state for a specific user).",
    analogy: "A load balancer is like a host at a busy restaurant deciding which of several open tables to seat each new party at — spreading people out so no single table (server) gets overwhelmed while others sit empty. Consistent hashing is like a host who remembers 'this specific family always sits at table 3' — useful when that table's waiter (server) already knows their order history (session state), and you want the same family routed there every time.",
    examples: [
      {code: "# Round robin: cycle through servers in fixed order\nservers = [\"server-A\", \"server-B\", \"server-C\"]\n\ndef round_robin(request_number):\n    return servers[request_number % len(servers)]\n\nfor i in range(7):\n    print(f\"request {i} -> {round_robin(i)}\")", note: "Round robin is simple and guarantees an even SPREAD across servers over time (each server gets roughly 1/3 of requests here) -- but notice it doesn't account for WHICH user is making the request; consecutive requests from the SAME user could land on different servers."},
      {code: "import hashlib\n\n# Consistent hashing (simplified): the SAME key always maps to the SAME server\nservers = [\"server-A\", \"server-B\", \"server-C\"]\n\ndef hash_route(user_id):\n    h = int(hashlib.sha256(str(user_id).encode()).hexdigest(), 16)\n    return servers[h % len(servers)]\n\nfor user_id in [\"user-42\", \"user-99\", \"user-42\", \"user-7\", \"user-99\"]:\n    print(f\"{user_id} -> {hash_route(user_id)}\")", note: "Every call with the SAME user_id ('user-42' both times, 'user-99' both times) routes to the SAME server -- this is the key property consistent hashing provides, useful when a server caches or holds state specific to that user, so repeated requests benefit from hitting the server that already 'knows' them."}
    ],
    mistakes: ["Using round robin when session/state affinity matters — a user's requests could bounce between servers that don't share their session data.","Assuming a load balancer solves scaling by itself — it only DISTRIBUTES traffic; the servers and database behind it still need to handle the actual load and data consistency.","Not considering server HEALTH — real load balancers also need to detect and route around a server that's down, not just blindly cycle through a fixed list."],
    handsOn: "Run both examples. For round_robin, confirm requests spread evenly (roughly 1/3 to each server over enough requests). For hash_route, confirm the SAME user_id always maps to the SAME server. Write one sentence describing a scenario where you'd choose consistent hashing over round robin.",
    doneWhen: "You can explain what a load balancer does, implement a basic round-robin and hash-based routing strategy, and articulate when each strategy fits better.",
    checks: [
      {q: "When would you prefer consistent hashing over simple round robin for load balancing?", a: "When a server holds state specific to a particular user or key (like session data or a local cache) — consistent hashing guarantees the same user's requests always land on the same server, so that server-side state stays useful across repeated requests, which round robin doesn't guarantee."}
    ],
    keyTakeaways: ["A load balancer distributes incoming requests across multiple servers.", "Round robin spreads requests evenly but ignores request identity/affinity.", "Consistent hashing routes the same key to the same server consistently, useful for session/state affinity."],
    resources: [
      {label: "AWS — What Is Load Balancing?", url: "https://aws.amazon.com/what-is/load-balancing/", kind: "docs"},
      {label: "System Design Primer — Load balancer", url: "https://github.com/donnemartin/system-design-primer#load-balancer", kind: "reference"}
    ]
  },
  {
    id: "swe-capstone", title: "Capstone: design a system, end to end",
    concept: "Your capstone: pick a real, familiar product (a URL shortener, a to-do app, a simple chat app) and design it end to end using everything from this module — sketch the REST API (lesson 1), decide what data needs a database and whether it needs to scale (lesson 2), identify what's worth caching (lesson 3), and explain how you'd handle more traffic than one server can take (lesson 4). Then rehearse explaining your design out loud — system design interviews are conversations, not written exams, and the reasoning matters more than a 'correct' diagram.",
    analogy: "This capstone is like being asked to design a building: you don't need to be a structural engineer who calculates load-bearing exactly, but you DO need to reasonably explain where the walls go, why the foundation is sized the way it is, and what happens if more floors get added later. System design interviews test that same level of reasoned, defensible judgment — not a perfect, exhaustively-detailed blueprint.",
    examples: [
      {code: "# A worked skeleton: designing a URL shortener (a classic system-design interview question)\ndesign_notes = \"\"\"\nAPI (lesson 1):\n  POST /urls        -> body: {long_url} -> returns {short_code}\n  GET  /{short_code} -> redirects to the original long_url\n\nData (lesson 2):\n  A table: short_code (indexed) -> long_url, created_at, click_count\n  Read-heavy (many redirects per shortened link) -> reads massively outnumber writes\n\nCaching (lesson 3):\n  Cache popular short_code -> long_url lookups in memory\n  -- redirects are the hot path and rarely change once created\n\nScaling (lesson 4):\n  Multiple redirect servers behind a load balancer (round robin is fine here --\n  no session state needed, each redirect lookup is independent)\n\"\"\"\nprint(design_notes)", note: "This is a WORKED EXAMPLE showing the reasoning shape expected, not a template to copy verbatim for your own capstone -- notice each design decision is JUSTIFIED by a concrete property of the problem (read-heavy access pattern -> caching makes sense; no session state -> round robin is fine), which is exactly the kind of reasoning an interviewer wants to hear."}
    ],
    mistakes: ["Jumping straight to a complex distributed-systems answer for a problem that doesn't need it — matching the design's complexity to the ACTUAL scale/requirements is part of good judgment.","Presenting a design with no justification for each decision — 'why cache this' and 'why this scaling approach' matter more than the diagram itself.","Treating this as a purely academic exercise — pick a product you actually understand well; your reasoning will be sharper and more specific."],
    handsOn: "Pick your own product idea and write a design following the same four-section structure (API, data, caching, scaling) as the URL-shortener example, with a one-sentence justification for each decision. Then rehearse explaining it out loud in under 3 minutes.",
    doneWhen: "You have a complete, justified system design covering API, data, caching, and scaling for a product of your choice, and can explain it fluently in under 3 minutes.",
    checks: [],
    keyTakeaways: ["System design interviews test justified reasoning, not a single 'correct' diagram.", "Match design complexity to the problem's actual scale and requirements.", "Every design decision should be backed by a concrete reason tied to the problem's properties."],
    resources: [
      {label: "System Design Primer (GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "reference"},
      {label: "Common Core — Career track (interview framing)", url: "/stream/common-core", kind: "course"},
      {label: "Forage Interview — practice this design out loud", url: "/interview", kind: "practice"}
    ]
  }
  ]
};
