// FORAGE — Software Engineer path, Module 2: Core Data Structures
// Standard CS data structure facts, verified by implementing and running each structure's
// operations in real Python and confirming outputs. Light quiz model: 1 sharpest MCQ per lesson.

module.exports = {
  id: "swe-datastructures", title: "Core Data Structures",
  why: "Every technical interview leans on a small set of core data structures — linked lists, stacks, queues, trees, graphs. Module 1 gave you the complexity lens; this module gives you the structures themselves, built from scratch so you understand what's actually happening underneath Python's built-ins.",
  topics: [
  {
    id: "swe-linked-lists", title: "Linked lists — nodes connected by pointers",
    concept: "A linked list is a sequence of NODES, where each node holds a value and a reference ('pointer') to the next node — unlike a Python list (a contiguous array), a linked list's elements can live anywhere in memory, connected only by these references. This trades away O(1) index access (to reach node #50 you must walk through 49 previous nodes — O(n)) for O(1) insertion/deletion at a known position WITHOUT shifting anything else, since you only need to rewire a couple of pointers.",
    analogy: "A Python list is a row of numbered parking spots — you can jump straight to spot #50. A linked list is more like a treasure hunt: each clue (node) tells you where to find the NEXT clue, but to reach the 50th clue you must walk through the first 49. The upside: inserting a new clue into the middle of a treasure hunt just means changing what one clue points to — no need to renumber the spots after it.",
    examples: [
      {code: "class Node:\n    def __init__(self, value):\n        self.value = value\n        self.next = None\n\nclass LinkedList:\n    def __init__(self):\n        self.head = None\n\n    def push_front(self, value):        # O(1) -- no shifting needed\n        node = Node(value)\n        node.next = self.head\n        self.head = node\n\n    def to_list(self):                  # O(n) -- must walk every node\n        result = []\n        current = self.head\n        while current:\n            result.append(current.value)\n            current = current.next\n        return result\n\nll = LinkedList()\nfor v in [3, 2, 1]:\n    ll.push_front(v)\nprint(ll.to_list())   # [1, 2, 3] -- each push_front lands at the head", note: "push_front is O(1) regardless of list length -- it just creates a node and rewires two pointers (node.next and self.head). Contrast this with a Python list's insert(0, x), which is O(n) because everything must physically shift. to_list() demonstrates the O(n) cost of linked-list traversal -- you cannot jump to an arbitrary position."},
      {code: "def find(ll, target):     # O(n) -- must walk from the head\n    current = ll.head\n    index = 0\n    while current:\n        if current.value == target:\n            return index\n        current = current.next\n        index += 1\n    return -1\n\nprint(find(ll, 2))   # 1 -- found at index 1\nprint(find(ll, 99))  # -1 -- not found, walked the whole list", note: "Unlike a Python list's O(1) index access, finding ANYTHING in a linked list -- even checking if a value exists -- requires an O(n) walk from the head, since there's no way to jump directly to a middle position."}
    ],
    mistakes: ["Assuming a linked list has O(1) index access like a Python list — it doesn't; reaching position i is O(i).","Forgetting to update ALL relevant pointers when inserting/deleting a node — a classic bug source (e.g. forgetting to set node.next before reassigning head).","Using a linked list when you actually need frequent random access — a Python list (or array) is the better tool when index-based access matters more than mid-list insertion."],
    handsOn: "Implement the LinkedList class above, push a few values, and confirm to_list() and find() behave as shown. Then add a push_back(value) method that appends to the END of the list (you'll need to walk to the last node first) and confirm its complexity is O(n), unlike push_front's O(1).",
    doneWhen: "You can implement a basic singly linked list with push_front and traversal, and explain the O(1)-insert-vs-O(n)-access tradeoff versus a Python list.",
    checks: [
      {q: "Why is push_front O(1) on a linked list but O(n) on a Python list (via insert(0, x))?", a: "A linked list's push_front only needs to create a new node and rewire two pointers (the new node's .next and the list's head reference) — no other nodes move. A Python list's insert(0, x) must physically shift every existing element over by one position, which is O(n)."}
    ],
    keyTakeaways: ["A linked list trades O(1) index access (which it lacks) for O(1) insertion/deletion at a known position.", "Traversal and search in a linked list are O(n) — no jumping to arbitrary positions.", "Use a linked list when frequent insertion/deletion matters more than random access."],
    resources: [
      {label: "MIT OCW — 6.006 Introduction to Algorithms (linked lists)", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", kind: "course"},
      {label: "NeetCode — Linked List patterns", url: "https://neetcode.io/roadmap", kind: "practice"}
    ]
  },
  {
    id: "swe-stacks-queues", title: "Stacks and queues — order matters",
    concept: "A STACK is Last-In-First-Out (LIFO) — the most recently added item is the first one removed (think a stack of plates: you take from the top). A QUEUE is First-In-First-Out (FIFO) — the first item added is the first one removed (think a checkout line). Python lists work fine as a stack (`.append()`/`.pop()` are both O(1) at the end), but make a POOR queue (`.pop(0)` is O(n) — everything shifts). For an efficient queue, use `collections.deque`, which gives O(1) operations at BOTH ends.",
    analogy: "A stack is a stack of plates in a cabinet — you always add and remove from the TOP; the plate you put in last is the first one you'll use next. A queue is a line at a coffee shop — whoever arrived FIRST gets served first, regardless of who's added to the back of the line most recently.",
    examples: [
      {code: "# Stack: Python list works great -- LIFO via append/pop at the end\nstack = []\nstack.append(1)\nstack.append(2)\nstack.append(3)\nprint(stack.pop())   # 3 -- last in, first out\nprint(stack.pop())   # 2\nprint(stack)          # [1] -- only the first pushed item remains", note: "append() and pop() (no argument, meaning pop from the end) are both O(1) on a Python list -- exactly what a stack needs, since both operations happen at the SAME end (the top)."},
      {code: "from collections import deque\nimport time\n\n# Queue: use deque, NOT a plain list\nqueue = deque()\nqueue.append(\"first\")\nqueue.append(\"second\")\nqueue.append(\"third\")\nprint(queue.popleft())   # 'first' -- first in, first out\nprint(queue.popleft())   # 'second'\nprint(list(queue))        # ['third']\n\n# Why not a plain list for a queue: pop(0) is O(n)\nbad_queue = list(range(200_000))\nt0 = time.perf_counter()\nfor _ in range(2000):\n    bad_queue.pop(0)          # O(n) each time -- everything shifts\nt1 = time.perf_counter()\n\ngood_queue = deque(range(200_000))\nt2 = time.perf_counter()\nfor _ in range(2000):\n    good_queue.popleft()       # O(1) each time\nt3 = time.perf_counter()\nprint(f\"list.pop(0) x2000: {(t1-t0)*1000:.1f} ms\")\nprint(f\"deque.popleft() x2000: {(t3-t2)*1000:.1f} ms\")", note: "deque.popleft() is O(1) because deque is implemented as a doubly-linked block structure optimized for both ends; list.pop(0) is O(n) because every remaining element must shift left. The timing gap should be dramatic -- this is a very common real-world performance bug when someone reaches for a plain list as a queue."}
    ],
    mistakes: ["Using a plain Python list with `.pop(0)` as a queue — it's O(n) per operation, an easy-to-miss performance bug at scale.","Confusing stack (LIFO) and queue (FIFO) order in an interview under pressure — anchor to a concrete mental image (plates vs. checkout line) to keep them straight.","Not knowing `collections.deque` exists — it's the standard, efficient tool for queue-like access patterns in Python."],
    handsOn: "Run both examples. For the timing comparison, confirm deque.popleft() is meaningfully faster than list.pop(0) at scale. Then implement a simple 'balanced parentheses' checker using a stack (push on '(', pop on ')', valid if the stack ends empty) and test it on a few strings.",
    doneWhen: "You can explain LIFO vs FIFO, know when to use a plain list (stack) versus deque (queue), and have implemented one classic stack-based algorithm.",
    checks: [
      {q: "Why is collections.deque preferred over a plain Python list for queue operations (removing from the front)?", a: "A plain list's pop(0) is O(n) because every remaining element must shift left to fill the gap; deque is implemented to support O(1) operations at both ends, making it the correct efficient choice for FIFO queue behavior."}
    ],
    keyTakeaways: ["A stack is LIFO (last in, first out); a queue is FIFO (first in, first out).", "A Python list works well as a stack (append/pop at the end are O(1)).", "Use collections.deque for a queue — list.pop(0) is an O(n) performance trap."],
    resources: [
      {label: "Python docs — collections.deque", url: "https://docs.python.org/3/library/collections.html#collections.deque", kind: "docs"},
      {label: "NeetCode — Stack patterns", url: "https://neetcode.io/roadmap", kind: "practice"}
    ]
  },
  {
    id: "swe-trees-intro", title: "Trees — hierarchical structure",
    concept: "A tree is a hierarchical structure of nodes where each node has at most a fixed set of CHILDREN, starting from one ROOT node with no parent. A BINARY TREE restricts each node to at most two children (commonly called 'left' and 'right'). A BINARY SEARCH TREE (BST) adds an ordering rule: everything in a node's left subtree is smaller, everything in its right subtree is larger — this ordering is what makes search, insert, and delete all O(log n) on average (in a balanced tree), by letting you eliminate half the remaining tree at each step, just like binary search on a sorted array.",
    analogy: "A tree is like an org chart — one CEO (root) with direct reports (children), who have their own reports, and so on. A binary search tree is like a very organized filing cabinet with a rule: at every drawer, files with SMALLER numbers go left, LARGER numbers go right — following that one rule at every level lets you find any file by eliminating half the remaining drawers at each step, the same idea as binary search.",
    examples: [
      {code: "class TreeNode:\n    def __init__(self, value):\n        self.value = value\n        self.left = None\n        self.right = None\n\ndef bst_insert(root, value):\n    if root is None:\n        return TreeNode(value)\n    if value < root.value:\n        root.left = bst_insert(root.left, value)\n    else:\n        root.right = bst_insert(root.right, value)\n    return root\n\ndef bst_search(root, target):     # O(log n) average on a balanced BST\n    if root is None:\n        return False\n    if root.value == target:\n        return True\n    elif target < root.value:\n        return bst_search(root.left, target)\n    else:\n        return bst_search(root.right, target)\n\nroot = None\nfor v in [50, 30, 70, 20, 40, 60, 80]:\n    root = bst_insert(root, v)\n\nprint(bst_search(root, 40))   # True\nprint(bst_search(root, 99))   # False", note: "Each bst_search call eliminates roughly half the remaining tree at each step (going left or right based on the comparison), the same logarithmic idea as binary search on a sorted array -- but here the structure itself encodes the ordering, rather than needing a pre-sorted array."},
      {code: "def inorder_traversal(root, result=None):    # visits nodes in SORTED order for a BST\n    if result is None:\n        result = []\n    if root:\n        inorder_traversal(root.left, result)\n        result.append(root.value)\n        inorder_traversal(root.right, result)\n    return result\n\nprint(inorder_traversal(root))   # [20, 30, 40, 50, 60, 70, 80] -- fully sorted", note: "In-order traversal (left, then node, then right) of a BST always visits values in SORTED order -- a direct, provable consequence of the BST ordering rule, and a common way to confirm a tree is a valid BST or to extract sorted data from one."}
    ],
    warn: "A BST's O(log n) operations assume the tree is reasonably BALANCED. Inserting already-sorted data one at a time into a naive BST (like this example) can degrade it into a straight line — effectively a linked list — making operations O(n) in the worst case. Real-world code often uses self-balancing variants (e.g. Python's built-in structures, or libraries) to guarantee balance.",
    mistakes: ["Forgetting a naive BST can degrade to O(n) if inserted data arrives in sorted order — balance isn't automatic without extra logic.","Confusing 'binary tree' (at most 2 children, no ordering rule) with 'binary SEARCH tree' (at most 2 children, WITH the left-smaller/right-larger ordering rule).","Writing traversal recursion without a proper base case (`if root:`) — an easy source of infinite recursion or crashes on empty subtrees."],
    handsOn: "Implement bst_insert, bst_search, and inorder_traversal as shown, insert the same values, and confirm the outputs. Then insert values in already-SORTED order (e.g. 1,2,3,4,5) and observe (by checking tree depth, or just reasoning about the resulting shape) that the tree degrades into a straight line rather than staying balanced.",
    doneWhen: "You can implement basic BST insert/search, explain why in-order traversal produces sorted output, and describe the balance assumption behind BST's O(log n) claim.",
    checks: [
      {q: "Why can a naive binary search tree's operations degrade from O(log n) to O(n) in the worst case?", a: "If data is inserted in an already-sorted order (or another adversarial order), each new node only ever goes to one side, producing a tree shaped like a straight line rather than a balanced structure — at that point, search/insert must walk through nearly every node, just like a linked list, losing the O(log n) benefit."}
    ],
    keyTakeaways: ["A binary search tree keeps values ordered (left < node < right), enabling O(log n) average search/insert.", "In-order traversal of a BST visits nodes in sorted order.", "A naive BST can degrade to O(n) if it becomes unbalanced (e.g. from sorted-order insertion)."],
    resources: [
      {label: "MIT OCW — 6.006 Introduction to Algorithms (BSTs)", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", kind: "course"},
      {label: "NeetCode — Trees patterns", url: "https://neetcode.io/roadmap", kind: "practice"}
    ]
  },
  {
    id: "swe-graphs-intro", title: "Graphs — nodes and the connections between them",
    concept: "A graph generalizes a tree: a set of NODES (vertices) connected by EDGES, with no restriction to a hierarchy — any node can connect to any other, and cycles are allowed. Graphs model an enormous range of real problems: social networks (people = nodes, friendships = edges), maps (locations = nodes, roads = edges), dependency chains (tasks = nodes, 'must happen before' = edges). The two standard traversal algorithms are BFS (Breadth-First Search — explore level by level, using a queue) and DFS (Depth-First Search — go as deep as possible down one path before backtracking, using a stack or recursion).",
    analogy: "If a tree is a strict org chart (one boss per person, no loops), a graph is more like an actual social network — any two people can be connected, connections can loop back around, and there's no single 'root' person everyone reports to. BFS exploring a graph is like a ripple spreading outward from a dropped stone, reaching all immediate neighbors before moving further out; DFS is like exploring a maze by committing to one path as far as it goes before backtracking to try another.",
    examples: [
      {code: "from collections import deque\n\n# Adjacency list: a common, memory-efficient graph representation\ngraph = {\n    \"A\": [\"B\", \"C\"],\n    \"B\": [\"A\", \"D\"],\n    \"C\": [\"A\", \"D\"],\n    \"D\": [\"B\", \"C\", \"E\"],\n    \"E\": [\"D\"],\n}\n\ndef bfs(graph, start):\n    visited = {start}\n    queue = deque([start])\n    order = []\n    while queue:\n        node = queue.popleft()\n        order.append(node)\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return order\n\nprint(bfs(graph, \"A\"))   # ['A', 'B', 'C', 'D', 'E'] -- explores level by level", note: "BFS uses a queue (FIFO, from the last lesson) to guarantee it fully explores everything at the CURRENT distance from the start before moving further out -- this is exactly why BFS is the standard choice for finding the SHORTEST path in an unweighted graph."},
      {code: "def dfs(graph, start, visited=None, order=None):\n    if visited is None:\n        visited = set()\n        order = []\n    visited.add(start)\n    order.append(start)\n    for neighbor in graph[start]:\n        if neighbor not in visited:\n            dfs(graph, neighbor, visited, order)\n    return order\n\nprint(dfs(graph, \"A\"))   # ['A', 'B', 'D', 'C', 'E'] -- commits deep before backtracking", note: "DFS uses recursion (an implicit stack, tying back to the LIFO idea from the last lesson) to plunge as deep as possible down one path -- notice it visits D before C, going A->B->D deep first, then backtracking to reach C -- the opposite exploration order from BFS's level-by-level sweep."}
    ],
    mistakes: ["Forgetting to track VISITED nodes — without it, a graph with a cycle causes infinite looping.","Using DFS when you actually need the SHORTEST path in an unweighted graph — BFS guarantees shortest path by construction; DFS does not.","Confusing an adjacency list (memory-efficient, good for sparse graphs) with an adjacency matrix (simpler but O(n²) memory) without considering which fits the problem's scale."],
    handsOn: "Implement both bfs and dfs on the example graph and confirm the traversal orders shown. Then add a new node 'F' connected only to 'E', re-run both traversals, and confirm F appears (reachable) — then remove the visited-tracking logic temporarily and observe what happens on a graph with a cycle (be ready to interrupt an infinite loop).",
    doneWhen: "You can implement BFS and DFS using an adjacency list, explain why BFS guarantees shortest path in an unweighted graph, and understand why visited-tracking is essential.",
    checks: [
      {q: "Why does BFS (not DFS) guarantee finding the shortest path in an unweighted graph?", a: "BFS explores the graph level by level using a queue, fully processing every node at the current distance before moving further out — so the first time it reaches a target node, it's guaranteed to be via the shortest possible number of edges. DFS commits deeply down one path first and offers no such guarantee."}
    ],
    keyTakeaways: ["A graph generalizes a tree: any node can connect to any other, and cycles are allowed.", "BFS (queue-based) explores level by level and guarantees shortest path in unweighted graphs; DFS (stack/recursion-based) explores deeply first.", "Tracking visited nodes is essential to avoid infinite loops on graphs with cycles."],
    resources: [
      {label: "MIT OCW — 6.006 Introduction to Algorithms (graphs, BFS/DFS)", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", kind: "course"},
      {label: "NeetCode — Graphs patterns", url: "https://neetcode.io/roadmap", kind: "practice"}
    ]
  }
  ]
};
