import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/legal/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Forage",
  description: "The terms that govern your use of Forage.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" updated="20 July 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of Forage
        (&quot;Forage&quot;, &quot;we&quot;, &quot;us&quot;), available at forage.co.in and
        related subdomains (the &quot;Service&quot;). By creating an account or otherwise
        using the Service, you agree to these Terms. If you don&apos;t agree, please don&apos;t
        use the Service.
      </p>

      <h2>1. What Forage is</h2>
      <p>
        Forage is an educational platform teaching technology skills through lessons, quizzes,
        an AI-assisted tutor, and a voice-based AI mock interview feature. A free tier
        (&quot;Common Core&quot;) is available to all users; additional career paths and
        features may require a paid plan (&quot;Pro&quot;).
      </p>

      <h2>2. Your account</h2>
      <p>
        You&apos;re responsible for keeping your account credentials secure and for all
        activity under your account. You must provide accurate information when signing up
        and are responsible for keeping it up to date. You must be at least 13 years old to
        use the Service.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose, or to harass, abuse, or harm another person.</li>
        <li>Attempt to gain unauthorized access to the Service, other accounts, or any systems or networks connected to the Service.</li>
        <li>Interfere with or disrupt the Service, including by circumventing rate limits, usage caps, or access controls.</li>
        <li>Scrape, copy, resell, or redistribute lesson content, quiz content, or any part of the Service without our written permission.</li>
        <li>Use the AI Tutor or AI Interview features to generate harmful, abusive, or illegal content.</li>
      </ul>

      <h2>4. Content and intellectual property</h2>
      <p>
        Lesson content, quizzes, and course materials on Forage are original works created for
        the Service and are owned by Forage (or licensed to us). You&apos;re granted a
        personal, non-transferable license to access and use this content for your own
        learning while your account is active — not to republish, redistribute, or use it
        commercially. Where lessons link to third-party documentation or resources, those
        remain the property of their respective owners.
      </p>
      <p>
        Any notes, code you write, or other content you submit through the Service remain
        yours. By submitting them (e.g. as part of a hands-on exercise), you grant us a
        limited license to store and process them solely to provide the Service to you.
      </p>

      <h2>5. Paid plans and billing</h2>
      <p>
        Some features require a paid Pro subscription. Prices, billing frequency, and payment
        methods will be clearly shown before you pay. See our{" "}
        <a href="/refund">Refund Policy</a> for cancellation and refund terms. We reserve the
        right to change pricing for future billing periods with reasonable advance notice.
      </p>

      <h2>6. AI features</h2>
      <p>
        Forage Tutor and Forage Interview are AI-assisted features. Responses are generated by
        third-party AI models and, while we ground the underlying lesson content in verified
        sources, AI-generated responses in the Tutor and Interview features may occasionally
        be inaccurate or incomplete. They&apos;re a learning aid, not professional certification,
        career, or legal advice — use your own judgment.
      </p>

      <h2>7. Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time. We may suspend or
        terminate access to your account if you violate these Terms, misuse the Service, or
        engage in activity that harms Forage or other users.
      </p>

      <h2>8. Disclaimers and limitation of liability</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties of any kind, express or
        implied. We don&apos;t guarantee that using Forage will result in employment, a
        certification, or any specific outcome. To the maximum extent permitted by law, Forage
        is not liable for indirect, incidental, or consequential damages arising from your use
        of the Service.
      </p>

      <h2>9. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material changes, we&apos;ll
        make reasonable efforts to notify users (e.g. via the Service or email). Continued use
        of the Service after changes take effect means you accept the updated Terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms? Reach us via the details on our <a href="/contact">Contact page</a>.
      </p>
    </LegalPageLayout>
  );
}
