import {
  Terminal,
  Globe,
  BarChart3,
  BrainCircuit,
  GraduationCap,
  Cloud,
  ShieldCheck,
  Code2 as CodeIcon,
  Compass,
  Flame,
  Sparkles,
  Trophy,
  Medal,
  Lock,
  CheckCircle2,
  BookOpen,
  Lightbulb,
  Code2,
  XCircle,
  AlertTriangle,
  Target,
  HelpCircle,
  PenLine,
  LogOut,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
  Loader2,
  type LucideIcon,
} from "lucide-react";

// Stream icon by slug — professional SVG icons, never emoji.
export const streamIcon: Record<string, LucideIcon> = {
  "common-core": GraduationCap,
  "ai-engineer": BrainCircuit,
  aiml: BrainCircuit,
  "software-engineer": CodeIcon,
  fullstack: Globe,
  "data-scientist": BarChart3,
  data: BarChart3,
  "cloud-devops": Cloud,
  cybersecurity: ShieldCheck,
  foundations: Terminal,
};

export {
  Terminal,
  Globe,
  BarChart3,
  BrainCircuit,
  GraduationCap,
  Cloud,
  ShieldCheck,
  Compass,
  Flame,
  Sparkles,
  Trophy,
  Medal,
  Lock,
  CheckCircle2,
  BookOpen,
  Lightbulb,
  Code2,
  XCircle,
  AlertTriangle,
  Target,
  HelpCircle,
  PenLine,
  LogOut,
  ChevronRight,
  ArrowLeft,
  ArrowRight,
  Eye,
  EyeOff,
  Loader2,
};
